activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=82,y=121,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=168,ly=141,xs=146&190,ys=141&141
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=504,y=120,w=60,h=40
- id: A3
  name: |-
    Invoke
    Retryable
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    EndpointUri: ${serviceUrl}
    HttpMethod: POST
    REQUEST_VARIABLE: serviceRequest
    RESPONSE_VARIABLE: serviceResponse
    WORK_DISPLAY_INFO: x=341,y=111,w=100,h=60
    max_tries: '3'
    retry_interval: '10'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=472,ly=140,xs=445&500,ys=140&140
- id: A4
  name: |-
    Create
    Request
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["serviceRequest"]'
    Rule: |-
      serviceRequest = new org.json.JSONObject()
      serviceRequest.put("something", "unimportant")
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=194,y=111,w=100,h=60
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=317,ly=141,xs=298&337,ys=141&141
variables:
  serviceRequest:
    type: org.json.JSONObject
    category: LOCAL
  serviceResponse:
    type: org.json.JSONObject
    category: LOCAL
  serviceUrl:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=48,y=41,w=95,h=26
