activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=84,y=137,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=182,ly=156,xs=148&216,ys=156&156
- id: A3
  name: |-
    Which
    Case?
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: testCase
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=220,y=125,w=85,h=65
  transitions:
  - id: T2
    to: A4
    event: FINISH
    resultCode: err
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=262,ly=226,xs=262&262,ys=194&259
  - id: T4
    to: A5
    event: FINISH
    resultCode: sub
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=320,ly=132,xs=309&406,ys=157&89
- id: A4
  name: Error Sub
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=213,y=263,w=100,h=60
    processname: com.centurylink.mdw.tests.services/ServiceSub.proc
    processversion: '[0.4,1)'
    synchronous: 'false'
    variables: '{"testCase":"$testCase"}'
  transitions:
  - id: T7
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=356,ly=293,xs=317&395,ys=293&293
- id: A5
  name: Cancel Sub
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=410,y=59,w=100,h=60
    processname: com.centurylink.mdw.tests.services/CancelSub.proc
    processversion: '[0.1,1)'
    synchronous: 'false'
    variables: '{"testCase":"$testCase"}'
  transitions:
  - id: T5
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=457,ly=188,xs=457&457,ys=123&254
- id: A6
  name: |-
    Wait
    Forever
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    SLA_DISPLAY_UNITS: Hours
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["eternity",""]]'
    WORK_DISPLAY_INFO: x=398,y=258,w=106,h=68
  transitions:
  - id: T6
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=557,ly=243,xs=509&605,ys=292&194
- id: A7
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=609,y=174,w=60,h=40
variables:
  testCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=40,y=36,w=112,h=26
textNotes:
- id: N1
  content: "Must not complete, \nor Cancel will fail."
  attributes:
    WORK_DISPLAY_INFO: x=388,y=339,w=133,h=40
