activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=75,y=153,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=199,ly=128,xs=139&260,ys=173&84
  - id: T3
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=199,ly=220,xs=139&260,ys=173&268
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=450,y=64,w=60,h=40
- id: A3
  name: |-
    Wait
    Here
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    SLA_DISPLAY_UNITS: Hours
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["never",""]]'
    WORK_DISPLAY_INFO: x=264,y=50,w=111,h=70
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=413,ly=84,xs=379&447,ys=84&84
- id: A4
  name: |-
    Task
    Here
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/An AutoForm Task.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=264,y=233,w=110,h=68
  transitions:
  - id: T4
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=410,ly=260,xs=378&443,ys=260&260
- id: A5
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=448,y=240,w=60,h=40
variables:
  testCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=50,y=50,w=0,h=0
