{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=75,y=153,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=199,ly=128,xs=139&260,ys=173&84"},
          "event": "FINISH",
          "id": "T1",
          "to": "A3"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=199,ly=220,xs=139&260,ys=173&268"},
          "event": "FINISH",
          "id": "T3",
          "to": "A4"
        }
      ]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=450,y=64,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "SLA_DISPLAY_UNITS": "Hours",
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "[[\"never\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=264,y=50,w=111,h=70"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.event.EventWaitActivity",
      "name": "Wait\nHere",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=413,ly=84,xs=379&447,ys=84&84"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "TASK_TEMPLATE": "com.centurylink.mdw.tests.tasks/An AutoForm Task.task",
        "TASK_TEMPLATE_assetVersion": "[0.1,1)",
        "WORK_DISPLAY_INFO": "x=264,y=233,w=110,h=68"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
      "name": "Task\nHere",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=410,ly=260,xs=378&443,ys=260&260"},
        "event": "FINISH",
        "id": "T4",
        "to": "A5"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=448,y=240,w=60,h=40"},
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "PerformanceLevel": "0",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=0,h=0"
  },
  "variables": {"testCase": {
    "category": "INPUT",
    "type": "java.lang.String"
  }}
}