{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=84,y=137,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=182,ly=156,xs=148&216,ys=156&156"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "Expression": "testCase",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=220,y=125,w=85,h=65"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Which\nCase?",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=262,ly=226,xs=262&262,ys=194&259"},
          "event": "FINISH",
          "id": "T2",
          "resultCode": "err",
          "to": "A4"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=320,ly=132,xs=309&406,ys=157&89"},
          "event": "FINISH",
          "id": "T4",
          "resultCode": "sub",
          "to": "A5"
        }
      ]
    },
    {
      "attributes": {
        "WORK_DISPLAY_INFO": "x=213,y=263,w=100,h=60",
        "processname": "com.centurylink.mdw.tests.services/ServiceSub.proc",
        "processversion": "[0.4,1)",
        "synchronous": "false",
        "variables": "{\"testCase\":\"$testCase\"}"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity",
      "name": "Error Sub",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=356,ly=293,xs=317&395,ys=293&293"},
        "event": "FINISH",
        "id": "T7",
        "to": "A6"
      }]
    },
    {
      "attributes": {
        "WORK_DISPLAY_INFO": "x=410,y=59,w=100,h=60",
        "processname": "com.centurylink.mdw.tests.services/CancelSub.proc",
        "processversion": "[0.1,1)",
        "synchronous": "false",
        "variables": "{\"testCase\":\"$testCase\"}"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity",
      "name": "Cancel Sub",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=457,ly=188,xs=457&457,ys=123&254"},
        "event": "FINISH",
        "id": "T5",
        "to": "A6"
      }]
    },
    {
      "attributes": {
        "SLA_DISPLAY_UNITS": "Hours",
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "[[\"eternity\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=398,y=258,w=106,h=68"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.event.EventWaitActivity",
      "name": "Wait\nForever",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=557,ly=243,xs=509&605,ys=292&194"},
        "event": "FINISH",
        "id": "T6",
        "to": "A7"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=609,y=174,w=60,h=40"},
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "PerformanceLevel": "0",
    "WORK_DISPLAY_INFO": "x=40,y=36,w=112,h=26"
  },
  "textNotes": [{
    "attributes": {"WORK_DISPLAY_INFO": "x=388,y=339,w=254,h=27"},
    "content": "Must not complete, or Cancel will fail.",
    "id": "N1"
  }],
  "variables": {"testCase": {
    "category": "INPUT",
    "type": "java.lang.String"
  }}
}