activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=72,y=121,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=193,ly=118,type=Elbow,xs=136&234,ys=141&141
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=487,y=120,w=60,h=40
- id: A3
  name: "Invoke\r\nEmployee Service"
  implementor: com.centurylink.mdw.workflow.adapter.soap.DocumentWebServiceAdapter
  attributes:
    DO_LOGGING: 'True'
    REQUEST_VARIABLE: requestDoc
    RESPONSE_VARIABLE: responseDoc
    WORK_DISPLAY_INFO: x=238,y=112,w=118,h=71
    WSDL: '#{props[''mdw.services.url'']}/SOAP/Employee.wsdl'
    max_tries: '3'
    retry_interval: '30'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=422,ly=140,type=Elbow,xs=360&483,ys=140&140
variables:
  requestDoc:
    type: org.apache.xmlbeans.XmlObject
    category: INPUT
  responseDoc:
    type: org.w3c.dom.Document
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=30,y=29,w=200,h=27
