activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=41,y=231,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=135,ly=252,xs=105&166,ys=252&252
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=540,y=235,w=60,h=40
- id: A3
  name: Fallout
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.services/Fallout.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=369,y=222,w=100,h=60
    Wait for Task: 'TRUE'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=504,ly=256,xs=473&536,ys=256&256
- id: A4
  name: Set stackTrace
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: stackTrace
    Rule: "import java.io.ByteArrayOutputStream\r\nimport java.io.PrintWriter\r\n\r\ndef baos = new ByteArrayOutputStream()\r\ndef writer = new PrintWriter(baos)\r\nexception.printStackTrace(writer)\r\nwriter.flush()\r\nstackTrace = baos.toString()"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=170,y=223,w=100,h=60
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=319,ly=253,xs=274&365,ys=253&253
subprocesses:
- id: P1
  name: Exception Handler
  activities:
  - id: A5
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=330,y=80,w=60,h=40
    transitions:
    - id: T4
      to: A6
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: type=Elbow,lx=425,ly=100,xs=394&456,ys=100&100
  - id: A6
    name: Handle Fallout
    implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
    attributes:
      STATUS_AFTER_EVENT: Cancelled
      TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
      WORK_DISPLAY_INFO: x=460,y=70,w=100,h=60
    transitions:
    - id: T5
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: type=Elbow,lx=595,ly=100,xs=564&626,ys=100&100
  - id: A7
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      WORK_DISPLAY_INFO: x=630,y=80,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=290,y=40,w=440,h=120
variables:
  exception:
    type: java.lang.Exception
    category: INPUT
  stackTrace:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=46,y=41,w=48,h=27
textNotes:
- id: N1
  content: |-
    Always have an embedded
    Exception Handler in package-
    level error processes to avoid
    infinite looping due to exception
    in error process itself.
  attributes:
    WORK_DISPLAY_INFO: x=744,y=48,w=218,h=89
