activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    Parameters: sapId=${request.sapId};workstationId=${request.workstationId}
    WORK_DISPLAY_INFO: x=43,y=102,w=60,h=40
  transitions:
  - id: T1
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=165,ly=129,type=Elbow,xs=107&152,ys=122&122
- id: A5
  name: "Real\r\nLookup?"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: sapId != 'DHO115360' && workstationId != 'dxoakes'
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=156,y=86,w=78,h=76
  transitions:
  - id: T4
    to: A4
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=300,ly=112,type=Elbow,xs=238&361,ys=112&112
  - id: T5
    to: A3
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=292,ly=189,type=Elbow,xs=230&265&265&364,ys=143&143&185&185
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=577,y=180,w=60,h=40
- id: A3
  name: Lookup
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: response
    Rule: "println 'sapId: ' + sapId;\r\nprintln 'workstationId: ' + workstationId;\r\n\r\nresponse = \r\n     '''<GetEmployeeResponse xmlns=\"http://mdw.centurylink.com/serviceTypes\">\r\n          <sapId>DHO115360</sapId>\r\n          <workstationId>dxoakes</workstationId>\r\n          <firstName>Donald</firstName>\r\n          <lastName>Oakes</lastName>\r\n        </GetEmployeeResponse>''';"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=368,y=166,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=527,ly=201,type=Elbow,xs=472&573,ys=200&200
- id: A6
  name: "Populate\r\nObject"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: employee#response
    Rule: "import java.io.ByteArrayOutputStream;\r\n\r\nimport javax.xml.bind.JAXBContext\r\nimport javax.xml.bind.Marshaller\r\n\r\nimport com.centurylink.mdw.java.CompiledJavaCache\r\n\r\nemployee = CompiledJavaCache.getInstance(\"com.centurylink.mdw.tests.services.Employee\", JAXBContext.class.getClassLoader(), runtimeContext.getPackage());\r\nemployee.setSapId(sapId);\r\nemployee.setWorkstationId(workstationId)\r\nemployee.setFirstName(firstName);\r\nemployee.setLastName(lastName);\r\n\r\nByteArrayOutputStream baos = new ByteArrayOutputStream();\r\nJAXBContext jaxbContext = JAXBContext.newInstance(employee.getClass());\r\nMarshaller marshaller = jaxbContext.createMarshaller();\r\nmarshaller.marshal(employee, baos);\r\nresponse = baos.toString();\r\n"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=553,y=81,w=106,h=67
  transitions:
  - id: T6
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=607,ly=154,type=Elbow,xs=607&607,ys=152&176
- id: A4
  name: LDAP Lookup
  implementor: com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter
  attributes:
    AppCuid: prop:LDAP/AppCUID
    AppPassword: prop:LDAP/AppPassword
    BaseDn: prop:LDAP/BaseDN
    Bindings: firstName=givenName;lastName=sn;sapId=saploginid;workstationId=uid
    LdapHost: prop:LDAP/Host
    LdapPort: prop:LDAP/Port
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    SearchContext: ou=People
    SearchFilter: '(#{sapId == '''' || sapId == null ? ''uid='' : ''saploginId=''}#{sapId == '''' || sapId == null ? workstationId : sapId})'
    WORK_DISPLAY_INFO: x=365,y=79,w=100,h=60
  transitions:
  - id: T3
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=539,ly=132,type=Elbow,xs=469&549,ys=110&110
variables:
  employee:
    type: java.lang.Object
    category: LOCAL
  firstName:
    type: java.lang.String
    category: LOCAL
  lastName:
    type: java.lang.String
    category: LOCAL
  request:
    type: javax.xml.bind.JAXBElement
    category: INPUT
  requestHeaders:
    type: java.util.Map<String,String>
    category: INPUT
  response:
    type: com.centurylink.mdw.model.StringDocument
    category: OUTPUT
  sapId:
    type: java.lang.String
    category: INPUT
  workstationId:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: SERVICE
  PerformanceLevel: '3'
  START_TRANSITION_ID: '2346892'
  WORK_DISPLAY_INFO: x=38,y=31,w=131,h=27
