activities:
- id: A4
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=208,y=44,w=60,h=40
  transitions:
  - id: T2
    to: A1
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=86,ly=40,type=Elbow,xs=204&91,ys=64&186
  - id: T3
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=303,ly=81,type=Elbow,xs=272&350,ys=64&64
- id: A3
  name: "LDAP Adapter\r\nMultiple Results"
  implementor: com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter
  attributes:
    AppCuid: ${props['mdw.ldap.app.user']}
    AppPassword: ${props['mdw.ldap.app.password']}
    BaseDn: ${props['mdw.ldap.base.dn']}
    Bindings: matchingCuids=uid;matchingMnetIds=mnetid;unmatchedMultiple=unmatched;matchingHomePhones=homephone
    LdapHost: ${props['mdw.ldap.host']}
    LdapPort: ${props['mdw.ldap.port']}
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    SearchContext: ou=People
    SearchFilter: (sn=${lastNameInput})
    WORK_DISPLAY_INFO: x=233,y=199,w=116,h=67
  transitions:
  - id: T7
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=301,ly=277,type=Elbow,xs=301&301,ys=270&296
- id: A5
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=274,y=390,w=60,h=40
- id: A1
  name: "LDAP Adapter\r\nSingle Result"
  implementor: com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter
  attributes:
    AppCuid: ${props['mdw.ldap.app.user']}
    AppPassword: ${props['mdw.ldap.app.password']}
    BaseDn: ${props['mdw.ldap.base.dn']}
    Bindings: department=departmentname;emailAddress=mail;firstName=givenname;lastName=sn;mnetId=mnetid;phoneNumber=telephonenumber;rcCode=rc;state=st;unmatchedSingle=unmatched;sapId=saploginid
    LdapHost: ${props['mdw.ldap.host']}
    LdapPort: ${props['mdw.ldap.port']}
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    SearchContext: ou=People
    SearchFilter: (uid=${cuid})
    WORK_DISPLAY_INFO: x=36,y=190,w=110,h=69
  transitions:
  - id: T6
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=199,ly=278,type=Elbow,xs=150&250,ys=224&330
- id: A6
  name: Wait 10s
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '10'
    Unit: Seconds
    WORK_DISPLAY_INFO: x=354,y=41,w=100,h=60
  transitions:
  - id: T5
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=348,ly=144,type=Elbow,xs=404&291,ys=105&195
  - id: T8
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=488,ly=72,type=Elbow,xs=458&517,ys=72&72
- id: A7
  name: Sync
  implementor: com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    Synced Activities: "LDAP Adapter\r\nSingle Result#LDAP Adapter\r\nMultiple Results#LDAP Adapter\r\nDocument Binding"
    WORK_DISPLAY_INFO: x=254,y=300,w=100,h=60
  transitions:
  - id: T1
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=304,ly=359,type=Elbow,xs=304&304,ys=364&386
- id: A8
  name: "10 More\r\nSeconds"
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '10'
    Unit: Seconds
    WORK_DISPLAY_INFO: x=521,y=44,w=106,h=67
  transitions:
  - id: T9
    to: A9
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=575,ly=138,type=Elbow,xs=575&575,ys=115&162
- id: A9
  name: "LDAP Adapter\r\nDocument Binding"
  implementor: com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter
  attributes:
    AppCuid: ${props['mdw.ldap.app.user']}
    AppPassword: ${props['mdw.ldap.app.password']}
    BaseDn: ${props['mdw.ldap.base.dn']}
    Bindings: userDocument=results
    LdapHost: ${props['mdw.ldap.host']}
    LdapPort: ${props['mdw.ldap.port']}
    OsgiBundleSymbolicName: com.centurylink.donsservicemix
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    SearchContext: ou=People
    SearchFilter: (saploginid=${sapIdInput})
    WORK_DISPLAY_INFO: x=523,y=166,w=113,h=69
  transitions:
  - id: T10
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=426,ly=249,type=Elbow,xs=519&358,ys=200&330
variables:
  cuid:
    type: java.lang.String
    category: INPUT
  department:
    type: java.lang.String
    category: LOCAL
  emailAddress:
    type: java.lang.String
    category: LOCAL
  firstName:
    type: java.lang.String
    category: LOCAL
  lastName:
    type: java.lang.String
    category: LOCAL
  lastNameInput:
    type: java.lang.String
    category: INPUT
  matchingCuids:
    type: java.util.List<String>
    category: LOCAL
  matchingHomePhones:
    type: java.util.List<String>
    category: LOCAL
  matchingMnetIds:
    type: java.util.List<Integer>
    category: LOCAL
  mnetId:
    type: java.lang.Integer
    category: LOCAL
  phoneNumber:
    type: java.lang.String
    category: LOCAL
  rcCode:
    type: java.lang.String
    category: LOCAL
  sapId:
    type: java.lang.String
    category: LOCAL
  sapIdInput:
    type: java.lang.String
    category: INPUT
  state:
    type: java.lang.String
    category: LOCAL
  unmatchedMultiple:
    type: java.util.List<String>
    category: LOCAL
  unmatchedSingle:
    type: java.lang.String
    category: LOCAL
  userDocument:
    type: org.json.JSONObject
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  START_TRANSITION_ID: '2358799'
  WORK_DISPLAY_INFO: x=20,y=13,w=116,h=27
