activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=69,y=171,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=158,ly=191,xs=133&183,ys=191&191
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=537,y=175,w=60,h=40
- id: A3
  name: |-
    Create
    Request
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["serviceRequest"]'
    Rule: |-
      // empty request is okay
      serviceRequest = new org.json.JSONObject()
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=188,y=157,w=108,h=73
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=325,ly=193,xs=299&352,ys=193&193
- id: A4
  name: |-
    POST
    404
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    EndpointUri: '#{props[''mdw.services.url'']}/api/notfound'
    HttpMethod: POST
    REQUEST_VARIABLE: serviceRequest
    RESPONSE_VARIABLE: serviceResponse
    WORK_DISPLAY_INFO: x=356,y=156,w=112,h=74
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=502,ly=195,xs=472&533,ys=195&195
variables:
  serviceRequest:
    type: org.json.JSONObject
    category: LOCAL
  serviceResponse:
    type: org.json.JSONObject
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=48,y=43,w=164,h=26
