description: Test process for manual task related services.
activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=52,y=92,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=157,ly=104,type=Elbow,xs=116&153,ys=112&112
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=512,y=90,w=60,h=40
- id: A4
  name: "Assign\r\nObj Var"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: objectVar
    Rule: "objectVar = new com.centurylink.mdw.tests.services.MyWorkflowModel()\r\nobjectVar.setFlowmaster('Manoj')"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=157,y=73,w=108,h=72
  transitions:
  - id: T2
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=297,ly=92,type=Elbow,xs=269&325,ys=109&109
- id: A5
  name: "Wait\r\nForever"
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["Hell freezes over",""]]'
    WORK_DISPLAY_INFO: x=329,y=74,w=109,h=70
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=475,ly=110,type=Elbow,xs=442&508,ys=110&110
variables:
  dateVar:
    type: java.util.Date
    category: INPUT
    label: Date Var
    display: Required
  docVar:
    type: org.w3c.dom.Document
    category: INPUT
    display: ReadOnly
  jaxbVar:
    type: javax.xml.bind.JAXBElement
    category: INPUT
  jsonUnassigned:
    type: org.json.JSONObject
    category: LOCAL
    display: ReadOnly
  objectVar:
    type: java.lang.Object
    category: LOCAL
  stringVar:
    type: java.lang.String
    category: INPUT
    label: String Var
    display: Optional
  unassignedVar:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=29,y=21,w=135,h=27
