{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=52,y=92,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=157,ly=104,type=Elbow,xs=116&153,ys=112&112"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=346,y=90,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Output Documents": "objectVar",
        "Rule": "objectVar = new com.centurylink.mdw.tests.services.MyWorkflowModel()\r\nobjectVar.setFlowmaster('Manoj')",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=157,y=73,w=108,h=72"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Assign\r\nObj Var",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=305,ly=110,type=Elbow,xs=269&342,ys=110&110"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=29,y=21,w=135,h=27"
  },
  "description": "Test process for manual task related services.",
  "variables": {
    "dateVar": {
      "category": "INPUT",
      "label": "Date Var",
      "type": "java.util.Date"
    },
    "docVar": {
      "category": "INPUT",
      "type": "org.w3c.dom.Document"
    },
    "jaxbVar": {
      "category": "INPUT",
      "type": "javax.xml.bind.JAXBElement"
    },
    "objectVar": {
      "category": "LOCAL",
      "type": "java.lang.Object"
    },
    "stringVar": {
      "category": "INPUT",
      "label": "String Var",
      "type": "java.lang.String"
    },
    "unassignedVar": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  },
  "version": "0.3"
}