activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=72,y=117,w=60,h=40
  transitions:
  - id: T13
    to: A10
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=179,ly=137,type=Elbow,xs=136&202,ys=137&137
- id: A6
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=595,y=119,w=60,h=40
- id: A5
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=680,y=229,w=60,h=40
- id: A9
  name: "POST\r\nRequest"
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    ConnectTimeout: '60000'
    DO_LOGGING: 'True'
    EndpointUri: '#{props[''mdw.services.url'']}/Services/REST'
    HeadersVariable: headersMap
    HttpMethod: POST
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    REQUEST_VARIABLE: requestDoc
    RESPONSE_VARIABLE: responseDoc
    ReadTimeout: '60000'
    WORK_DISPLAY_INFO: x=442,y=213,w=121,h=76
  transitions:
  - id: T12
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=633,ly=247,type=Elbow,xs=567&676,ys=249&249
- id: A8
  name: "GET\r\nRequest"
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    DO_LOGGING: 'True'
    EndpointUri: '#{props[''mdw.services.url'']}/services/AppSummary'
    HeadersVariable: headersMap
    HttpMethod: GET
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    RESPONSE_VARIABLE: responseDoc
    WORK_DISPLAY_INFO: x=412,y=104,w=116,h=74
  transitions:
  - id: T3
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=566,ly=143,type=Elbow,xs=532&591,ys=139&139
- id: A10
  name: Set Request
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: SetRequest_A10
    Java: |
      package com.centurylink.mdw.tests.services;

      import java.util.Map;
      import java.util.HashMap;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.user.User;
      import com.centurylink.mdw.model.user.Workgroup;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;
      import com.centurylink.mdw.tests.services.GetEmployee;

      public class SetRequest_A10 implements JavaExecutor {

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
          }

          public Object execute(Map<String, Object> variables) throws JavaExecutionException {
              String httpMethod = (String) variables.get("httpMethod");
              if (httpMethod.equals("POST")) {
                  GetEmployee requestDoc = new GetEmployee();
                  requestDoc.setWorkstationId("dxoakes");
                  variables.put("requestDoc", requestDoc);
                  Map<String,String> headers = new HashMap<String,String>();
                  headers.put("my-header", "my-header-value");
                  headers.put("Content-Type", "text/xml");
                  variables.put("headersMap", headers);
              }
              else if (httpMethod.equals("PATCH")) {
                  Workgroup workgroup = new Workgroup(0L, "Patchy Developers", "Dev Group for PATCH");
                  workgroup.setUsers(new User[] { new User("dxoakes") });
                  try {
                      variables.put("patchRequest", workgroup.getJson());
                  }
                  catch (org.json.JSONException ex) {
                      throw new JavaExecutionException(ex.getMessage(), ex);
                  }
              }
              return httpMethod;
          }

      }
    Output Documents: requestDoc#patchRequest#headersMap
    WORK_DISPLAY_INFO: x=206,y=104,w=120,h=74
  transitions:
  - id: T14
    to: A8
    event: FINISH
    resultCode: GET
    attributes:
      TRANSITION_DISPLAY_INFO: lx=358,ly=149,type=Elbow,xs=330&408,ys=141&141
  - id: T15
    to: A9
    event: FINISH
    resultCode: POST
    attributes:
      TRANSITION_DISPLAY_INFO: lx=337,ly=226,type=ElbowV,xs=310&310&438,ys=182&250&250
  - id: T16
    to: A11
    event: FINISH
    resultCode: PATCH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=272,ly=271,type=Elbow,xs=266&266,ys=182&317
- id: A11
  name: "PATCH\r\nRequest"
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    ConnectTimeout: '30000'
    DO_LOGGING: 'True'
    EndpointUri: '#{props[''mdw.services.url'']}/services/com/centurylink/mdw/tests/services/PatchHandler'
    HttpMethod: PATCH
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    REQUEST_VARIABLE: patchRequest
    RESPONSE_VARIABLE: patchResponse
    ReadTimeout: '30000'
    WORK_DISPLAY_INFO: x=205,y=321,w=126,h=79
  transitions:
  - id: T17
    to: A12
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=394,ly=361,type=Elbow,xs=335&453,ys=361&361
- id: A12
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=457,y=341,w=60,h=40
variables:
  headersMap:
    type: java.util.Map<String,String>
    category: LOCAL
  httpMethod:
    type: java.lang.String
    category: INPUT
  patchRequest:
    type: org.json.JSONObject
    category: LOCAL
  patchResponse:
    type: org.json.JSONObject
    category: LOCAL
  requestDoc:
    type: javax.xml.bind.JAXBElement
    category: LOCAL
  responseDoc:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
attributes:
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=39,y=38,w=202,h=27
