{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=80,y=158,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=224,ly=153,type=Elbow,xs=144&264,ys=178&178"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=503,y=158,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "throw new Exception('I've fallen and I can't get up')",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=268,y=151,w=124,h=64"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Error",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=454,ly=178,type=Elbow,xs=396&499,ys=178&178"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=105,h=27"
  },
  "version": "0.2"
}