activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=61,y=93,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=180,ly=113,type=Elbow,xs=125&234,ys=113&113
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=437,y=90,w=60,h=40
- id: A3
  name: Error
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    Java: "package com.centurylink.mdw.tests.services;\r\n\r\nimport java.util.Map;\r\n\r\nimport com.centurylink.mdw.java.JavaExecutionException;\r\nimport com.centurylink.mdw.java.JavaExecutor;\r\nimport com.centurylink.mdw.java.MdwJavaException;\r\nimport com.centurylink.mdw.model.workflow.ActivityRuntimeContext;\r\n\r\npublic class Error_A3 implements JavaExecutor {\r\n\r\n    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {\r\n    }\r\n\r\n    public Object execute(Map<String, Object> variables) throws JavaExecutionException {\r\n        throw new JavaExecutionException(\"I've fallen and I can't get up\");\r\n    }\r\n}\r\n"
    WORK_DISPLAY_INFO: x=238,y=84,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=388,ly=110,type=Elbow,xs=342&433,ys=110&110
variables:
  testCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=28,y=35,w=105,h=27
