activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=69,y=132,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=178,ly=152,xs=133&224,ys=152&152
- id: A2
  name: OK
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=449,y=132,w=60,h=40
- id: A3
  name: |-
    Request
    Valid?
  implementor: com.centurylink.mdw.workflow.activity.validate.SwaggerValidatorActivity
  attributes:
    WORK_DISPLAY_INFO: x=228,y=117,w=111,h=74
    Strict: 'true'
    Validate: '["Body"]'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=383,ly=156,xs=343&444,ys=152&152
  - id: T3
    to: A4
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=287,ly=210,xs=282&282,ys=195&245
- id: A4
  name: Invalid
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=251,y=249,w=60,h=40
variables:
  request:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
  requestHeaders:
    type: java.util.Map<String,String>
    category: INPUT
  response:
    type: com.centurylink.mdw.model.Jsonable
    category: OUTPUT
  responseHeaders:
    type: java.util.Map<String,String>
    category: OUTPUT
attributes:
  NodeStyle: BoxIcon
  requestMethod: POST
  requestParameters: '[["person","Body","true","Person","com.centurylink.mdw.tests.workflow/Person.java"]]'
  ArrowStyle: ArrowEnd
  WORK_DISPLAY_INFO: x=50,y=38,w=69,h=27
  PROCESS_VISIBILITY: SERVICE
  requestPath: Person
