activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=40,y=140,w=60,h=40
  transitions:
  - id: T4
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=140,ly=160,xs=104&176,ys=160&160
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=510,y=140,w=60,h=40
- id: A3
  name: Invoke
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    EndpointUri: ${url}
    HeadersVariable: serviceRequestHeaders
    HttpMethod: POST
    Output Documents: '["serviceRequest"]'
    PostScriptLang: Groovy
    PreScript: |
      if (url.endsWith('/Workgroups')) {
          return '''{
        "name": "Yet another group",
        "description": "a group for testing"
      }'''
      }
    PreScriptLang: Groovy
    REQUEST_VARIABLE: serviceRequest
    RESPONSE_VARIABLE: serviceResponse
    WORK_DISPLAY_INFO: x=350,y=120,w=100,h=80
    max_tries: '2'
    retry_interval: '60'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=480,ly=160,xs=454&506,ys=160&160
- id: A5
  name: |-
    Create
    Request
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: UnparseableResponse_A5
    Java: |
      package com.centurylink.mdw.tests.services;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      import java.util.HashMap;
      import java.util.Map;

      public class UnparseableResponse_A5 implements JavaExecutor {
          private ActivityRuntimeContext context;

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
              this.context = context;
          }

          public Object execute(Map<String,Object> variables) throws JavaExecutionException  {
              // bad request content causes 500 error with XML response
              variables.put("serviceRequest", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n" +
                  "<GetEmployee xmlns:ns2=\"http://mdw.centurylink.com/serviceTypes\">\n" +
                  "</GetEmployee>");
              Map<String,String> requestHeaders = new HashMap<>();
              requestHeaders.put("Content-Type", "text/xml");
              variables.put("serviceRequestHeaders", requestHeaders);
              return null;
          }
      }
    Output Documents: '["serviceRequest","serviceRequestHeaders"]'
    WORK_DISPLAY_INFO: x=180,y=120,w=100,h=80
  transitions:
  - id: T5
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=315,ly=160,xs=284&346,ys=160&160
variables:
  serviceRequest:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
  serviceRequestHeaders:
    type: java.util.Map<String,String>
    category: LOCAL
  serviceResponse:
    type: org.json.JSONObject
    category: LOCAL
  url:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=41,y=40,w=210,h=26
  requestMethod: POST
