activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    Parameters: firstName=${request.firstName};lastName=${request.lastName}
    WORK_DISPLAY_INFO: x=108,y=219,w=60,h=40
  transitions:
  - id: T1
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=319,ly=240,type=Elbow,xs=172&480,ys=238&238
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=484,y=218,w=60,h=40
variables:
  firstName:
    type: java.lang.String
    category: INPUT
  lastName:
    type: java.lang.String
    category: INPUT
  request:
    type: com.centurylink.mdw.common.service.Jsonable
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=50,y=50,w=195,h=27
