activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=33,y=108,w=60,h=40
  transitions:
  - id: T7
    to: A10
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=111,ly=150,type=Elbow,xs=97&134,ys=128&187
- id: A2
  name: Right
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=387,y=404,w=60,h=40
- id: A3
  name: Decide
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Rule: "println(\"kotlin eval testing...\")\r\n\r\ncheck(variables[\"numFlavs\"] == 31) { \"Invalid value for variable numFlavs\" }\r\n\r\nvariables[\"flavor\"]"
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=126,y=391,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    resultCode: Chocolate
    attributes:
      TRANSITION_DISPLAY_INFO: lx=281,ly=406,type=Elbow,xs=230&383,ys=424&424
  - id: T3
    to: A4
    event: FINISH
    resultCode: Vanilla
    attributes:
      TRANSITION_DISPLAY_INFO: lx=183,ly=480,type=Elbow,xs=176&176,ys=455&515
- id: A4
  name: Wrong
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=146,y=519,w=60,h=40
- id: A5
  name: Exec
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Output Documents: '["jsonablePerson"]'
    Rule: "import com.centurylink.mdw.tests.script.Person\r\n\r\nvar person: Person = variables[\"jsonablePerson\"] as Person\r\n\r\n// simple set variable\r\nvariables[\"jsonablePersonName\"] = person.getName()\r\nvariables[\"mrid\"] = runtimeContext.masterRequestId\r\n\r\n// update json content\r\nperson.firstName = \"Linus\"\r\nperson.lastName = \"Torvalds\"\r\n\r\n"
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=289,y=160,w=100,h=65
  transitions:
  - id: T10
    to: A13
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=425,ly=193,type=Elbow,xs=393&448,ys=193&193
- id: A9
  name: Finish
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=620,y=286,w=60,h=40
- id: A10
  name: Which
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: variables["testCase"]
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=138,y=156,w=79,h=63
  transitions:
  - id: T1
    to: A11
    event: FINISH
    resultCode: decide
    attributes:
      TRANSITION_DISPLAY_INFO: lx=188,ly=242,type=Elbow,xs=177&177,ys=223&279
  - id: T4
    to: A5
    event: FINISH
    resultCode: exec
    attributes:
      TRANSITION_DISPLAY_INFO: lx=249,ly=173,type=Elbow,xs=221&285,ys=189&189
- id: A11
  name: Boolean
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: '"decide".equals(variables["testCase"])'
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=135,y=283,w=83,h=60
  transitions:
  - id: T8
    to: A3
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=182,ly=351,type=Elbow,xs=176&176,ys=347&387
  - id: T9
    to: A12
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=234,ly=298,type=Elbow,xs=222&281,ys=316&316
- id: A12
  name: No Way
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=285,y=296,w=60,h=40
- id: A13
  name: Use Class
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Output Documents: '["jsonObject"]'
    Rule: "import com.centurylink.mdw.tests.script.Person\r\nimport com.centurylink.mdw.tests.script.PersonLookup\r\n\r\n// update document value, and reflect changes made previously\r\nval person = variables[\"jsonablePerson\"] as Person\r\nvariables[\"jsonObject\"] = PersonLookup.find(person.lastName!!).getJson()"
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=452,y=162,w=100,h=62
  transitions:
  - id: T11
    to: A14
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=552,ly=253,type=Elbow,xs=504&504,ys=228&273
- id: A14
  name: "Access\r\nfrom Java"
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    Java: |
      package com.centurylink.mdw.tests.script;

      import java.util.Map;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      /**
       * Access kotlin from java.
       */
      public class AccessfromJava_A14 implements JavaExecutor {

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
          }

          public Object execute(Map<String,Object> variables) throws JavaExecutionException {
              variables.put("unfound", PersonLookup.find("Brin").getJson());
              return null;
          }
      }
    Output Documents: '["unfound"]'
    WORK_DISPLAY_INFO: x=457,y=277,w=99,h=66
  transitions:
  - id: T12
    to: A9
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=589,ly=306,type=Elbow,xs=560&616,ys=306&306
variables:
  flavor:
    type: java.lang.String
    category: INPUT
  jsonObject:
    type: org.json.JSONObject
    category: LOCAL
  jsonablePerson:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
  jsonablePersonName:
    type: java.lang.String
    category: LOCAL
  mrid:
    type: java.lang.String
    category: LOCAL
  numFlavs:
    type: java.lang.Integer
    category: INPUT
  testCase:
    type: java.lang.String
    category: INPUT
  unfound:
    type: org.json.JSONObject
    category: LOCAL
  yamlPerson:
    type: org.yaml.snakeyaml.Yaml
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=41,y=46,w=93,h=27
