activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=52,y=79,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=184,ly=98,type=Elbow,xs=116&193,ys=99&99
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=405,y=82,w=60,h=40
- id: A3
  name: "Set mrid variable\r\nfrom runtimeContext"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: mrid = runtimeContext.getMasterRequestId();
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=197,y=74,w=127,h=74
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=365,ly=102,type=Elbow,xs=328&401,ys=102&102
variables:
  mrid:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=28,y=21,w=147,h=27
textNotes:
- id: N4
  content: "TODO: Test other runtimeContext access\r\nbesides masterRequestId."
  attributes:
    WORK_DISPLAY_INFO: x=137,y=191,w=309,h=38
