activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=157,y=90,w=60,h=40
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=160,ly=149,type=Elbow,xs=187&187,ys=134&209
- id: A4
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=158,y=336,w=60,h=40
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=396,y=218,w=60,h=40
- id: A3
  name: JavaScript Activity
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: "localString = inputString + \" added string\";\r\nlocalInt = inputInt + 8;\r\nif (inputString != null)\r\n  \"OutcomeY\";"
    SCRIPT: JavaScript
    WORK_DISPLAY_INFO: x=137,y=213,w=100,h=60
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=188,ly=302,type=Elbow,xs=188&188,ys=277&332
  - id: T2
    to: A2
    event: FINISH
    resultCode: OutcomeY
    attributes:
      TRANSITION_DISPLAY_INFO: lx=317,ly=238,type=Elbow,xs=241&392,ys=238&238
variables:
  bystander:
    type: org.json.JSONObject
    category: LOCAL
  innocent:
    type: org.w3c.dom.Document
    category: LOCAL
  inputInt:
    type: java.lang.Integer
    category: INPUT
  inputString:
    type: java.lang.String
    category: INPUT
  localInt:
    type: java.lang.String
    category: LOCAL
  localString:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  START_TRANSITION_ID: '2330344'
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=29,y=25,w=179,h=27
