spool add_fkeys.lst;

ALTER TABLE ACTIVITY_INSTANCE ADD (
  CONSTRAINT ACTINST_STATUS_FK
    FOREIGN KEY (STATUS_CD) 
	REFERENCES WORK_STATUS (WORK_STATUS_ID),
  CONSTRAINT ACTINST_PROCINST_FK
    FOREIGN KEY (PROCESS_INSTANCE_ID) 
	REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID));

ALTER TABLE EVENT_INSTANCE ADD (
  CONSTRAINT EVENTINST_DOCUMENT_FK 
	FOREIGN KEY (DOCUMENT_ID) 
	REFERENCES DOCUMENT (DOCUMENT_ID));
	
ALTER TABLE PACKAGE_ACTIVITY_IMPLEMENTORS ADD (
  CONSTRAINT PACKAGEIMPL_ACTIMPL_FK
	FOREIGN KEY (ACTIVITY_IMPLEMENTOR_ID) 
	REFERENCES ACTIVITY_IMPLEMENTOR (ACTIVITY_IMPLEMENTOR_ID),
  CONSTRAINT PACKAGEIMPL_PACKAGE_FK 
	FOREIGN KEY (PACKAGE_ID) 
	REFERENCES PACKAGE (PACKAGE_ID));
	
ALTER TABLE PACKAGE_EXTERNAL_EVENTS ADD (
  CONSTRAINT PACKAGEEXTEVENT_EXTEVENT_FK
	FOREIGN KEY (EXTERNAL_EVENT_ID) 
	REFERENCES EXTERNAL_EVENT (EXTERNAL_EVENT_ID),
  CONSTRAINT PACKAGEEXTEVENT_PACKAGE_FK 
	FOREIGN KEY (PACKAGE_ID) 
	REFERENCES PACKAGE (PACKAGE_ID));
	
ALTER TABLE PACKAGE_RULESETS ADD (
  CONSTRAINT FK_PACKAGE_RULESETS_2 
	FOREIGN KEY (RULE_SET_ID) 
	REFERENCES RULE_SET (RULE_SET_ID),
  CONSTRAINT FK_PACKAGE_RULESETS_1 
	FOREIGN KEY (PACKAGE_ID) 
	REFERENCES PACKAGE (PACKAGE_ID));
	
ALTER TABLE PROCESS_INSTANCE ADD (
  CONSTRAINT PROCINST_STATUS_FK 
    FOREIGN KEY (STATUS_CD) 
	REFERENCES WORK_STATUS (WORK_STATUS_ID));

ALTER TABLE TASK ADD (
  CONSTRAINT TASK_TYPE_FK 
	FOREIGN KEY (TASK_TYPE_ID) 
	REFERENCES TASK_TYPE (TASK_TYPE_ID),
  CONSTRAINT TASK_CATEGORY_FK 
	FOREIGN KEY (TASK_CATEGORY_ID) 
	REFERENCES TASK_CATEGORY (TASK_CATEGORY_ID));
	
ALTER TABLE TASK_INSTANCE ADD (
  CONSTRAINT TASK_INSTANCE_STATUS_FK 
	FOREIGN KEY (TASK_INSTANCE_STATUS) 
	REFERENCES TASK_STATUS (TASK_STATUS_ID),
  FOREIGN KEY (TASK_INSTANCE_STATE) 
	REFERENCES TASK_STATE (TASK_STATE_ID));
	
ALTER TABLE USER_GROUP_MAPPING ADD (
  CONSTRAINT USERGRPMAP_USER_FK
	FOREIGN KEY (USER_INFO_ID)
	REFERENCES USER_INFO (USER_INFO_ID),
  CONSTRAINT USERGRPMAP_GROUP_FK
	FOREIGN KEY (USER_GROUP_ID)
	REFERENCES USER_GROUP (USER_GROUP_ID));
	
ALTER TABLE USER_ROLE_MAPPING ADD (
  FOREIGN KEY (USER_ROLE_ID) 
	REFERENCES USER_ROLE (USER_ROLE_ID));

ALTER TABLE VARIABLE_INSTANCE ADD (
  CONSTRAINT VARINST_PROCINST_FK 
	FOREIGN KEY (PROCESS_INST_ID) 
	REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID));
	
ALTER TABLE WORK_TRANSITION_INSTANCE ADD (
  CONSTRAINT TRANSINST_PROCINST_FK
    FOREIGN KEY (PROCESS_INST_ID)
	REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID),
  CONSTRAINT TRANSINST_STATUS_FK
    FOREIGN KEY (STATUS_CD)
	REFERENCES WORK_TRANSITION_STATUS (WORK_TRANSITION_STATUS_ID));

ALTER TABLE TASK_INST_GRP_MAPP ADD (
  CONSTRAINT TASKINSTGRP_GROUP_FK 
  FOREIGN KEY (USER_GROUP_ID) 
  REFERENCES USER_GROUP(USER_GROUP_ID)
);

ALTER TABLE TASK_INST_INDEX ADD (
  CONSTRAINT TASKINSTIDX_TASKINST_FK 
  FOREIGN KEY (TASK_INSTANCE_ID) 
  REFERENCES TASK_INSTANCE(TASK_INSTANCE_ID)
);

ALTER TABLE USER_GROUP ADD (
  CONSTRAINT GROUP_PARENT_FK
    FOREIGN KEY (PARENT_GROUP_ID) 
	REFERENCES USER_GROUP (USER_GROUP_ID));

spool off;
