
DROP TABLE ATTACHMENT;
DROP TABLE INSTANCE_NOTE;
DROP TABLE TASK_INST_INDEX;
DROP TABLE TASK_INST_GRP_MAPP;
DROP TABLE TASK_INSTANCE;
DROP TABLE TASK;
DROP TABLE TASK_TYPE;
DROP TABLE TASK_STATUS;
DROP TABLE TASK_CATEGORY;
DROP TABLE TASK_STATE;

DROP TABLE PACKAGE_EXTERNAL_EVENTS;
DROP TABLE PACKAGE_ACTIVITY_IMPLEMENTORS;
DROP TABLE PACKAGE_RULESETS;
DROP TABLE PACKAGE;

DROP TABLE USER_ROLE_MAPPING;
DROP TABLE USER_GROUP_MAPPING;
DROP TABLE USER_ROLE;
DROP TABLE USER_INFO;
DROP TABLE USER_GROUP;

DROP TABLE EVENT_WAIT_INSTANCE;
DROP TABLE EVENT_INSTANCE;
DROP TABLE EVENT_LOG;
DROP TABLE EVENT_TYPE;
DROP TABLE EXTERNAL_EVENT;

DROP TABLE DOCUMENT;
DROP TABLE WORK_TRANSITION_INSTANCE;
DROP TABLE VARIABLE_INSTANCE;
DROP TABLE ACTIVITY_INSTANCE;
DROP TABLE PROCESS_INSTANCE;

DROP TABLE ACTIVITY_IMPLEMENTOR;
DROP TABLE RULE_SET;
DROP TABLE ATTRIBUTE;

DROP TABLE VARIABLE_TYPE;
DROP TABLE WORK_TRANSITION_STATUS;
DROP TABLE WORK_STATUS;
DROP TABLE RESOURCE_TYPE;

