drop SEQUENCE WORK_TRANS_INST_ID_SEQ;
drop SEQUENCE MDW_COMMON_ID_SEQ;
drop SEQUENCE VARIABLE_INST_ID_SEQ;
drop SEQUENCE MDW_COMMON_INST_ID_SEQ;
drop SEQUENCE ATTACHMENT_ID_SEQ;
drop SEQUENCE ACTIVITY_INSTANCE_ID_SEQ;
drop SEQUENCE EVENT_WAIT_INSTANCE_ID_SEQ;
drop SEQUENCE INSTANCE_NOTE_ID_SEQ;
drop SEQUENCE EVENT_LOG_ID_SEQ;

