activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=70,y=110,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=160,ly=130,xs=134&186,ys=130&130
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=700,y=110,w=60,h=40
- id: A3
  name: Populate
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: JavaObject_A3
    Java: |
      package com.centurylink.mdw.tests.variables;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;

      import java.util.ArrayList;
      import java.util.List;
      import java.util.Map;

      public class JavaObject_A3 implements JavaExecutor {

          public Object execute(Map<String,Object> variables) throws JavaExecutionException  {
              Mountain input = (Mountain)variables.get("input");
              if (input != null)
                  input.setElevation(input.getElevation() - 1);
              variables.put("mountain", new Mountain("Fuji", 12389, "Japan"));
              List<Mountain> mountains = new ArrayList<>();
              mountains.add(new Mountain("Denali", 20310, "United States"));
              mountains.add(new Mountain("K2", 28251, "Pakistan"));
              variables.put("mountains", mountains);
              return null;
          }
      }
    Output Documents: '["mountain","mountains"]'
    WORK_DISPLAY_INFO: x=190,y=100,w=100,h=60
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=320,ly=130,xs=294&346,ys=130&130
- id: A4
  name: Wait
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    SLA_DISPLAY_UNITS: Hours
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["Wait-${masterRequestId}",""]]'
    WORK_DISPLAY_INFO: x=350,y=100,w=100,h=60
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=485,ly=130,xs=454&516,ys=130&130
- id: A5
  name: Update
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["input","mountain","mountains"]'
    Rule: |
      import com.centurylink.mdw.tests.variables.Mountain

      mountain.elevation = mountain.elevation - 1
      mountains.add(new Mountain("Evans", 14271, "United States"))
      if (input != null) {
          input.elevation = input.elevation - 1
      }
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=520,y=100,w=100,h=60
  transitions:
  - id: T4
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=660,ly=130,xs=624&696,ys=130&130
variables:
  input:
    type: java.lang.Object
    category: INPUT
  mountain:
    type: java.lang.Object
    category: LOCAL
  mountains:
    type: java.lang.Object
    category: LOCAL
  testCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=44,y=42,w=104,h=26
