activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=70,y=120,w=60,h=40
  transitions:
  - id: T1
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=310,ly=140,xs=134&486,ys=140&140
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=490,y=120,w=60,h=40
variables:
  input:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
  local:
    type: com.centurylink.mdw.model.Jsonable
    category: LOCAL
  request:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=44,y=39,w=84,h=26
  requestMethod: POST
  requestParameters: '[["mountain","Body","true","","com.centurylink.mdw.tests.variables/Mountain.java"]]'
  requestPath: Jsonable
  requestSummary: Because it's there
