# paths are relative to the location of this file
mdw:
  version: 6.1.14

asset:
  location: ../mdw-workflow/assets

config:
  location: config

data:
  workgroups:
    - Developers
    - MDW Support
