activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=72,y=139,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=165,ly=159,xs=136&194,ys=159&159
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=620,y=142,w=60,h=40
- id: A3
  name: |-
    Determine
    Fortune
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Output Documents: '["response"]'
    Rule: |
      import org.json.JSONObject
      import brave.internal.HexCodec.writeHexLong
      import com.centurylink.mdw.zipkin.tests.Fortune
      import com.centurylink.mdw.zipkin.tests.SpanId

      val username = (variables["request"] as JSONObject).getString("name")
      runtimeContext.logInfo("FortuneSub >> Name: ${username}")
      variables["username"] = username

      val span = brave.Tracing.currentTracer().currentSpan()
      if (span != null) {
          variables["traceId"] = span.context().traceIdString()
          variables["spanId"] = SpanId(span.context().spanId()).hexId()
          span.context().parentId()?.let { variables["parentSpanId"] = SpanId(it).hexId() }
      }
      variables["response"] = Fortune(username, "You will acquire great wealth.")
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=198,y=128,w=110,h=69
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=361,ly=161,xs=312&410,ys=161&161
- id: A4
  name: |-
    Retrieve
    User
  implementor: com.centurylink.mdw.microservice.MicroserviceRestAdapter
  attributes:
    EndpointUri: ${props['mdw.services.url']}/api/Users?find=${username}
    HttpMethod: GET
    Microservice: FindUsers
    RESPONSE_VARIABLE: foundUsers
    WORK_DISPLAY_INFO: x=414,y=132,w=100,h=60
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=567,ly=162,xs=518&616,ys=162&162
variables:
  foundUsers:
    type: org.json.JSONObject
    category: LOCAL
  parentSpanId:
    type: java.lang.String
    category: LOCAL
  request:
    type: org.json.JSONObject
    category: INPUT
  response:
    type: com.centurylink.mdw.model.Jsonable
    category: OUTPUT
  spanId:
    type: java.lang.String
    category: LOCAL
  traceId:
    type: java.lang.String
    category: LOCAL
  username:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: SERVICE
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=44,y=39,w=109,h=26
