<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
  name="wsdl-first"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:tns="http://mdw.centurylink.com/webservice"
  xmlns:typens="http://mdw.centurylink.com/service/types"
  targetNamespace="http://mdw.centurylink.com/webservice">

  <wsdl:types>
    <xsd:schema
      targetNamespace="http://mdw.centurylink.com/service/types"
      elementFormDefault="qualified">
      <xsd:element name="Request">
        <xsd:complexType>
          <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
              <xsd:sequence>
                <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
              </xsd:sequence>
            </xsd:restriction>
          </xsd:complexContent>
        </xsd:complexType>        
      </xsd:element>
      <xsd:element name="Response">
        <xsd:complexType>
          <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
              <xsd:sequence>
                <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
              </xsd:sequence>
            </xsd:restriction>
          </xsd:complexContent>
        </xsd:complexType>        
      </xsd:element>
      <xsd:element name="Fault">
        <xsd:complexType>
          <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
              <xsd:sequence>
                <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
              </xsd:sequence>
            </xsd:restriction>
          </xsd:complexContent>
        </xsd:complexType>        
      </xsd:element>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="Request">
    <wsdl:part
      name="payload"
      element="typens:Request" />
  </wsdl:message>
  <wsdl:message name="Response">
    <wsdl:part
      name="payload"
      element="typens:Response" />
  </wsdl:message>
  <wsdl:message name="Fault">
    <wsdl:part
      name="payload"
      element="typens:Fault" />
  </wsdl:message>

  <wsdl:portType name="MdwService">
    <wsdl:operation name="Invoke">
      <wsdl:input message="tns:Request" />
      <wsdl:output message="tns:Response" />
      <wsdl:fault
        name="Fault"
        message="tns:Fault" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding
    name="MdwSoapBinding"
    type="tns:MdwService">
    <soap:binding
      style="document"
      transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Invoke">
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="Fault">
        <soap:fault
          use="literal"
          name="Fault" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="MdwWebService">
    <wsdl:port
      binding="tns:MdwSoapBinding"
      name="soap">
      <soap:address location="${MDWFramework.MDWDesigner/services.url}/SOAP/MDW%20Baseline/mdw.wsdl" />
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>