<?xml version="1.0" encoding="UTF-8"?>
<definitions
  xmlns:tns="http://mdw.qwest.com/listener/webservice"
  xmlns:wsr="http://www.openuri.org/2002/10/soap/reliability/"
  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding"
  xmlns:conv="http://www.openuri.org/2002/04/wsdl/conversation/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:s="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  targetNamespace="http://mdw.qwest.com/listener/webservice">
  <types
    xmlns:tns="http://mdw.qwest.com/listener/webservice"
    xmlns:wsr="http://www.openuri.org/2002/10/soap/reliability/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding"
    xmlns:conv="http://www.openuri.org/2002/04/wsdl/conversation/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.xmlsoap.org/wsdl/">
    <schema
      xmlns="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://mdw.qwest.com/listener/webservice">
      <import namespace="http://schemas.xmlsoap.org/soap/encoding/">
      </import>
    </schema>
  </types>
  <message name="invokeWebService">
    <part
      xmlns:partns="http://www.w3.org/2001/XMLSchema"
      type="partns:string"
      name="ServiceName">
    </part>
    <part
      xmlns:partns="http://www.w3.org/2001/XMLSchema"
      type="partns:string"
      name="RequestDetails">
    </part>
  </message>
  <message name="invokeWebServiceResponse">
    <part
      xmlns:partns="http://www.w3.org/2001/XMLSchema"
      type="partns:string"
      name="Response">
    </part>
  </message>
  <portType name="MDWWebServicePort">
    <operation name="invokeWebService">
      <input message="tns:invokeWebService">
      </input>
      <output message="tns:invokeWebServiceResponse">
      </output>
    </operation>
  </portType>
  <binding
    type="tns:MDWWebServicePort"
    name="MDWWebServicePort">
    <soap:binding
      style="rpc"
      transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="invokeWebService">
      <soap:operation
        style="rpc"
        soapAction="" />
      <input>
        <soap:body
          namespace="http://mdw.qwest.com/listener/webservice"
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          use="encoded" />
      </input>
      <output>
        <soap:body
          namespace="http://mdw.qwest.com/listener/webservice"
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
          use="encoded" />
      </output>
    </operation>
  </binding>
  <service name="MDWWebService">
    <port
      name="MDWWebServicePort"
      binding="tns:MDWWebServicePort">
      <soap:address location="${mdw.services.url}/MDWWebService" />
    </port>
  </service>
</definitions>