# paths are relative to the location of this file
mdw:
  version: {{mdw-version}}

asset:
  location: {{asset-loc}}

config:
  location: {{config-loc}}

data:
  workgroups:
    - Developers
    - MDW Support
