{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=59,y=118,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=154,ly=123,type=Elbow,xs=123&178,ys=138&138"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=512,y=263,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DO_LOGGING": "True",
        "JNDI Server URL": "mdw-activemq",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "Queue Name": "com.centurylink.mdw.external.event.queue",
        "REQUEST_VARIABLE": "syncRequest",
        "RESPONSE_VARIABLE": "syncResponse",
        "WORK_DISPLAY_INFO": "x=335,y=103,w=99,h=69",
        "Wait for response?": "True"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.adapter.jms.JmsAdapter",
      "name": "Synchronous\r\nJMS Request",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=500,ly=242,type=Elbow,xs=438&542,ys=137&259"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Expression": "synchronous",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=182,y=102,w=95,h=74"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Synchronous?",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=292,ly=119,type=Elbow,xs=281&331,ys=137&137"},
          "event": "FINISH",
          "id": "T3",
          "resultCode": "true",
          "to": "A3"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=240,ly=211,type=Elbow,xs=230&230,ys=175&235"},
          "event": "FINISH",
          "id": "T4",
          "resultCode": "false",
          "to": "A5"
        }
      ]
    },
    {
      "attributes": {
        "DO_LOGGING": "True",
        "JNDI Server URL": "mdw-activemq",
        "Queue Name": "com.centurylink.mdw.external.event.queue",
        "REQUEST_VARIABLE": "asyncRequest",
        "RESPONSE_VARIABLE": "asyncResponse",
        "WORK_DISPLAY_INFO": "x=183,y=239,w=101,h=71",
        "Wait for response?": "False"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.adapter.jms.JmsAdapter",
      "name": "Asynchronous \r\nJMS Request",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=398,ly=283,type=Elbow,xs=288&508,ys=283&283"},
        "event": "FINISH",
        "id": "T5",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=22,y=31,w=235,h=27"
  },
  "variables": {
    "asyncRequest": {
      "category": "INPUT",
      "type": "com.centurylink.mdw.model.StringDocument"
    },
    "asyncResponse": {
      "category": "LOCAL",
      "type": "org.w3c.dom.Document"
    },
    "syncRequest": {
      "category": "INPUT",
      "type": "com.centurylink.mdw.model.StringDocument"
    },
    "syncResponse": {
      "category": "LOCAL",
      "type": "org.apache.xmlbeans.XmlObject"
    },
    "synchronous": {
      "category": "INPUT",
      "type": "java.lang.Boolean"
    }
  },
  "version": "0.4"
}