<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="JMS Adapter OSGi service" version="0.4" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=59,y=118,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=512,y=263,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Synchronous&#13;&#10;JMS Request" Implementation="com.centurylink.mdw.workflow.adapter.jms.JmsAdapter">
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="JNDI Server URL" Value="mdw-activemq"/>
      <bpm:Attribute Name="PostScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="PreScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="Queue Name" Value="com.centurylink.mdw.external.event.queue"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="syncRequest"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="syncResponse"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=335,y=103,w=99,h=69"/>
      <bpm:Attribute Name="Wait for response?" Value="True"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Synchronous?" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptEvaluator">
      <bpm:Attribute Name="Expression" Value="synchronous"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=182,y=102,w=95,h=74"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Asynchronous &#13;&#10;JMS Request" Implementation="com.centurylink.mdw.workflow.adapter.jms.JmsAdapter">
      <bpm:Attribute Name="Correlation ID" Value=""/>
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="JNDI Server URL" Value="mdw-activemq"/>
      <bpm:Attribute Name="Queue Name" Value="com.centurylink.mdw.external.event.queue"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="asyncRequest"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="asyncResponse"/>
      <bpm:Attribute Name="Reply Queue Name" Value=""/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=183,y=239,w=101,h=71"/>
      <bpm:Attribute Name="Wait for response?" Value="False"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A4" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=154,ly=123,type=Elbow,xs=123&amp;178,ys=138&amp;138"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=500,ly=242,type=Elbow,xs=438&amp;542,ys=137&amp;259"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="true" From="A4" To="A3" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=292,ly=119,type=Elbow,xs=281&amp;331,ys=137&amp;137"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="false" From="A4" To="A5" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=240,ly=211,type=Elbow,xs=230&amp;230,ys=175&amp;235"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A5" To="A2" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=398,ly=283,type=Elbow,xs=288&amp;508,ys=283&amp;283"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=22,y=31,w=235,h=27"/>
    <bpm:Variables Name="asyncRequest" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.StringDocument"/>
    </bpm:Variables>
    <bpm:Variables Name="asyncResponse" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="org.w3c.dom.Document"/>
    </bpm:Variables>
    <bpm:Variables Name="synchronous" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Boolean"/>
    </bpm:Variables>
    <bpm:Variables Name="syncRequest" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.StringDocument"/>
    </bpm:Variables>
    <bpm:Variables Name="syncResponse" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="org.apache.xmlbeans.XmlObject"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>