{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=39,y=88,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=132,ly=108,type=Elbow,xs=103&168,ys=108&108"},
        "event": "FINISH",
        "id": "T4",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=506,y=87,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "ServiceInterface": "com.centurylink.mdw.tests.osgi/TestUserService.java",
        "ServiceInterface_assetVersion": "[0.2,1)",
        "ServiceMethod": "ping(AuthenticatedUser user)",
        "ServiceParameters": "user (AuthenticatedUser)=#{user}",
        "ServiceResult": "userResponse",
        "WORK_DISPLAY_INFO": "x=335,y=80,w=100,h=60"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.adapter.osgi.OsgiServiceAdapter",
      "name": "Ping User",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=466,ly=107,type=Elbow,xs=439&502,ys=107&107"},
        "event": "FINISH",
        "id": "T3",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Output Documents": "userVO",
        "PostScriptLang": "Groovy",
        "PreScript": "import com.centurylink.mdw.services.dao.user.cache.UserGroupCache\r\n\r\nuserVO = UserGroupCache.getUser(cuid);\r\n",
        "PreScriptLang": "Groovy",
        "ServiceInterface": "com.centurylink.mdw.tests.osgi/TestUserService.java",
        "ServiceInterface_assetVersion": "[0.2,1)",
        "ServiceMethod": "createUser(Long id, String cuid, String name)",
        "ServiceParameters": "id (Long)=#{userVO.id};cuid (String)=#{userVO.cuid};name (String)=#{userVO.name}",
        "ServiceResult": "user",
        "WORK_DISPLAY_INFO": "x=172,y=77,w=100,h=60"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.adapter.osgi.OsgiServiceAdapter",
      "name": "Create User",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=303,ly=108,type=Elbow,xs=276&331,ys=108&108"},
        "event": "FINISH",
        "id": "T5",
        "to": "A4"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=23,y=20,w=180,h=27"
  },
  "variables": {
    "cuid": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "user": {
      "category": "LOCAL",
      "type": "java.lang.Object"
    },
    "userResponse": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "userVO": {
      "category": "LOCAL",
      "type": "java.lang.Object"
    }
  },
  "version": "0.3"
}