spool create_bam_objs.log;


CREATE TABLE BAM_MASTER_REQUEST
(
  MASTER_REQUEST_ROWID  INT PRIMARY KEY auto_increment,
  MASTER_REQUEST_ID     VARCHAR(64),
  SOURCE_SYSTEM         VARCHAR(32),
  REQUEST_TIME          DATETIME                    NOT NULL,
  RECORD_TIME           DATETIME                    NOT NULL
)auto_increment=1000;

CREATE TABLE BAM_EVENT
(
  EVENT_ROWID           INT PRIMARY KEY auto_increment,
  MASTER_REQUEST_ROWID  INT                  NOT NULL,
  EVENT_NAME            VARCHAR(40)       	 NOT NULL,
  EVENT_CATEGORY        VARCHAR(40),
  EVENT_SUBCATEGORY     VARCHAR(40),
  SOURCE_SYSTEM         VARCHAR(40),
  EVENT_ID              VARCHAR(64),
  EVENT_DATA            VARCHAR(4000),
  RECORD_TIME           DATETIME                    NOT NULL,
  EVENT_TIME            DATETIME                    NOT NULL,
  NOTE                  VARCHAR(4000)
)auto_increment=1000;

ALTER TABLE BAM_EVENT  
 ADD FOREIGN KEY BAM_EVENT_FK (MASTER_REQUEST_ROWID) 
 REFERENCES BAM_MASTER_REQUEST (MASTER_REQUEST_ROWID);

CREATE TABLE BAM_ATTRIBUTE
(
  MASTER_REQUEST_ROWID  INT                  NOT NULL,
  EVENT_ROWID           INT					 NOT NULL,
  COMPONENT_ROWID       INT,
  ATTRIBUTE_NAME        VARCHAR(64)       	 NOT NULL,
  ATTRIBUTE_VALUE       VARCHAR(4000)
);

ALTER TABLE BAM_ATTRIBUTE  
 ADD FOREIGN KEY EVENT_ROWID (EVENT_ROWID) 
 REFERENCES BAM_EVENT (EVENT_ROWID)
 ON DELETE CASCADE;

ALTER TABLE BAM_ATTRIBUTE  
 ADD FOREIGN KEY MASTER_REQUEST_ROWID_FK (MASTER_REQUEST_ROWID) 
 REFERENCES BAM_MASTER_REQUEST (MASTER_REQUEST_ROWID);
 
spool off;
