{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=260,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=210,ly=215,type=Elbow,xs=124&239,ys=280&280"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=480,y=260,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "ChannelName": "CLIENT.MDW",
        "CorrelationId": "444",
        "DO_LOGGING": "true",
        "HostName": "vodclwfmas101.dev.qintra.com",
        "Port": "1991",
        "QueueManagerName": "TESTMC",
        "QueueName": "TEST.QUEUE",
        "REQUEST_VARIABLE": "request",
        "RESPONSE_VARIABLE": "response",
        "ReplyQueueName": "TEST.QUEUE",
        "WORK_DISPLAY_INFO": "x=243,y=249,w=116,h=60",
        "synchronous": "False"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.adapter.mqseries.MqSeriesAdapter",
      "name": "MQ Series Adapter",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=422,ly=280,type=Elbow,xs=363&476,ys=280&280"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "variables": {
    "request": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "response": {
      "category": "OUTPUT",
      "type": "java.lang.String"
    }
  },
  "version": "0.1"
}