activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=65,y=114,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=231,ly=114,type=Elbow,xs=129&245,ys=134&134
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=485,y=114,w=60,h=40
- id: A3
  name: "Stubbed Event\r\nWait"
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: notGonnaHappen-{$MasterRequestID},,false,
    WORK_DISPLAY_INFO: x=249,y=112,w=99,h=72
    rcvdMsgDocVar: notifyPayload
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=417,ly=134,type=Elbow,xs=352&481,ys=134&134
variables:
  notifyPayload:
    type: org.apache.xmlbeans.XmlObject
    category: LOCAL
  request:
    type: com.centurylink.mdw.model.StringDocument
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=33,y=29,w=222,h=27
