activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=49,y=112,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=169,ly=91,type=Elbow,xs=113&222,ys=132&132
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=469,y=112,w=60,h=40
- id: A3
  name: GetEmployee
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    DO_LOGGING: 'True'
    EndpointUri: http://purposely_bogus:10001/MDWHub/Services/REST
    HttpMethod: POST
    REQUEST_VARIABLE: request
    RESPONSE_VARIABLE: response
    WORK_DISPLAY_INFO: x=226,y=107,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=397,ly=132,type=Elbow,xs=330&465,ys=132&132
variables:
  request:
    type: com.centurylink.mdw.model.StringDocument
    category: INPUT
  response:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=26,y=26,w=151,h=27
