activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=35,y=58,w=60,h=40
  transitions:
  - id: T1
    to: A11
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=200,ly=29,type=Elbow,xs=99&151,ys=78&148
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=574,y=233,w=60,h=40
- id: A3
  name: Stubbed Script
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: throw new Exception('Help!')
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=242,y=143,w=100,h=60
  transitions:
  - id: T2
    to: A4
    event: FINISH
    resultCode: toTimer
    attributes:
      TRANSITION_DISPLAY_INFO: lx=354,ly=153,type=Elbow,xs=346&410,ys=177&177
  - id: T4
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=293,ly=214,type=Elbow,xs=294&294,ys=207&225
- id: A4
  name: Stubbed Timer
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '600'
    TIMER_WAIT_DISPLAY_UNITS: Minutes
    WORK_DISPLAY_INFO: x=414,y=151,w=100,h=60
  transitions:
  - id: T3
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=541,ly=169,type=Elbow,xs=518&550,ys=179&179
- id: A5
  name: Finish
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=264,y=229,w=60,h=40
- id: A6
  name: "Stub Test\r\nSubproc"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=554,y=147,w=100,h=60
    processname: com.centurylink.mdw.tests.stubbing/TestActivityStubSubproc
    processversion: '[0.1,1)'
    synchronous: 'TRUE'
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=604,ly=220,type=Elbow,xs=604&604,ys=211&229
- id: A11
  name: Path
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: flowPath
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=121,y=152,w=60,h=40
  transitions:
  - id: T8
    to: A3
    event: FINISH
    resultCode: various
    attributes:
      TRANSITION_DISPLAY_INFO: lx=186,ly=150,type=Elbow,xs=185&238,ys=172&172
  - id: T9
    to: A12
    event: FINISH
    resultCode: all timers
    attributes:
      TRANSITION_DISPLAY_INFO: lx=163,ly=213,type=Elbow,xs=151&151,ys=196&290
- id: A12
  name: Timer 1
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '60'
    TIMER_WAIT_DISPLAY_UNITS: Minutes
    WORK_DISPLAY_INFO: x=104,y=294,w=100,h=60
  transitions:
  - id: T10
    to: A13
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=224,ly=324,type=Elbow,xs=208&241,ys=324&324
- id: A13
  name: Timer 2
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: ${number}
    TIMER_WAIT_DISPLAY_UNITS: Hours
    WORK_DISPLAY_INFO: x=245,y=294,w=100,h=60
  transitions:
  - id: T11
    to: A14
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=361,ly=323,type=Elbow,xs=349&373,ys=323&323
- id: A14
  name: Timer 3
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '7200'
    TIMER_WAIT_DISPLAY_UNITS: Hours
    WORK_DISPLAY_INFO: x=377,y=293,w=100,h=60
  transitions:
  - id: T12
    to: A15
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=503,ly=325,type=Elbow,xs=481&525,ys=325&325
- id: A15
  name: Done
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=529,y=305,w=60,h=40
subprocesses:
- id: P8
  name: Exception Handler
  activities:
  - id: A9
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=273,y=45,w=60,h=40
    transitions:
    - id: T6
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=369,ly=65,type=Elbow,xs=337&401,ys=65&65
  - id: A7
    name: Stubbed Task
    implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
    attributes:
      AlertIntervalUnits: Hours
      Category: COM
      IndexProvider: com.centurylink.mdw.services.task.CustomTaskIndexProvider
      Notices: Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;
      SLAUnits: Hours
      STATUS_AFTER_EVENT: Cancelled
      TaskLogicalId: TestActivityStub:A7
      TaskName: TestActivityStub Fallout
      Variables: scriptActivityExecuted,scriptActivityExecuted,Not Displayed,0,,java.lang.Boolean
      WORK_DISPLAY_INFO: x=405,y=34,w=100,h=60
    transitions:
    - id: T7
      to: A10
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=539,ly=65,type=Elbow,xs=509&566,ys=65&65
  - id: A10
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=570,y=45,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=232,y=20,w=449,h=87
variables:
  flowPath:
    type: java.lang.String
    category: INPUT
  number:
    type: java.lang.Integer
    category: INPUT
  updatedDoc:
    type: org.w3c.dom.Document
    category: LOCAL
  updatedString:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  SLA: '24'
  SLA_UNIT: Hours
  WORK_DISPLAY_INFO: x=23,y=15,w=149,h=27
