spool add_fkeys.lst;

ALTER TABLE ACTIVITY_INSTANCE ADD ( 
  CONSTRAINT ACTINST_PROCINST_FK
    FOREIGN KEY (PROCESS_INSTANCE_ID) 
  REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID));

ALTER TABLE EVENT_INSTANCE ADD (
  CONSTRAINT EVENTINST_DOCUMENT_FK 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES DOCUMENT (DOCUMENT_ID));
  
ALTER TABLE DOCUMENT_CONTENT ADD (
  CONSTRAINT DOCCONTENT_DOCUMENT_FK 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES DOCUMENT (DOCUMENT_ID));

ALTER TABLE USER_GROUP_MAPPING ADD (
  CONSTRAINT USERGRPMAP_USER_FK
  FOREIGN KEY (USER_INFO_ID)
  REFERENCES USER_INFO (USER_INFO_ID),
  CONSTRAINT USERGRPMAP_GROUP_FK
  FOREIGN KEY (USER_GROUP_ID)
  REFERENCES USER_GROUP (USER_GROUP_ID));
  
ALTER TABLE USER_ROLE_MAPPING ADD (
  FOREIGN KEY (USER_ROLE_ID) 
  REFERENCES USER_ROLE (USER_ROLE_ID));
  
ALTER TABLE VARIABLE_INSTANCE ADD (
  CONSTRAINT VARINST_PROCINST_FK 
  FOREIGN KEY (PROCESS_INST_ID) 
  REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID));
  
ALTER TABLE WORK_TRANSITION_INSTANCE ADD (
  CONSTRAINT TRANSINST_PROCINST_FK
    FOREIGN KEY (PROCESS_INST_ID)
  REFERENCES PROCESS_INSTANCE (PROCESS_INSTANCE_ID));

ALTER TABLE TASK_INST_GRP_MAPP ADD (
  CONSTRAINT TASKINSTGRP_GROUP_FK 
  FOREIGN KEY (USER_GROUP_ID) 
  REFERENCES USER_GROUP(USER_GROUP_ID)
);

ALTER TABLE TASK_INST_INDEX ADD (
  CONSTRAINT TASKINSTIDX_TASKINST_FK 
  FOREIGN KEY (TASK_INSTANCE_ID) 
  REFERENCES TASK_INSTANCE(TASK_INSTANCE_ID)
);

ALTER TABLE USER_GROUP ADD (
  CONSTRAINT GROUP_PARENT_FK
    FOREIGN KEY (PARENT_GROUP_ID) 
  REFERENCES USER_GROUP (USER_GROUP_ID));
  
ALTER TABLE SOLUTION_MAP ADD (
  CONSTRAINT SOLUTION_MAP_FK 
  FOREIGN KEY (SOLUTION_ID) 
  REFERENCES SOLUTION(SOLUTION_ID)
);

spool off;