schemaVersion: '6.1'
name: com.centurylink.mdw.react.workflow
version: 6.1.34-SNAPSHOT

dependencies:
  - com.centurylink.mdw.base v6.1.34-SNAPSHOT
  - com.centurylink.mdw.node v6.1.34-SNAPSHOT
  - com.centurylink.mdw.react v6.1.34-SNAPSHOT
