activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=130,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=185,ly=150,xs=124&246,ys=150&150
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=480,y=130,w=60,h=40
- id: A3
  name: |-
    Set
    Version
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: Deleted_A3
    Java: |
      package com.centurylink.mdw.tests.multiver;

      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      import java.util.Map;

      public class Deleted_A3 implements JavaExecutor {
          private ActivityRuntimeContext context;

          public void initialize(ActivityRuntimeContext context) {
              this.context = context;
          }

          public Object execute(Map<String,Object> variables) {
              variables.put("version", context.getProcess().getLabel());
              return null;
          }
      }
    WORK_DISPLAY_INFO: x=250,y=110,w=100,h=80
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=415,ly=150,xs=354&476,ys=150&150
variables:
  version:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=48,y=44,w=75,h=26
