activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=41,y=163,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=146,ly=183,type=Elbow,xs=105&185,ys=183&183
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=605,y=164,w=60,h=40
- id: A3
  name: Wait
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["{$MasterRequestID}",""]]'
    WORK_DISPLAY_INFO: x=189,y=152,w=100,h=60
  transitions:
  - id: T2
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=337,ly=182,type=Elbow,xs=293&381,ys=182&182
- id: A5
  name: Set oldVar
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: InflightBefore_A5
    Java: |
      package com.centurylink.mdw.tests.workflow;

      import java.util.Map;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      public class InflightBefore_A5 implements JavaExecutor {

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
          }

          public Object execute(Map<String,Object> variables) throws JavaExecutionException {
              variables.put("oldVar", "from InflightBefore");
              return null;
          }

      }
    WORK_DISPLAY_INFO: x=385,y=153,w=100,h=60
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=545,ly=184,type=Elbow,xs=489&601,ys=184&184
variables:
  newVar:
    type: java.lang.String
    category: LOCAL
  oldVar:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=46,y=51,w=123,h=27
