activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=74,y=159,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=166,ly=178,xs=138&195,ys=178&178
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=692,y=158,w=60,h=40
- id: A3
  name: before
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |-
      runtimeContext.logDebug("Executing " + runtimeContext.getActivity().getName())
      beforeVar = 'initial version'
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=199,y=149,w=100,h=60
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=342,ly=181,xs=303&381,ys=181&181
- id: A5
  name: Pause
  implementor: com.centurylink.mdw.base.PauseActivity
  attributes:
    WORK_DISPLAY_INFO: x=384,y=162,w=60,h=40
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=482,ly=182,xs=448&516,ys=182&182
- id: A6
  name: after
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: InflightInstanceDef_A6
    Java: |
      package com.centurylink.mdw.tests.multiver;

      import java.util.Map;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      public class InflightInstanceDef_A6 implements JavaExecutor {
          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
          }

          public Object execute(Map<String,Object> variables) throws JavaExecutionException  {
              variables.put("afterVar", "after version"); // to be updated for instance
              return null;
          }
      }
    WORK_DISPLAY_INFO: x=520,y=150,w=100,h=60
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=656,ly=178,xs=624&688,ys=178&178
variables:
  afterVar:
    type: java.lang.String
    category: LOCAL
  beforeVar:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=43,y=38,w=183,h=26
textNotes:
- id: N1
  content: For manual testing
  attributes:
    WORK_DISPLAY_INFO: x=46,y=75,w=152,h=32
