{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=70,y=92,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=185,ly=91,type=Elbow,xs=134&227,ys=112&112"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=424,y=93,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString(); ",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=231,y=85,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Set Info",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=378,ly=113,type=Elbow,xs=335&420,ys=113&113"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=27,y=24,w=172,h=27"
  },
  "variables": {
    "procName": {
      "category": "OUTPUT",
      "type": "java.lang.String"
    },
    "procVer": {
      "category": "OUTPUT",
      "type": "java.lang.String"
    }
  }
}