activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=90,y=140,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=215,ly=160,xs=154&276,ys=160&160
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=310,y=270,w=60,h=40
- id: A3
  name: Set Values 3.0
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: SubprocessMultiver_A3
    Java: |
      package com.centurylink.mdw.tests.multiver;

      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      import java.util.Map;

      public class SubprocessMultiver_A3 implements JavaExecutor {

          private ActivityRuntimeContext runtimeContext;

          @Override
          public void initialize(ActivityRuntimeContext runtimeContext) {
              this.runtimeContext = runtimeContext;
          }

          @Override
          public Object execute(Map<String,Object> variables)  {
              variables.put("version", runtimeContext.getProcess().getLabel());
              variables.put("message", "Hello from version 3.0");
              return null;
          }
      }
    WORK_DISPLAY_INFO: x=280,y=130,w=120,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=340,ly=230,xs=340&340,ys=194&266
variables:
  message:
    type: java.lang.String
    category: LOCAL
  version:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=44,y=38,w=187,h=26
