{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=41,y=101,w=60,h=40"},
      "id": "A10",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=154,ly=121,type=Elbow,xs=105&202,ys=121&121"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=694,y=106,w=60,h=40"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "count++\nprintln \"count: \" + count\n",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=467,y=277,w=100,h=60"
      },
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "count++",
      "transitions": [{
        "attributes": {
          "TRANSITION_DELAY": "0",
          "TRANSITION_DISPLAY_INFO": "lx=576,ly=160,type=ElbowH,xs=463&343&343&472,ys=303&303&135&135",
          "TRANSITION_RETRY_COUNT": "200"
        },
        "event": "FINISH",
        "id": "T14",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Expression": "count > 100",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=476,y=98,w=90,h=47"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Count > 100?",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=599,ly=132,type=ElbowH,xs=570&690,ys=125&125",
            "TRANSITION_RETRY_COUNT": "0"
          },
          "event": "FINISH",
          "id": "T12",
          "resultCode": "true",
          "to": "A5"
        },
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=483,ly=201,type=Elbow,xs=521&521,ys=149&273",
            "TRANSITION_RETRY_COUNT": "200"
          },
          "event": "FINISH",
          "id": "T13",
          "resultCode": "false",
          "to": "A1"
        }
      ]
    },
    {
      "attributes": {
        "Rule": "count = 0",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=206,y=90,w=100,h=60"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "count = 0",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=391,ly=125,type=Elbow,xs=310&472,ys=121&121"},
        "event": "FINISH",
        "id": "T11",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "PerformanceLevel": "0",
    "Response to Invoker": "When Terminate",
    "START_TRANSITION_ID": "2332188",
    "TRANSITION_RETRY_COUNT": "-1",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=20,y=24,w=198,h=27"
  },
  "variables": {
    "Color": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "Run": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "count": {
      "category": "LOCAL",
      "type": "java.lang.Integer"
    }
  },
  "version": "0.5"
}