CREATE TABLE SOLUTION
(
  SOLUTION_ID    BIGINT            PRIMARY KEY auto_increment,
  ID             VARCHAR(128)      NOT NULL, -- TODO: unique constraint
  NAME           VARCHAR(1024)     NOT NULL,
  OWNER_TYPE     VARCHAR(128)      NOT NULL,
  OWNER_ID       VARCHAR(128)      NOT NULL,  
  CREATE_DT      TIMESTAMP         NOT NULL,
  CREATE_USR     VARCHAR(30)       NOT NULL,
  MOD_DT         DATETIME,
  MOD_USR        VARCHAR(30),
  COMMENTS       VARCHAR(1024)
) auto_increment=1000;

CREATE TABLE SOLUTION_MAP
(
  SOLUTION_ID    BIGINT            NOT NULL,
  MEMBER_TYPE    VARCHAR(128)      NOT NULL,
  MEMBER_ID      VARCHAR(128)      NOT NULL,
  CREATE_DT      TIMESTAMP         NOT NULL,
  CREATE_USR     VARCHAR(30)       NOT NULL,
  MOD_DT         DATETIME,
  MOD_USR        VARCHAR(30),
  COMMENTS       VARCHAR(1024)
);

CREATE TABLE VALUE
(
  NAME            VARCHAR(1024)    NOT NULL,
  VALUE           VARCHAR(2048)    NOT NULL,
  OWNER_TYPE      VARCHAR(128)     NOT NULL,
  OWNER_ID        VARCHAR(128)     NOT NULL,
  CREATE_DT       TIMESTAMP        NOT NULL,
  CREATE_USR      VARCHAR(30)      NOT NULL,
  MOD_DT          DATETIME,
  MOD_USR         VARCHAR(30),
  COMMENTS        VARCHAR(1024)
);

ALTER TABLE SOLUTION_MAP ADD
(
  CONSTRAINT SOLUTION_MAP_FK 
  FOREIGN KEY (SOLUTION_ID) 
  REFERENCES SOLUTION(SOLUTION_ID)
);

ALTER TABLE SOLUTION_MAP ADD  
(   
  CONSTRAINT SOLUTION_MAP_MEMBER PRIMARY KEY (SOLUTION_ID,MEMBER_TYPE,MEMBER_ID)
);

ALTER TABLE SOLUTION ADD  (   
  CONSTRAINT SOL_FRIENDLY_ID UNIQUE KEY (ID)  
);

ALTER TABLE value ADD  
(   
  CONSTRAINT value_primary_key PRIMARY KEY (Name(100),Owner_type,owner_id)
);