activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=284,y=28,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=314,ly=100,xs=314&314,ys=71&129
- id: A3
  name: Which?
  implementor: com.centurylink.mdw.tests.code.WhichActivity
  attributes:
    WORK_DISPLAY_INFO: x=284,y=133,w=60,h=40
  transitions:
  - id: T2
    to: A4
    event: FINISH
    resultCode: java
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=155,ly=182,xs=280&101,ys=153&224
  - id: T3
    to: A6
    event: FINISH
    resultCode: java pagelet
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=228,ly=226,xs=314&230,ys=177&314
  - id: T4
    to: A5
    event: FINISH
    resultCode: kotlin
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=461,ly=182,xs=348&567,ys=153&212
  - id: T5
    to: A7
    event: FINISH
    resultCode: kotlin pagelet
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=339,ly=330,xs=329&329&416&416,ys=164&350&350&379
- id: A4
  name: |-
    Java
    Activity
  implementor: com.centurylink.mdw.tests.code.JavaActivity
  attributes:
    WORK_DISPLAY_INFO: x=36,y=204,w=60,h=40
  transitions:
  - id: T7
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=67,ly=283,xs=67&67,ys=248&319
- id: A5
  name: |-
    Kotlin
    Activity
  implementor: com.centurylink.mdw.tests.code.KotlinActivity
  attributes:
    WORK_DISPLAY_INFO: x=572,y=192,w=60,h=40
  transitions:
  - id: T9
    to: A9
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=600,ly=271,xs=600&600,ys=236&306
- id: A6
  name: Java Invader
  implementor: com.centurylink.mdw.tests.code.JavaInvader
  attributes:
    Invader: Dr. Soran
    Planet: Neptune
    WORK_DISPLAY_INFO: x=181,y=318,w=100,h=60
  transitions:
  - id: T6
    to: A8
    event: FINISH
    resultCode: Neptune
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=112,ly=324,xs=176&102,ys=343&343
- id: A7
  name: Kotlin Invader
  implementor: com.centurylink.mdw.tests.code.KotlinInvader
  attributes:
    Invader: Gul Dukat
    Planet: Jupiter
    WORK_DISPLAY_INFO: x=375,y=384,w=100,h=60
  transitions:
  - id: T8
    to: A9
    event: FINISH
    resultCode: Jupiter
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=524,ly=362,xs=479&564,ys=414&330
- id: A8
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=38,y=323,w=60,h=40
- id: A9
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=569,y=310,w=60,h=40
variables:
  invader:
    type: java.lang.String
    category: LOCAL
  testCase:
    type: java.lang.String
    category: INPUT
  updated:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=39,y=79,w=202,h=26
