activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=130,w=60,h=40
  transitions:
  - id: T4
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=180,ly=150,xs=124&236,ys=150&150
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=450,y=130,w=60,h=40
- id: A4
  name: "Custom\r\nCategory Task"
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    WORK_DISPLAY_INFO: x=240,y=120,w=100,h=70
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.code/customCategoryTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=395,ly=150,xs=344&446,ys=150&150
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=36,y=27,w=155,h=27
  PROCESS_VISIBILITY: PUBLIC
