activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=63,y=107,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=150,ly=127,xs=127&173,ys=127&127
- id: A3
  name: Before
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Rule: |-
      runtimeContext.logInfo("Before")
      variables["whereAmI"] = "Before"
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=177,y=104,w=92,h=55
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=297,ly=130,xs=273&322,ys=130&130
- id: A4
  name: Pause
  implementor: com.centurylink.mdw.base.PauseActivity
  attributes:
    WORK_DISPLAY_INFO: x=326,y=111,w=60,h=40
    implementor_assetVersion: '[0.2,1)'
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=417,ly=131,xs=390&444,ys=131&131
- id: A5
  name: After
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    Rule: |-
      runtimeContext.logInfo("After")
      variables["whereAmI"] = "After"
    SCRIPT: Kotlin Script
    WORK_DISPLAY_INFO: x=448,y=107,w=92,h=52
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=576,ly=133,xs=544&608,ys=133&133
- id: A6
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=611,y=113,w=60,h=40
variables:
  whereAmI:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=39,y=37,w=129,h=26
