activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=80,y=110,w=60,h=40
  transitions:
  - id: T3
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=210,ly=130,xs=144&276,ys=130&130
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=520,y=110,w=60,h=40
- id: A4
  name: Await Event
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    SLA_DISPLAY_UNITS: Hours
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["RequestHandlers-${masterRequestId}",""]]'
    WORK_DISPLAY_INFO: x=280,y=100,w=100,h=60
    rcvdMsgDocVar: notifyMessage
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=450,ly=130,xs=384&516,ys=130&130
variables:
  notifyMessage:
    type: org.json.JSONObject
    category: LOCAL
  request:
    type: org.json.JSONObject
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=38,y=35,w=162,h=26
