
DROP TABLE ATTACHMENT;
DROP TABLE INSTANCE_NOTE;
DROP TABLE TASK_INST_INDEX;
DROP TABLE TASK_INST_GRP_MAPP;
DROP TABLE TASK_INSTANCE;

DROP TABLE USER_ROLE_MAPPING;
DROP TABLE USER_GROUP_MAPPING;
DROP TABLE USER_ROLE;
DROP TABLE USER_INFO;
DROP TABLE USER_GROUP;

DROP TABLE EVENT_WAIT_INSTANCE;
DROP TABLE EVENT_INSTANCE;
DROP TABLE EVENT_LOG;

DROP TABLE DOCUMENT_CONTENT;
DROP TABLE DOCUMENT;
DROP TABLE WORK_TRANSITION_INSTANCE;
DROP TABLE VARIABLE_INSTANCE;
DROP TABLE ACTIVITY_INSTANCE;
DROP TABLE PROCESS_INSTANCE;

DROP TABLE SOLUTION_MAP;
DROP TABLE SOLUTION;
DROP TABLE VALUE;

DROP TABLE ATTRIBUTE;