ALTER TABLE DOCUMENT ADD (STATUS_CODE TINYINT, STATUS_MESSAGE VARCHAR(1000));
-- not used when mongodb is present
CREATE TABLE DOCUMENT_CONTENT
(
  DOCUMENT_ID         BIGINT,
  CONTENT             MEDIUMTEXT      NOT NULL  
);
ALTER TABLE DOCUMENT_CONTENT ADD (
  CONSTRAINT DOCCONTENT_DOCUMENT_FK 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES DOCUMENT (DOCUMENT_ID));
CREATE INDEX DOCCONTENT_DOCUMENT_FK ON DOCUMENT_CONTENT
(DOCUMENT_ID);
