<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="CamelEventWait" version="0.1" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=60,y=142,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=462,y=143,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Wait for&#13;&#10;Event from Camel" Implementation="com.centurylink.mdw.workflow.activity.event.EventWaitActivity">
      <bpm:Attribute Name="DESCRIPTION" Value="Notifies by camel Route"/>
      <bpm:Attribute Name="STATUS_AFTER_TIMEOUT" Value="Cancelled"/>
      <bpm:Attribute Name="WAIT_EVENT_NAMES" Value="CamelEvent-{$eventId},FINISH,true,"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=241,y=134,w=107,h=76"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=237,ly=188,type=Elbow,xs=124&amp;237,ys=162&amp;162"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=405,ly=163,type=Elbow,xs=352&amp;458,ys=163&amp;163"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=27,y=30,w=149,h=27"/>
    <bpm:Variables Name="eventId" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Integer"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>