{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=142,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=237,ly=188,type=Elbow,xs=124&237,ys=162&162"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=462,y=143,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DESCRIPTION": "Notifies by camel Route",
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "CamelEvent-{$eventId},FINISH,true,",
        "WORK_DISPLAY_INFO": "x=241,y=134,w=107,h=76"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.event.EventWaitActivity",
      "name": "Wait for\r\nEvent from Camel",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=405,ly=163,type=Elbow,xs=352&458,ys=163&163"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=27,y=30,w=149,h=27"
  },
  "variables": {"eventId": {
    "category": "INPUT",
    "type": "java.lang.Integer"
  }},
  "version": "0.1"
}