<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="MDWTestCamelAdapter" version="0.6" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=77,y=138,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=473,y=140,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Test Camel Route Adapter" Implementation="com.centurylink.mdw.camel.adapter.CamelRouteAdapter">
      <bpm:Attribute Name="PostScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="PreScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="testRequest"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="testResponse"/>
      <bpm:Attribute Name="RouteDefinition" Value="com.centurylink.mdw.tests.camel/StartNNotifyProcessRoute.camel"/>
      <bpm:Attribute Name="RouteDefinition_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=231,y=125,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A4" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=184,ly=158,type=Elbow,xs=141&amp;227,ys=158&amp;158"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=402,ly=160,type=Elbow,xs=335&amp;469,ys=160&amp;160"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=21,y=27,w=212,h=27"/>
    <bpm:Variables Name="testRequest" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="org.w3c.dom.Document"/>
    </bpm:Variables>
    <bpm:Variables Name="testResponse" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>