{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=77,y=138,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=184,ly=158,type=Elbow,xs=141&227,ys=158&158"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=473,y=140,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "REQUEST_VARIABLE": "testRequest",
        "RESPONSE_VARIABLE": "testResponse",
        "RouteDefinition": "com.centurylink.mdw.tests.camel/StartNNotifyProcessRoute.camel",
        "RouteDefinition_assetVersion": "[0.1,1)",
        "WORK_DISPLAY_INFO": "x=231,y=125,w=100,h=60"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.camel.adapter.CamelRouteAdapter",
      "name": "Test Camel Route Adapter",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=402,ly=160,type=Elbow,xs=335&469,ys=160&160"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=21,y=27,w=212,h=27"
  },
  "variables": {
    "testRequest": {
      "category": "INPUT",
      "type": "org.w3c.dom.Document"
    },
    "testResponse": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  },
  "version": "0.6"
}