{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=40,y=33,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=157,ly=54,xs=104&211,ys=54&54"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=612,y=356,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=215,y=32,w=258,h=41"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "One",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=250,ly=94,xs=250&250,ys=77&111"},
          "event": "FINISH",
          "id": "T2",
          "to": "A4"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=341,ly=93,xs=341&341,ys=77&109"},
          "event": "FINISH",
          "id": "T3",
          "to": "A5"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=438,ly=93,xs=438&438,ys=77&109"},
          "event": "FINISH",
          "id": "T4",
          "to": "A6"
        }
      ]
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=220,y=114,w=60,h=40"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Two",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=250,ly=186,xs=250&250,ys=158&214"},
        "event": "FINISH",
        "id": "T5",
        "to": "A7"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=311,y=112,w=60,h=40"},
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Not",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=341,ly=185,xs=341&341,ys=156&214"},
        "event": "FINISH",
        "id": "T6",
        "to": "A7"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=408,y=112,w=60,h=40"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Three",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=438,ly=185,xs=438&438,ys=156&214"},
        "event": "FINISH",
        "id": "T7",
        "to": "A7"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"false\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=219,y=218,w=264,h=52"
      },
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity",
      "name": "Sync",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=340,ly=310,xs=340&340,ys=274&346"},
        "event": "FINISH",
        "id": "T8",
        "to": "A8"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=310,y=351,w=60,h=40"
      },
      "id": "A8",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Four",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=406,ly=371,xs=374&438,ys=371&371"},
        "event": "FINISH",
        "id": "T9",
        "to": "A9"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"false\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=442,y=345,w=100,h=60",
        "processname": "com.centurylink.mdw.tests.milestones/EasySub.proc",
        "processversion": "[0.1,1)",
        "synchronous": "true"
      },
      "id": "A9",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity",
      "name": "EasySub",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=577,ly=375,xs=546&609,ys=375&375"},
        "event": "FINISH",
        "id": "T10",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=57,y=159,w=46,h=26"
  }
}