{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=49,y=102,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=288,ly=122,xs=112&464,ys=122&122"},
        "event": "FINISH",
        "id": "T1",
        "to": "A2"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=469,y=102,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=45,y=31,w=35,h=26"
  }
}