{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=84,y=56,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=185,ly=76,xs=147&224,ys=76&76"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=519,y=183,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=229,y=57,w=60,h=40"},
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "One",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=330,ly=77,xs=292&368,ys=77&77"},
        "event": "FINISH",
        "id": "T2",
        "to": "A4"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=373,y=58,w=60,h=40"},
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Two",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=400,ly=140,xs=400&400,ys=102&179"},
        "event": "FINISH",
        "id": "T4",
        "to": "A5"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=370,y=183,w=60,h=40"},
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Branch",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=473,ly=203,xs=433&514,ys=203&203"},
          "event": "FINISH",
          "id": "T3",
          "resultCode": "Done",
          "to": "A2"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=311,ly=152,xs=365&258,ys=203&101"},
          "event": "FINISH",
          "id": "T5",
          "resultCode": "Back",
          "to": "A3"
        }
      ]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=74,y=134,w=58,h=26"
  }
}