{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=40,y=123,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=148,ly=144,xs=104&192,ys=144&144"},
        "event": "FINISH",
        "id": "T5",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "Monitors": "[[\"true\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=665,y=134,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Output Documents": "[\"executionPlan\"]",
        "Rule": "import com.centurylink.mdw.bpm.ProcessExecutionPlanDocument\nimport com.centurylink.mdw.bpm.ParameterDocument.Parameter\nimport com.centurylink.mdw.bpm.ProcessExecutionPlanDocument.ProcessExecutionPlan\nimport com.centurylink.mdw.bpm.SubprocessInstanceDocument.SubprocessInstance\nimport com.centurylink.mdw.model.workflow.WorkStatus\n\nexecutionPlan = ProcessExecutionPlanDocument.Factory.newInstance()\nProcessExecutionPlan exeplan = executionPlan.addNewProcessExecutionPlan()\n\nSubprocessInstance subprocinst = exeplan.addNewSubprocessInstance()\nsubprocinst.setLogicalProcessName(\"Child\")\nsubprocinst.setStatusCode(WorkStatus.STATUS_PENDING_PROCESS.intValue())\n\nsubprocinst = exeplan.addNewSubprocessInstance()\nsubprocinst.setLogicalProcessName(\"Kid\")\nsubprocinst.setStatusCode(WorkStatus.STATUS_PENDING_PROCESS.intValue())\n\n",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=196,y=122,w=100,h=60"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Create\nPlan",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=350,ly=153,xs=300&400,ys=153&153"},
        "event": "FINISH",
        "id": "T3",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "Execution Plan": "executionPlan",
        "Monitors": "[[\"false\",\"Milestone\",\"com.centurylink.mdw.milestones/ActivityMilestone.java\",\"\"],[\"true\",\"Test Cases\",\"com.centurylink.mdw.testing/TestCaseActivityMonitor.java\",\"\"],[\"true\",\"Zipkin Activity\",\"com.centurylink.mdw.zipkin/TraceActivityMonitor.java\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=404,y=123,w=100,h=60",
        "processmap": "[[\"Child\",\"com.centurylink.mdw.tests.milestones/Child.proc\",\"[0.2,1)\"],[\"Kid\",\"com.centurylink.mdw.tests.milestones/Kid.proc\",\"[0.1,1)\"]]",
        "synchronous": "true"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeHeterogeneousProcessActivity",
      "name": "Invoke\nSubs",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=585,ly=154,xs=508&662,ys=154&154"},
        "event": "FINISH",
        "id": "T4",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "PerformanceLevel": "0",
    "WORK_DISPLAY_INFO": "x=35,y=34,w=149,h=26"
  },
  "variables": {"executionPlan": {
    "category": "LOCAL",
    "type": "org.apache.xmlbeans.XmlObject"
  }}
}