activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=100,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=158,ly=119,xs=124&192,ys=119&119
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=735,y=212,w=60,h=40
- id: A3
  name: |-
    Milestone
    One
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    Rule: runtimeContext.logDebug("Executing " + runtimeContext.activity.name)
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=196,y=89,w=100,h=60
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=245,ly=178,xs=245&245,ys=154&202
- id: A4
  name: |-
    Create
    Plan
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["executionPlan"]'
    Rule: |
      import com.centurylink.mdw.bpm.ProcessExecutionPlanDocument
      import com.centurylink.mdw.bpm.ParameterDocument.Parameter
      import com.centurylink.mdw.bpm.ProcessExecutionPlanDocument.ProcessExecutionPlan
      import com.centurylink.mdw.bpm.SubprocessInstanceDocument.SubprocessInstance
      import com.centurylink.mdw.model.workflow.WorkStatus

      executionPlan = ProcessExecutionPlanDocument.Factory.newInstance()
      ProcessExecutionPlan exeplan = executionPlan.addNewProcessExecutionPlan()

      SubprocessInstance subprocinst = exeplan.addNewSubprocessInstance()
      subprocinst.setLogicalProcessName("SubOne")
      subprocinst.setStatusCode(WorkStatus.STATUS_PENDING_PROCESS.intValue())
      addParameter(subprocinst, "inputVar", "\$subOneInput")

      subprocinst = exeplan.addNewSubprocessInstance()
      subprocinst.setLogicalProcessName("SubTwo")
      subprocinst.setStatusCode(WorkStatus.STATUS_PENDING_PROCESS.intValue())
      addParameter(subprocinst, "inputVar", "\$subTwoInput")

      void addParameter(SubprocessInstance subprocinst, String name, String value) {
          Parameter param = subprocinst.addNewParameter()
          param.setName(name)
          param.setStringValue(value)
      }
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=195,y=205,w=100,h=60
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=349,ly=236,xs=299&399,ys=236&236
- id: A5
  name: |-
    Invoke
    Subs
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeHeterogeneousProcessActivity
  attributes:
    Execution Plan: executionPlan
    Monitors: '[["false","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    STATUS_AFTER_EVENT: Hold
    WORK_DISPLAY_INFO: x=403,y=206,w=100,h=60
    processmap: '[["SubOne","com.centurylink.mdw.tests.milestones/SubOne.proc","[0,1)"],["SubTwo","com.centurylink.mdw.tests.milestones/SubTwo.proc","[0.1,1)"]]'
    synchronous: 'true'
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=545,ly=235,xs=507&584,ys=235&235
- id: A6
  name: Lastly
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=588,y=214,w=60,h=40
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=691,ly=233,xs=652&731,ys=233&233
variables:
  executionPlan:
    type: org.apache.xmlbeans.XmlObject
    category: LOCAL
  subOneInput:
    type: java.lang.String
    category: INPUT
  subTwoInput:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=35,y=34,w=149,h=26
