{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=71,y=87,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "StartB",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=311,ly=108,xs=135&487,ys=108&108"},
        "event": "FINISH",
        "id": "T1",
        "to": "A2"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=491,y=87,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "StopB"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=46,y=37,w=49,h=26"
  }
}