activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=85,y=128,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=168,ly=145,xs=149&188,ys=145&145
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    Monitors: '[["false","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=608,y=124,w=60,h=40
- id: A3
  name: Branch A
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=319,y=63,w=60,h=40
  transitions:
  - id: T5
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=417,ly=113,xs=383&452,ys=83&144
- id: A4
  name: Dummy
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=192,y=123,w=60,h=40
  transitions:
  - id: T2
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=285,ly=113,xs=256&315,ys=143&83
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=284,ly=179,xs=256&313,ys=143&216
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=286,ly=143,xs=256&316,ys=143&143
- id: A5
  name: Branch B
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=318,y=196,w=60,h=40
  transitions:
  - id: T7
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=417,ly=180,xs=382&452,ys=216&144
- id: A6
  name: Branch 0
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=320,y=124,w=60,h=40
  transitions:
  - id: T6
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=418,ly=144,xs=384&452,ys=144&144
- id: A7
  name: sync
  implementor: com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""],["true","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["true","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    WORK_DISPLAY_INFO: x=456,y=120,w=82,h=51
  transitions:
  - id: T8
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=573,ly=144,xs=542&605,ys=144&144
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=46,y=34,w=92,h=26
