activities:
- id: A142
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=304,y=38,w=60,h=40
  transitions:
  - id: T113
    to: A139
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=306,ly=98,type=Elbow,xs=334&334,ys=82&117
- id: A140
  name: NorthSouth Decision Table
  implementor: com.centurylink.mdw.drools.DroolsDecisionTableActivity
  attributes:
    DecisionTableSheet: NorthSouth
    KnowledgeBase: com.centurylink.mdw.tests.rules/drools-multiSheetDecisionTable.xlsx
    KnowledgeBase_assetVersion: '[0.2,1)'
    Rules Language: Drools
    WORK_DISPLAY_INFO: x=418,y=200,w=100,h=60
  transitions:
  - id: T111
    to: A138
    event: FINISH
    resultCode: NORTHERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=433,ly=313,type=Elbow,xs=433&433,ys=264&363
  - id: T112
    to: A141
    event: FINISH
    resultCode: SOUTHERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=515,ly=313,type=Elbow,xs=515&515,ys=264&363
- id: A138
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=389,y=367,w=60,h=40
- id: A141
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=513,y=367,w=60,h=40
- id: A143
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=95,y=370,w=60,h=40
- id: A144
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=229,y=370,w=60,h=40
- id: A137
  name: EastWest DecisionTable
  implementor: com.centurylink.mdw.drools.DroolsDecisionTableActivity
  attributes:
    DecisionTableSheet: EastWest
    KnowledgeBase: com.centurylink.mdw.tests.rules/drools-multiSheetDecisionTable.xlsx
    KnowledgeBase_assetVersion: '[0.2,1)'
    Rules Language: Drools
    WORK_DISPLAY_INFO: x=143,y=202,w=100,h=60
  transitions:
  - id: T109
    to: A143
    event: FINISH
    resultCode: WESTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=149,ly=315,type=Elbow,xs=149&149,ys=266&366
  - id: T110
    to: A144
    event: FINISH
    resultCode: EASTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=236,ly=315,type=Elbow,xs=236&236,ys=266&366
- id: A139
  name: Geography
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: geography
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=298,y=121,w=82,h=59
  transitions:
  - id: T107
    to: A137
    event: FINISH
    resultCode: EastWest
    attributes:
      TRANSITION_DISPLAY_INFO: lx=276,ly=199,type=Elbow,xs=294&247,ys=150&232
  - id: T108
    to: A140
    event: FINISH
    resultCode: NorthSouth
    attributes:
      TRANSITION_DISPLAY_INFO: lx=404,ly=149,type=Elbow,xs=384&414,ys=150&230
variables:
  geography:
    type: java.lang.String
    category: INPUT
  quotedPrice:
    type: java.lang.String
    category: INPUT
  region:
    type: java.lang.String
    category: INPUT
  workgroup:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  START_TRANSITION_ID: '2345034'
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=23,y=77,w=276,h=27
