activities:
- id: A2
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    Parameters: '{"orderNumber":"${request.orderNumber}","dueDate":"${request.dueDate}","region":"${request.regionString}","quotedPrice":"${request.quotedPrice}"}'
    WORK_DISPLAY_INFO: x=183,y=47,w=60,h=40
  transitions:
  - id: T2
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=200,ly=78,type=Elbow,xs=213&213,ys=91&138
- id: A3
  name: Setup XMLBean
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    OsgiBundleSymbolicName: com.centurylink.donsfuse
    Output Documents: xmlBeanVar
    Rule: "import com.centurylink.mdw.service.ApplicationSummaryDocument \r\nimport com.centurylink.mdw.service.ApplicationSummaryDocument.ApplicationSummary     \r\n\r\nxmlBeanVar = ApplicationSummaryDocument.Factory.newInstance();  \r\nApplicationSummary appSummary = xmlBeanVar.addNewApplicationSummary(); \r\nappSummary.setMdwVersion('6.1');"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=163,y=142,w=100,h=60
  transitions:
  - id: T4
    to: A1
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=217,ly=232,type=Elbow,xs=217&217,ys=206&258
- id: A1
  name: "Drools \r\nDecision Table"
  implementor: com.centurylink.mdw.drools.DroolsDecisionTableActivity
  attributes:
    KnowledgeBase: com.centurylink.mdw.tests.rules/drools-orderRoutingDecisionTable.xlsx
    KnowledgeBase_assetVersion: '[0.2,1)'
    Logging: 'true'
    Output Documents: xmlBeanVar
    RuleVersionVar: ruleVersion
    Rules Language: Drools
    Stateful: 'FALSE'
    WORK_DISPLAY_INFO: x=172,y=262,w=105,h=72
  transitions:
  - id: T5
    to: A7
    event: FINISH
    resultCode: WESTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=270,ly=392,type=Elbow,xs=223&223&371&371,ys=338&385&385&435
  - id: T6
    to: A7
    event: FINISH
    resultCode: EASTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=329,ly=277,type=Elbow,xs=281&395,ys=298&435
- id: A5
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=523,y=446,w=60,h=40
- id: A7
  name: Set Response
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["response"]'
    Rule: |-
      response = new org.json.JSONObject()
      response.put('workgroup', workgroup)
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=345,y=439,w=100,h=60
  transitions:
  - id: T7
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=484,ly=466,type=Elbow,xs=449&519,ys=466&466
variables:
  dueDate:
    type: java.util.Date
    category: INPUT
  orderNumber:
    type: java.lang.String
    category: INPUT
  quotedPrice:
    type: java.lang.Integer
    category: INPUT
  region:
    type: java.lang.String
    category: INPUT
  request:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
  requestHeaders:
    type: java.util.Map<String,String>
    category: INPUT
  response:
    type: org.json.JSONObject
    category: OUTPUT
  ruleVersion:
    type: java.lang.String
    category: LOCAL
  workgroup:
    type: java.lang.String
    category: LOCAL
  xmlBeanVar:
    type: org.apache.xmlbeans.XmlObject
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: SERVICE
  START_TRANSITION_ID: '2345108'
  WORK_DISPLAY_INFO: x=356,y=87,w=196,h=26
  requestMethod: POST
  requestParameters: '[["Order","Body","true","Order for Rules","com.centurylink.mdw.tests.rules/Order.java","[0.1,1)"]]'
  requestPath: /order
  requestSummary: Order for Rules testing
