activities:
- id: A3
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=221,y=36,w=60,h=40
  transitions:
  - id: T1
    to: A1
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=227,ly=95,type=Elbow,xs=251&251,ys=80&119
- id: A1
  name: "Apply Order \r\nRouting"
  implementor: com.centurylink.mdw.drools.DroolsActivity
  attributes:
    Facts: dueDate#region
    KnowledgeBase: com.centurylink.mdw.tests.rules/drools-orderRoutingDrool.drl
    KnowledgeBase_assetVersion: '[0.2,1)'
    Logging: 'TRUE'
    Rules Language: Drools
    Stateful: 'FALSE'
    WORK_DISPLAY_INFO: x=202,y=123,w=100,h=69
    assetVersion: '[0.6,1)'
  transitions:
  - id: T2
    to: A4
    event: FINISH
    resultCode: WESTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=93,ly=232,type=Elbow,xs=198&82,ys=157&292
  - id: T3
    to: A2
    event: FINISH
    resultCode: EASTERN
    attributes:
      TRANSITION_DISPLAY_INFO: lx=369,ly=234,type=Elbow,xs=306&435,ys=157&291
- id: A4
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=52,y=296,w=60,h=40
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=405,y=295,w=60,h=40
variables:
  billedPrice:
    type: java.lang.Integer
    category: LOCAL
  dueDate:
    type: java.util.Date
    category: INPUT
  orderNumber:
    type: java.lang.String
    category: INPUT
  quotedPrice:
    type: java.lang.Integer
    category: INPUT
  region:
    type: java.lang.String
    category: INPUT
  workgroup:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  START_TRANSITION_ID: '2344974'
  WORK_DISPLAY_INFO: x=39,y=33,w=128,h=27
textNotes:
- id: N5
  content: 'TODO: Custom attributes for VCS Assets'
  attributes:
    WORK_DISPLAY_INFO: x=316,y=123,w=309,h=22
