activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=38,y=107,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=122,ly=127,xs=103&142,ys=127&127
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=766,y=111,w=60,h=40
- id: A3
  name: |-
    Custom
    Activity
  implementor: com.centurylink.mdw.tests.workflow.LoggingActivity
  attributes:
    WORK_DISPLAY_INFO: x=145,y=96,w=104,h=68
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=278,ly=130,xs=254&302,ys=130&130
- id: A4
  name: Dynamic Java
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: ActivityLogging_A4
    Java: "package com.centurylink.mdw.tests.workflow;\n\nimport java.util.Map;\n\nimport com.centurylink.mdw.java.JavaExecutionException;\nimport com.centurylink.mdw.java.JavaExecutor;\nimport com.centurylink.mdw.java.MdwJavaException;\nimport com.centurylink.mdw.model.workflow.ActivityRuntimeContext;\n\npublic class ActivityLogging_A4 implements JavaExecutor {\n    private ActivityRuntimeContext context;\n\n    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {\n        this.context = context;\n    }\n\n    public Object execute(Map<String,Object> variables) throws JavaExecutionException  {\n        // context\n        context.logInfo(\"context.logInfo()\");\n        context.logDebug(\"context.logDebug()\");\n        context.logError(\"context.logError()\", new Exception(\"context.logError()\"));\n        \n        return null;\n    }\n}\n"
    WORK_DISPLAY_INFO: x=305,y=97,w=103,h=66
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=433,ly=129,xs=412&454,ys=129&129
- id: A5
  name: Groovy
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    WORK_DISPLAY_INFO: x=458,y=98,w=104,h=62
    SCRIPT: Groovy
    Rule: |
      runtimeContext.logInfo("context.logInfo()");
      runtimeContext.logDebug("context.logDebug()");
      runtimeContext.logError("context.logError()", new Exception("context.logError()"));
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=586,ly=130,xs=566&606,ys=130&130
- id: A6
  name: Kotlin
  implementor: com.centurylink.mdw.kotlin.ScriptActivity
  attributes:
    WORK_DISPLAY_INFO: x=611,y=101,w=100,h=60
    SCRIPT: Kotlin Script
    Rule: |
      runtimeContext.logInfo("context.logInfo()");
      runtimeContext.logDebug("context.logDebug()");
      runtimeContext.logError("context.logError()", Exception("context.logError()"));
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=738,ly=131,xs=714&762,ys=131&131
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=31,y=28,w=149,h=26
  PROCESS_VISIBILITY: PUBLIC
