activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=260,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=157,ly=294,type=Elbow,xs=124&149,ys=280&280
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=461,y=118,w=60,h=40
- id: A3
  name: Which Case?
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: processCase
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=153,y=245,w=98,h=68
  transitions:
  - id: T2
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=202,ly=217,type=Elbow,xs=202&202,ys=241&175
  - id: T3
    to: A6
    event: FINISH
    resultCode: error handler delegation
    attributes:
      TRANSITION_DISPLAY_INFO: lx=258,ly=291,type=Elbow,xs=255&399,ys=281&281
- id: A5
  name: Script with syntax Error
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: "$xmldata.MINUTES = \"2\";\r\n\r\n$intarraytest = \"1~1~2~3~5~8\";\r\n\r\n$maptest = \"R=red~G=green~B=blue\";\r\n\r\nsyntax error here"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=136,y=112,w=133,h=59
  transitions:
  - id: T4
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=342,ly=138,type=Elbow,xs=273&457,ys=138&138
- id: A6
  name: Invoke Subprocess with Error
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=403,y=249,w=176,h=65
    processname: com.centurylink.mdw.tests.workflow/TestSubProcess2.proc
    processversion: '[0,1)'
    synchronous: 'TRUE'
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=491,ly=197,type=Elbow,xs=491&491,ys=245&162
subprocesses:
- id: P9
  name: Exception Handler
  activities:
  - id: A7
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=557,y=60,w=60,h=40
    transitions:
    - id: T6
      to: A11
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=652,ly=80,type=Elbow,xs=621&684,ys=80&80
  - id: A10
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=857,y=60,w=60,h=40
  - id: A11
    name: ActivityException Fallout
    implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
    attributes:
      STATUS_AFTER_EVENT: Cancelled
      TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
      TASK_TEMPLATE: com.centurylink.mdw.tests.workflow/activityExceptionFallout.task
      TASK_TEMPLATE_assetVersion: '[0.2,1)'
      WORK_DISPLAY_INFO: x=688,y=51,w=100,h=60
      Wait for Task: 'TRUE'
    transitions:
    - id: T7
      to: A10
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=822,ly=80,type=Elbow,xs=792&853,ys=80&80
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=544,y=20,w=386,h=116
variables:
  exception:
    type: java.lang.Exception
    category: LOCAL
  processCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=50,y=50,w=159,h=27
