<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="ActivityException" version="0.2" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=60,y=260,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=461,y=118,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Which Case?" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptEvaluator">
      <bpm:Attribute Name="Expression" Value="processCase"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=153,y=245,w=98,h=68"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Script with syntax Error" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="$xmldata.MINUTES = &quot;2&quot;;&#13;&#10;&#13;&#10;$intarraytest = &quot;1~1~2~3~5~8&quot;;&#13;&#10;&#13;&#10;$maptest = &quot;R=red~G=green~B=blue&quot;;&#13;&#10;&#13;&#10;syntax error here"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=136,y=112,w=133,h=59"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Invoke Subprocess with Error" Implementation="com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity">
      <bpm:Attribute Name="processname" Value="com.centurylink.mdw.tests.workflow/MDWTestSubProcess2"/>
      <bpm:Attribute Name="processversion" Value="[0.4,1)"/>
      <bpm:Attribute Name="synchronous" Value="TRUE"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=403,y=249,w=176,h=65"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=157,ly=294,type=Elbow,xs=124&amp;149,ys=280&amp;280"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A5" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=202,ly=217,type=Elbow,xs=202&amp;202,ys=241&amp;175"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="error handler delegation" From="A3" To="A6" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=258,ly=291,type=Elbow,xs=255&amp;399,ys=281&amp;281"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A5" To="A2" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=342,ly=138,type=Elbow,xs=273&amp;457,ys=138&amp;138"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A6" To="A2" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=491,ly=197,type=Elbow,xs=491&amp;491,ys=245&amp;162"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=50,y=50,w=159,h=27"/>
    <bpm:Variables Name="exception" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.Object"/>
    </bpm:Variables>
    <bpm:Variables Name="processCase" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
    <bpm:SubProcess Id="P9" name="Exception Handler" version="0" description="">
      <bpm:Activity Id="A7" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
        <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=557,y=60,w=60,h=40"/>
      </bpm:Activity>
      <bpm:Activity Id="A10" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
        <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
        <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=857,y=60,w=60,h=40"/>
      </bpm:Activity>
      <bpm:Activity Id="A11" Name="ActivityException Fallout" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
        <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
        <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/AutoFormManualTask.pagelet"/>
        <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.workflow/activityExceptionFallout.task"/>
        <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.2,1)"/>
        <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=688,y=51,w=100,h=60"/>
        <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
      </bpm:Activity>
      <bpm:Transition CompletionCode="" From="A7" To="A11" Event="FINISH" Id="T6">
        <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=652,ly=80,type=Elbow,xs=621&amp;684,ys=80&amp;80"/>
      </bpm:Transition>
      <bpm:Transition CompletionCode="" From="A11" To="A10" Event="FINISH" Id="T7">
        <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=822,ly=80,type=Elbow,xs=792&amp;853,ys=80&amp;80"/>
      </bpm:Transition>
      <bpm:Attribute Name="PROCESS_VISIBILITY" Value="EMBEDDED"/>
      <bpm:Attribute Name="EMBEDDED_PROCESS_TYPE" Value="Exception Handler"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=544,y=20,w=386,h=116"/>
    </bpm:SubProcess>
  </bpm:Process>
</bpm:processDefinition>