{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=260,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=219,ly=232,type=Elbow,xs=124&244,ys=280&280"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=480,y=260,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "import com.centurylink.mdw.config.PropertyManager\r\n\r\nprintln 'one: ' + PropertyManager.getProperty(\"one.prop\")\r\nprintln 'two: ' + runtimeContext.getProperty(\"two.prop\")\r\n\r\nprintln 'three.flat: ' + PropertyManager.getProperty(\"three.flat.config\")\r\nprintln 'three.structured: ' + runtimeContext.getProperty(\"three.structured.config\")\r\n",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=248,y=249,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Log Props",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=414,ly=280,type=Elbow,xs=352&476,ys=280&280"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "Documentation": "Scenario:\r\n\r\n1. In mdw.yaml, the following appears under `application`:\r\n```yaml\r\napplication:\r\n  name: my-mdw\r\n  configs:\r\n    - one.properties\r\n    - two.properties\r\n    - three.yaml\r\n``` \r\n\r\n2. The following files exist in the location pointed to by -Dmdw.config.location.  \r\n**one.properties**\r\n```\r\none.prop=oneValue\r\n```\r\n**two.properties**\r\n```\r\ntwo.prop=twoValue\r\n```\r\n**three.yaml**\r\n```yaml\r\nflat.config: threeFlatValue\r\nstructured:\r\n  config: threeStructuredValue\r\n```\r\n\r\n3. The `Log Props` activity produces this output:\r\n```\r\none: oneValue\r\ntwo: twoValue\r\nthree.flat: threeFlatValue\r\nthree.structured: threeStructuredValue\r\n``` ",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=46,y=56,w=96,h=27"
  }
}