activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=58,y=161,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=181,ly=181,xs=122&240,ys=181&181
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=505,y=163,w=60,h=40
- id: A3
  name: Retrieve App User
  implementor: com.centurylink.mdw.workflow.adapter.rest.RestServiceAdapter
  attributes:
    EndpointUri: ${props['mdw.services.url']}/api/Users/${appUser}
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    PreScript: runtimeContext.logDebug("Executing " + runtimeContext.getActivity().getName())
    RESPONSE_VARIABLE: appUserResponse
    WORK_DISPLAY_INFO: x=244,y=160,w=129,h=62
    HttpMethod: GET
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=439,ly=183,xs=377&501,ys=183&183
variables:
  appUser:
    type: java.lang.String
    category: INPUT
  appUserResponse:
    type: org.json.JSONObject
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=50,y=50,w=0,h=0
  PROCESS_VISIBILITY: PUBLIC
