activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=86,y=115,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=225,ly=137,xs=150&300,ys=137&137
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=506,y=115,w=60,h=40
- id: A3
  name: |-
    Do
    Logging
  implementor: com.centurylink.mdw.tests.workflow.BadLogger
  attributes:
    WORK_DISPLAY_INFO: x=304,y=120,w=119,h=66
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=464,ly=137,xs=427&502,ys=137&137
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=41,y=37,w=142,h=26
