activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=33,y=127,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=97,ly=70,type=Elbow,xs=97&153,ys=147&147
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=507,y=127,w=60,h=40
- id: A4
  name: jsonToJson
  implementor: com.centurylink.mdw.workflow.activity.transform.CrossmapActivity
  attributes:
    Input: jsonInput
    Mapper: com.centurylink.mdw.tests.workflow/jsonToJson.groovy
    Mapper_assetVersion: '[0.1,1)'
    Output: jsonToJsonOutput
    WORK_DISPLAY_INFO: x=157,y=118,w=100,h=60
  transitions:
  - id: T2
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=299,ly=167,type=Elbow,xs=261&317,ys=148&148
- id: A5
  name: jsonToXml
  implementor: com.centurylink.mdw.workflow.activity.transform.CrossmapActivity
  attributes:
    Input: jsonInput
    Mapper: com.centurylink.mdw.tests.workflow/jsonToXml.groovy
    Mapper_assetVersion: '[0.1,1)'
    Output: jsonToXmlOutput
    WORK_DISPLAY_INFO: x=321,y=118,w=100,h=60
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=464,ly=147,type=Elbow,xs=425&503,ys=147&147
variables:
  jsonInput:
    type: org.json.JSONObject
    category: INPUT
  jsonToJsonOutput:
    type: org.json.JSONObject
    category: LOCAL
  jsonToXmlOutput:
    type: org.w3c.dom.Document
    category: LOCAL
  xmlInput:
    type: org.w3c.dom.Document
    category: INPUT
  xmlToJsonOutput:
    type: org.json.JSONObject
    category: LOCAL
  xmlToXmlOutput:
    type: org.w3c.dom.Document
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=45,y=38,w=131,h=27
textNotes:
- id: N6
  content: 'TODO: Add tests for jsonToXml and xmlToXml'
  attributes:
    WORK_DISPLAY_INFO: x=215,y=30,w=341,h=22
