{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=304,y=38,w=60,h=40"},
      "id": "A142",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=306,ly=98,type=Elbow,xs=334&334,ys=82&117"},
        "event": "FINISH",
        "id": "T113",
        "to": "A139"
      }]
    },
    {
      "attributes": {
        "DecisionTableSheet": "NorthSouth",
        "KnowledgeBase": "com.centurylink.mdw.tests.workflow/drools-multiSheetDecisionTable.xlsx",
        "KnowledgeBase_assetVersion": "[0.1,1)",
        "Rules Language": "Drools",
        "WORK_DISPLAY_INFO": "x=418,y=200,w=100,h=60"
      },
      "id": "A140",
      "implementor": "com.centurylink.mdw.drools.DroolsDecisionTableActivity",
      "name": "NorthSouth Decision Table",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=433,ly=313,type=Elbow,xs=433&433,ys=264&363"},
          "event": "FINISH",
          "id": "T111",
          "resultCode": "NORTHERN",
          "to": "A138"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=515,ly=313,type=Elbow,xs=515&515,ys=264&363"},
          "event": "FINISH",
          "id": "T112",
          "resultCode": "SOUTHERN",
          "to": "A141"
        }
      ]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=389,y=367,w=60,h=40"},
      "id": "A138",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=513,y=367,w=60,h=40"},
      "id": "A141",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=95,y=370,w=60,h=40"},
      "id": "A143",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=229,y=370,w=60,h=40"},
      "id": "A144",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DecisionTableSheet": "EastWest",
        "KnowledgeBase": "com.centurylink.mdw.tests.workflow/drools-multiSheetDecisionTable.xlsx",
        "KnowledgeBase_assetVersion": "[0.1,1)",
        "Rules Language": "Drools",
        "WORK_DISPLAY_INFO": "x=144,y=203,w=100,h=60"
      },
      "id": "A137",
      "implementor": "com.centurylink.mdw.drools.DroolsDecisionTableActivity",
      "name": "EastWest DecisionTable",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=149,ly=316,type=Elbow,xs=149&149,ys=267&366"},
          "event": "FINISH",
          "id": "T109",
          "resultCode": "WESTERN",
          "to": "A143"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=236,ly=316,type=Elbow,xs=236&236,ys=267&366"},
          "event": "FINISH",
          "id": "T110",
          "resultCode": "EASTERN",
          "to": "A144"
        }
      ]
    },
    {
      "attributes": {
        "Expression": "geography",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=298,y=121,w=82,h=59"
      },
      "id": "A139",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Geography",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=277,ly=200,type=Elbow,xs=294&248,ys=150&233"},
          "event": "FINISH",
          "id": "T107",
          "resultCode": "EastWest",
          "to": "A137"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=404,ly=149,type=Elbow,xs=384&414,ys=150&230"},
          "event": "FINISH",
          "id": "T108",
          "resultCode": "NorthSouth",
          "to": "A140"
        }
      ]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "SLA": "20",
    "SLA_UNIT": "Minutes",
    "START_TRANSITION_ID": "2345034",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=23,y=77,w=276,h=27"
  },
  "variables": {
    "geography": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "quotedPrice": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "region": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "workgroup": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  }
}