{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=147,y=28,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=164,ly=59,type=Elbow,xs=177&177,ys=72&119"},
        "event": "FINISH",
        "id": "T2",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "OsgiBundleSymbolicName": "com.centurylink.donsfuse",
        "Output Documents": "xmlBeanVar",
        "Rule": "import com.centurylink.mdw.service.ApplicationSummaryDocument \r\nimport com.centurylink.mdw.service.ApplicationSummaryDocument.ApplicationSummary     \r\n\r\nxmlBeanVar = ApplicationSummaryDocument.Factory.newInstance();  \r\nApplicationSummary appSummary = xmlBeanVar.addNewApplicationSummary(); \r\nappSummary.setMdwVersion('5.5');",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=130,y=123,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Setup XMLBean",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=181,ly=202,type=Elbow,xs=181&181,ys=187&218"},
        "event": "FINISH",
        "id": "T4",
        "to": "A1"
      }]
    },
    {
      "attributes": {
        "KnowledgeBase": "com.centurylink.mdw.tests.workflow/drools-orderRoutingDecisionTable.xlsx",
        "KnowledgeBase_assetVersion": "[0.1,1)",
        "Logging": "true",
        "Output Documents": "xmlBeanVar",
        "RuleVersionVar": "ruleVersion",
        "Rules Language": "Drools",
        "Stateful": "FALSE",
        "WORK_DISPLAY_INFO": "x=133,y=222,w=105,h=72"
      },
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.rules.DroolsDecisionTableActivity",
      "name": "Drools \r\nDecision Table",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=67,ly=297,type=Elbow,xs=129&57,ys=258&344"},
          "event": "FINISH",
          "id": "T1",
          "resultCode": "WESTERN",
          "to": "A4"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=263,ly=296,type=Elbow,xs=242&325,ys=258&353"},
          "event": "FINISH",
          "id": "T3",
          "resultCode": "EASTERN",
          "to": "A5"
        }
      ]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=295,y=357,w=60,h=40"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=27,y=348,w=60,h=40"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2345108",
    "WORK_DISPLAY_INFO": "x=294,y=87,w=185,h=27"
  },
  "variables": {
    "dueDate": {
      "category": "INPUT",
      "type": "java.util.Date"
    },
    "orderNumber": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "quotedPrice": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "region": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "ruleVersion": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "workgroup": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "xmlBeanVar": {
      "category": "LOCAL",
      "type": "org.apache.xmlbeans.XmlObject"
    }
  },
  "version": "0.2"
}