activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=119,y=74,w=32,h=32
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=93,ly=197,type=Elbow,xs=136&136,ys=110&217
- id: A2
  name: Force Error
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: bad script
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=124,y=221,w=24,h=24
  transitions:
  - id: T4
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=136,ly=304,type=Elbow,xs=136&136,ys=249&362
- id: A3
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=121,y=366,w=32,h=32
subprocesses:
- id: SubProcess1
  name: Exception Handler
  activities:
  - id: A5
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=333,y=63,w=32,h=32
    transitions:
    - id: T1
      to: A4
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=422,ly=75,type=Elbow,xs=369&474,ys=75&75
  - id: A6
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      WORK_DISPLAY_INFO: x=633,y=63,w=32,h=32
  - id: A4
    name: Subprocess From Embedded
    implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
    attributes:
      WORK_DISPLAY_INFO: x=478,y=65,w=20,h=20
      processname: SubprocessForEmbedded
      processversion: '[0.4,1)'
      synchronous: 'TRUE'
      variables: fromParent=$passToSub;toParent=$receiveFromSub
    transitions:
    - id: T2
      to: A6
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=565,ly=75,type=Elbow,xs=502&629,ys=75&75
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    ENTRY_TRANSITION_ID: '2328556'
    PROCESS_VISIBILITY: EMBEDDED
    START_TRANSITION_ID: '2328549'
    WORK_DISPLAY_INFO: x=293,y=23,w=395,h=110
variables:
  passToSub:
    type: java.lang.String
    category: INPUT
  receiveFromSub:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  ERROR_TRANSITION_ID: '84481'
  NodeStyle: Icon
  PROCESS_VISIBILITY: PUBLIC
  START_TRANSITION_ID: '2328555'
  WORK_DISPLAY_INFO: x=23,y=20,w=242,h=27
