{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=71,y=132,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=204,ly=137,type=Elbow,xs=135&226,ys=152&152"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=496,y=133,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "MICROSERVICE_NAMES": "true,mic1,${serviceSummary != null},",
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "servicesummary-update-{$MasterRequestID},,false,",
        "WORK_DISPLAY_INFO": "x=230,y=114,w=150,h=78"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.microservice.DependenciesWaitActivity",
      "name": "Microservice\r\nDependencies Wait",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=439,ly=153,type=Elbow,xs=384&492,ys=153&153"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "SERVICE",
    "WORK_DISPLAY_INFO": "x=40,y=42,w=278,h=26"
  },
  "variables": {"serviceSummary": {
    "category": "INPUT",
    "type": "com.centurylink.mdw.model.Jsonable"
  }}
}