{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=42,y=120,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=177,ly=106,type=Elbow,xs=106&153,ys=140&140"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=504,y=123,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Event Name": "servicesummary-update-{$MasterRequestID}",
        "WORK_DISPLAY_INFO": "x=330,y=109,w=103,h=69"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.microservice.ServiceSummaryEventPublish",
      "name": "Publish\r\nEvent",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=468,ly=143,type=Elbow,xs=437&500,ys=143&143"},
        "event": "FINISH",
        "id": "T3",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Rule": "Thread.sleep(20000)",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=157,y=112,w=111,h=65"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Sleep a Few\r\nSeconds",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=289,ly=149,type=Elbow,xs=272&326,ys=144&144"},
        "event": "FINISH",
        "id": "T2",
        "to": "A3"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=39,y=38,w=268,h=27"
  }
}