activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=21,y=306,w=60,h=40
  transitions:
  - id: T23
    to: A23
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=135,ly=325,type=Elbow,xs=85&174,ys=326&326
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=353,y=320,w=60,h=40
- id: A23
  name: "Event Check \nActivity"
  implementor: com.centurylink.mdw.workflow.activity.event.EventCheckActivity
  attributes:
    WAIT_EVENT_NAMES: C-{$MasterRequestID},Cancelled::ABORT,false,;M-{$MasterRequestID},FINISH,false,;S-{$MasterRequestID},Completed::CORRECT,false,;H-{$MasterRequestID},Hold::CORRECT,true,
    WORK_DISPLAY_INFO: x=178,y=298,w=117,h=75
    rcvdMsgDocVar: response
  transitions:
  - id: T24
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=324,ly=340,type=Elbow,xs=299&349,ys=340&340
subprocesses:
- id: P6
  name: Correction Handler
  activities:
  - id: A7
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=266,y=139,w=60,h=40
    transitions:
    - id: T27
      to: A8
      event: FINISH
      attributes:
        TRANSITION_DELAY: 5s
        TRANSITION_DISPLAY_INFO: lx=446,ly=159,type=Elbow,xs=330&562,ys=159&159
  - id: A8
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=566,y=139,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Correction Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=226,y=99,w=440,h=120
- id: P13
  name: Cancellation Handler
  activities:
  - id: A14
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=733,y=141,w=60,h=40
    transitions:
    - id: T28
      to: A15
      event: FINISH
      attributes:
        TRANSITION_DELAY: 10s
        TRANSITION_DISPLAY_INFO: lx=913,ly=161,type=Elbow,xs=797&1029,ys=161&161
  - id: A15
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=1033,y=141,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Cancellation Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=693,y=101,w=440,h=120
- id: P24
  name: Exception Handler
  activities:
  - id: A25
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=471,y=425,w=60,h=40
    transitions:
    - id: T29
      to: A27
      event: FINISH
      attributes:
        TRANSITION_DELAY: 10s
        TRANSITION_DISPLAY_INFO: lx=651,ly=445,type=Elbow,xs=535&767,ys=445&445
  - id: A27
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=771,y=425,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=431,y=385,w=440,h=120
variables:
  CustomerAccountId:
    type: java.lang.String
    category: LOCAL
  request:
    type: org.w3c.dom.Document
    category: LOCAL
  response:
    type: org.w3c.dom.Document
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=50,y=50,w=110,h=27
