activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=46,y=123,w=60,h=40
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=161,ly=143,type=Elbow,xs=110&212,ys=143&143
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=489,y=121,w=60,h=40
- id: A3
  name: "Microservice \r\nDependencies Wait"
  implementor: com.centurylink.mdw.microservice.DependenciesWaitActivity
  attributes:
    MICROSERVICE_NAMES: true,mic2,${serviceSummary != null},
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: servicesummary-update-{$MasterRequestID},,false,
    WORK_DISPLAY_INFO: x=216,y=107,w=157,h=82
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=377,ly=170,type=Elbow,xs=377&485,ys=141&141
variables:
  serviceSummary:
    type: com.centurylink.mdw.model.Jsonable
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=25,y=36,w=278,h=26
