{
  "activities": [
    {
      "attributes": {
        "Parameters": "customerId=${request['donsOrder/customerId']};orderNumber=${request['donsOrder/orderNumber']}",
        "WORK_DISPLAY_INFO": "x=75,y=197,w=60,h=40"
      },
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=304,ly=217,type=Elbow,xs=139&469,ys=217&217"},
        "event": "FINISH",
        "id": "T1",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=473,y=198,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=205,h=27"
  },
  "variables": {
    "customerId": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "orderNumber": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "request": {
      "category": "INPUT",
      "type": "org.apache.xmlbeans.XmlObject"
    }
  },
  "version": "0.1"
}