activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=31,y=158,w=60,h=40
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=124,ly=178,type=Elbow,xs=95&154,ys=178&178
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=763,y=157,w=60,h=40
- id: A3
  name: Wait
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    STATUS_AFTER_TIMEOUT: Cancelled
    WAIT_EVENT_NAMES: '[["{$MasterRequestID}",""]]'
    WORK_DISPLAY_INFO: x=298,y=147,w=100,h=60
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=425,ly=164,type=Elbow,xs=402&448,ys=178&178
- id: A4
  name: Set newVar
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: newVar = 'hello I am newVar'
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=452,y=150,w=100,h=60
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=586,ly=179,type=Elbow,xs=556&603,ys=179&179
- id: A5
  name: Set oldVar
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    Java: "package com.centurylink.mdw.tests.workflow;\r\n\r\nimport java.util.Map;\r\n\r\nimport com.centurylink.mdw.java.JavaExecutionException;\r\nimport com.centurylink.mdw.java.JavaExecutor;\r\nimport com.centurylink.mdw.java.MdwJavaException;\r\nimport com.centurylink.mdw.model.workflow.ActivityRuntimeContext;\r\n\r\npublic class SetoldVar_A5 implements JavaExecutor {\r\n\r\n    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {\r\n    }\r\n\r\n    public Object execute(Map<String,Object> variables) throws JavaExecutionException {\r\n        variables.put(\"oldVar\", \"from InflightAfter\");\r\n        return null;\r\n    }\r\n\r\n}\r\n"
    WORK_DISPLAY_INFO: x=607,y=149,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=736,ly=177,type=Elbow,xs=711&759,ys=177&177
- id: A6
  name: Dummy
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=158,y=153,w=75,h=50
  transitions:
  - id: T5
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=265,ly=178,type=Elbow,xs=237&294,ys=178&178
variables:
  newVar:
    type: java.lang.String
    category: LOCAL
  oldVar:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=41,y=49,w=107,h=27
textNotes:
- id: N7
  content: Only in v0.2
  attributes:
    WORK_DISPLAY_INFO: x=144,y=219,w=101,h=22
