{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=31,y=158,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=124,ly=178,type=Elbow,xs=95&154,ys=178&178"},
        "event": "FINISH",
        "id": "T4",
        "to": "A6"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=763,y=157,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "[[\"{$MasterRequestID}\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=298,y=147,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.event.EventWaitActivity",
      "name": "Wait",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=425,ly=164,type=Elbow,xs=402&448,ys=178&178"},
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "Rule": "newVar = 'hello I am newVar'",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=452,y=150,w=100,h=60"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Set newVar",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=586,ly=179,type=Elbow,xs=556&603,ys=179&179"},
        "event": "FINISH",
        "id": "T3",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "Java": "package com.centurylink.mdw.tests.workflow;\r\n\r\nimport java.util.Map;\r\n\r\nimport com.centurylink.mdw.java.JavaExecutionException;\r\nimport com.centurylink.mdw.java.JavaExecutor;\r\nimport com.centurylink.mdw.java.MdwJavaException;\r\nimport com.centurylink.mdw.model.workflow.ActivityRuntimeContext;\r\n\r\npublic class SetoldVar_A5 implements JavaExecutor {\r\n\r\n    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {\r\n    }\r\n\r\n    public Object execute(Map<String,Object> variables) throws JavaExecutionException {\r\n        variables.put(\"oldVar\", \"from InflightAfter\");\r\n        return null;\r\n    }\r\n\r\n}\r\n",
        "WORK_DISPLAY_INFO": "x=607,y=149,w=100,h=60"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity",
      "name": "Set oldVar",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=736,ly=177,type=Elbow,xs=711&759,ys=177&177"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=158,y=153,w=75,h=50"},
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Dummy",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=265,ly=178,type=Elbow,xs=237&294,ys=178&178"},
        "event": "FINISH",
        "id": "T5",
        "to": "A3"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=41,y=49,w=107,h=27"
  },
  "textNotes": [{
    "attributes": {"WORK_DISPLAY_INFO": "x=144,y=219,w=101,h=22"},
    "content": "Only in v0.2",
    "id": "N7"
  }],
  "variables": {
    "newVar": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "oldVar": {
      "category": "INPUT",
      "type": "java.lang.String"
    }
  }
}