{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=41,y=163,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=146,ly=183,type=Elbow,xs=105&185,ys=183&183"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=605,y=164,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "STATUS_AFTER_TIMEOUT": "Cancelled",
        "WAIT_EVENT_NAMES": "[[\"{$MasterRequestID}\",\"\"]]",
        "WORK_DISPLAY_INFO": "x=189,y=152,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.event.EventWaitActivity",
      "name": "Wait",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=337,ly=182,type=Elbow,xs=293&381,ys=182&182"},
        "event": "FINISH",
        "id": "T2",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "Java": "package com.centurylink.mdw.tests.workflow;\r\n\r\nimport java.util.Map;\r\n\r\nimport com.centurylink.mdw.java.JavaExecutionException;\r\nimport com.centurylink.mdw.java.JavaExecutor;\r\nimport com.centurylink.mdw.java.MdwJavaException;\r\nimport com.centurylink.mdw.model.workflow.ActivityRuntimeContext;\r\n\r\npublic class SetoldVar_A5 implements JavaExecutor {\r\n\r\n    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {\r\n    }\r\n\r\n    public Object execute(Map<String,Object> variables) throws JavaExecutionException {\r\n        variables.put(\"oldVar\", \"from InflightBefore\");\r\n        return null;\r\n    }\r\n\r\n}\r\n",
        "WORK_DISPLAY_INFO": "x=385,y=153,w=100,h=60"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity",
      "name": "Set oldVar",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=545,ly=184,type=Elbow,xs=489&601,ys=184&184"},
        "event": "FINISH",
        "id": "T3",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=46,y=51,w=123,h=27"
  },
  "variables": {
    "newVar": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "oldVar": {
      "category": "INPUT",
      "type": "java.lang.String"
    }
  }
}