{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=208,y=44,w=60,h=40"},
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=86,ly=40,type=Elbow,xs=204&91,ys=64&186"},
          "event": "FINISH",
          "id": "T2",
          "to": "A1"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=303,ly=81,type=Elbow,xs=272&350,ys=64&64"},
          "event": "FINISH",
          "id": "T3",
          "to": "A6"
        }
      ]
    },
    {
      "attributes": {
        "AppCuid": "prop:LDAP/AppCUID",
        "AppPassword": "prop:LDAP/AppPassword",
        "BaseDn": "prop:LDAP/BaseDN",
        "Bindings": "matchingCuids=uid;matchingMnetIds=mnetid;unmatchedMultiple=unmatched;matchingHomePhones=homephone",
        "LdapHost": "prop:LDAP/Host",
        "LdapPort": "prop:LDAP/Port",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "SearchContext": "ou=People",
        "SearchFilter": "(sn=${lastNameInput})",
        "WORK_DISPLAY_INFO": "x=233,y=199,w=116,h=67"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter",
      "name": "LDAP Adapter\r\nMultiple Results",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=301,ly=277,type=Elbow,xs=301&301,ys=270&296"},
        "event": "FINISH",
        "id": "T7",
        "to": "A7"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=274,y=390,w=60,h=40"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "AppCuid": "prop:LDAP/AppCUID",
        "AppPassword": "prop:LDAP/AppPassword",
        "BaseDn": "prop:LDAP/BaseDN",
        "Bindings": "department=departmentname;emailAddress=mail;firstName=givenname;lastName=sn;mnetId=mnetid;phoneNumber=telephonenumber;rcCode=rc;state=st;unmatchedSingle=unmatched;sapId=saploginid",
        "LdapHost": "prop:LDAP/Host",
        "LdapPort": "prop:LDAP/Port",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "SearchContext": "ou=People",
        "SearchFilter": "(uid=${cuid})",
        "WORK_DISPLAY_INFO": "x=36,y=190,w=110,h=69"
      },
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter",
      "name": "LDAP Adapter\r\nSingle Result",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=199,ly=278,type=Elbow,xs=150&250,ys=224&330"},
        "event": "FINISH",
        "id": "T6",
        "to": "A7"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "10",
        "Unit": "Seconds",
        "WORK_DISPLAY_INFO": "x=354,y=41,w=100,h=60"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Wait 10s",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=348,ly=144,type=Elbow,xs=404&291,ys=105&195"},
          "event": "FINISH",
          "id": "T5",
          "to": "A3"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=488,ly=72,type=Elbow,xs=458&517,ys=72&72"},
          "event": "FINISH",
          "id": "T8",
          "to": "A8"
        }
      ]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "Synced Activities": "LDAP Adapter\r\nSingle Result#LDAP Adapter\r\nMultiple Results#LDAP Adapter\r\nDocument Binding",
        "WORK_DISPLAY_INFO": "x=254,y=300,w=100,h=60"
      },
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity",
      "name": "Sync",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=304,ly=359,type=Elbow,xs=304&304,ys=364&386"},
        "event": "FINISH",
        "id": "T1",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "10",
        "Unit": "Seconds",
        "WORK_DISPLAY_INFO": "x=521,y=44,w=106,h=67"
      },
      "id": "A8",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "10 More\r\nSeconds",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=575,ly=138,type=Elbow,xs=575&575,ys=115&162"},
        "event": "FINISH",
        "id": "T9",
        "to": "A9"
      }]
    },
    {
      "attributes": {
        "AppCuid": "prop:LDAP/AppCUID",
        "AppPassword": "prop:LDAP/AppPassword",
        "BaseDn": "prop:LDAP/BaseDN",
        "Bindings": "userDocument=results",
        "LdapHost": "prop:LDAP/Host",
        "LdapPort": "prop:LDAP/Port",
        "OsgiBundleSymbolicName": "com.centurylink.donsservicemix",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "SearchContext": "ou=People",
        "SearchFilter": "(saploginid=${sapIdInput})",
        "WORK_DISPLAY_INFO": "x=523,y=166,w=113,h=69"
      },
      "id": "A9",
      "implementor": "com.centurylink.mdw.workflow.adapter.ldap.LdapAdapter",
      "name": "LDAP Adapter\r\nDocument Binding",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=426,ly=249,type=Elbow,xs=519&358,ys=200&330"},
        "event": "FINISH",
        "id": "T10",
        "to": "A7"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2358799",
    "WORK_DISPLAY_INFO": "x=20,y=13,w=116,h=27"
  },
  "variables": {
    "cuid": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "department": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "emailAddress": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "firstName": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "lastName": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "lastNameInput": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "matchingCuids": {
      "category": "LOCAL",
      "type": "java.util.List<String>"
    },
    "matchingHomePhones": {
      "category": "LOCAL",
      "type": "java.util.List<String>"
    },
    "matchingMnetIds": {
      "category": "LOCAL",
      "type": "java.util.List<Integer>"
    },
    "mnetId": {
      "category": "LOCAL",
      "type": "java.lang.Integer"
    },
    "phoneNumber": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "rcCode": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "sapId": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "sapIdInput": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "state": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "unmatchedMultiple": {
      "category": "LOCAL",
      "type": "java.util.List<String>"
    },
    "unmatchedSingle": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "userDocument": {
      "category": "LOCAL",
      "type": "org.apache.xmlbeans.XmlObject"
    }
  },
  "version": "0.2"
}