<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="MDWServiceLevel_9" version="0.1" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=56,y=261,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=561,y=125,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Invoke regular Async Subprocess" Implementation="com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=323,y=115,w=183,h=59"/>
      <bpm:Attribute Name="processname" Value="com.centurylink.mdw.tests.workflow/RpcWebService"/>
      <bpm:Attribute Name="processversion" Value="[0.4,1)"/>
      <bpm:Attribute Name="synchronous" Value="FALSE"/>
      <bpm:Attribute Name="variables" Value="requestDoc=${myvar}"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Set document" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Output Documents" Value="myvar"/>
      <bpm:Attribute Name="Rule" Value="myvar=&quot;Some special variable value in here!&quot;;"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=168,y=117,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Which Test Case?" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptEvaluator">
      <bpm:Attribute Name="Expression" Value="processCase"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=157,y=250,w=122,h=61"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A5" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=126,ly=281,type=Elbow,xs=120&amp;153,ys=281&amp;281"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=540,ly=144,type=Elbow,xs=510&amp;557,ys=145&amp;145"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A3" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=306,ly=148,type=Elbow,xs=272&amp;319,ys=145&amp;145"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="DocumentBinding" From="A5" To="A4" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=118,ly=207,type=Elbow,xs=218&amp;218,ys=246&amp;181"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="SERVICE"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=50,y=50,w=185,h=27"/>
    <bpm:Attribute Name="PerformanceLevel" Value="9"/>
    <bpm:Variables Name="myvar" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.StringDocument"/>
    </bpm:Variables>
    <bpm:Variables Name="processCase" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>