activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=56,y=261,w=60,h=40
  transitions:
  - id: T1
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=126,ly=281,type=Elbow,xs=120&153,ys=281&281
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=561,y=125,w=60,h=40
- id: A3
  name: Invoke regular Async Subprocess
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=323,y=115,w=183,h=59
    processname: com.centurylink.mdw.tests.workflow/SmartProcessChild
    processversion: '[2.3,3)'
    synchronous: 'FALSE'
    variables: '{"inputVar":"#{myvar}"}'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=540,ly=144,type=Elbow,xs=510&557,ys=145&145
- id: A4
  name: Set document
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: myvar
    Rule: myvar="Some special variable value in here!";
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=168,y=117,w=100,h=60
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=306,ly=148,type=Elbow,xs=272&319,ys=145&145
- id: A5
  name: Which Test Case?
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: processCase
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=157,y=250,w=122,h=61
  transitions:
  - id: T4
    to: A4
    event: FINISH
    resultCode: DocumentBinding
    attributes:
      TRANSITION_DISPLAY_INFO: lx=118,ly=207,type=Elbow,xs=218&218,ys=246&181
variables:
  myvar:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
  processCase:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: SERVICE
  PerformanceLevel: '9'
  SLA: '20'
  SLA_UNIT: Minutes
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=50,y=50,w=185,h=27
