{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=53,y=119,w=60,h=40"},
      "id": "A34",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=158,ly=138,type=Elbow,xs=117&199,ys=139&139"},
        "event": "FINISH",
        "id": "T27",
        "to": "A31"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=625,y=117,w=60,h=40"
      },
      "id": "A33",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Finish"
    },
    {
      "attributes": {
        "Rule": "ncube = n * n * n;   ",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=203,y=111,w=100,h=60"
      },
      "id": "A31",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Calculate cube",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=360,ly=142,type=Elbow,xs=307&412,ys=142&142"},
        "event": "FINISH",
        "id": "T28",
        "to": "A35"
      }]
    },
    {
      "attributes": {
        "Output Documents": "resultdoc",
        "Rule": "import groovy.xml.MarkupBuilder;\r\n\r\ndef stringWriter = new StringWriter();\r\ndef docBuilder = new MarkupBuilder(stringWriter);\r\ndocBuilder.Result {\r\n\t\tn(n)\r\n\t\tnplus1(n+1)\r\n\t\tcube(ncube)\r\n\t\r\n}\r\nresultdoc = stringWriter.toString();",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=416,y=113,w=100,h=60"
      },
      "id": "A35",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "create output\r\ndocument",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=571,ly=137,type=Elbow,xs=520&621,ys=137&137"},
        "event": "FINISH",
        "id": "T29",
        "to": "A33"
      }]
    }
  ],
  "attributes": {
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "SLA": "20",
    "SLA_UNIT": "Minutes",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=41,y=30,w=202,h=27"
  },
  "variables": {
    "n": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "ncube": {
      "category": "OUTPUT",
      "type": "java.lang.Long"
    },
    "resultdoc": {
      "category": "OUTPUT",
      "type": "com.centurylink.mdw.model.StringDocument"
    }
  },
  "version": "0.6"
}