{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=53,y=119,w=60,h=40"},
      "id": "A34",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=158,ly=138,type=Elbow,xs=117&199,ys=139&139"},
        "event": "FINISH",
        "id": "T27",
        "to": "A31"
      }]
    },
    {
      "attributes": {
        "Rule": "document resultdoc;\n\n& $resultdoc = \"Result\";\n$resultdoc.n = $n;\n$resultdoc.nplus1 = $n + 1;\n$resultdoc.cube = $ncube;",
        "SCRIPT": "MagicBox",
        "WORK_DISPLAY_INFO": "x=393,y=100,w=102,h=71"
      },
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "create output\ndocument",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=568,ly=137,type=Elbow,xs=499&621,ys=137&137"},
        "event": "FINISH",
        "id": "T2",
        "to": "A33"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=625,y=117,w=60,h=40"
      },
      "id": "A33",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Finish"
    },
    {
      "attributes": {
        "Rule": "ncube = n * n * n;   ",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=203,y=111,w=100,h=60"
      },
      "id": "A31",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Calculate cube",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=421,ly=127,type=Elbow,xs=307&389,ys=141&141"},
        "event": "FINISH",
        "id": "T1",
        "to": "A1"
      }]
    }
  ],
  "attributes": {
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=41,y=30,w=202,h=27"
  },
  "variables": {
    "n": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "ncube": {
      "category": "OUTPUT",
      "type": "java.lang.Long"
    },
    "resultdoc": {
      "category": "OUTPUT",
      "type": "org.w3c.dom.Document"
    }
  },
  "version": "0.5"
}