{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=83,y=77,w=60,h=40"},
      "id": "A34",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=219,ly=96,type=Elbow,xs=147&266,ys=97&97"},
        "event": "FINISH",
        "id": "T27",
        "to": "A31"
      }]
    },
    {
      "attributes": {
        "Rule": "result = argument * argument;   ",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=270,y=70,w=100,h=60"
      },
      "id": "A31",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Calculate sqaure",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=454,ly=98,type=Elbow,xs=374&533,ys=98&98"},
        "event": "FINISH",
        "id": "T1",
        "to": "A33"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=537,y=78,w=60,h=40"
      },
      "id": "A33",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Finish"
    }
  ],
  "attributes": {
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "SLA": "20",
    "SLA_UNIT": "Minutes",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=34,y=24,w=202,h=27"
  },
  "variables": {
    "argument": {
      "category": "INOUT",
      "type": "java.lang.Integer"
    },
    "newvar": {
      "category": "INOUT",
      "type": "java.lang.Boolean"
    },
    "result": {
      "category": "OUTPUT",
      "type": "java.lang.Long"
    },
    "testxml": {
      "category": "INPUT",
      "type": "org.w3c.dom.Document"
    }
  },
  "version": "0.5"
}