{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=260,w=60,h=40"},
      "id": "A43",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=146,ly=280,type=Elbow,xs=124&167,ys=280&280"},
        "event": "FINISH",
        "id": "T38",
        "to": "A42"
      }]
    },
    {
      "attributes": {
        "Expression": "testCase",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=171,y=260,w=60,h=40"
      },
      "id": "A42",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "which case?",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=268,ly=115,type=ElbowH,xs=231&290&290&416,ys=280&280&49&49",
            "TRANSITION_RETRY_COUNT": "0"
          },
          "event": "FINISH",
          "id": "T34",
          "resultCode": "cancel",
          "to": "A48"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=327,ly=280,type=Elbow,xs=235&412,ys=280&280"},
          "event": "FINISH",
          "id": "T36",
          "resultCode": "wait",
          "to": "A49"
        },
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=260,ly=369,type=ElbowH,xs=231&292&292&413,ys=280&280&422&422",
            "TRANSITION_RETRY_COUNT": "0"
          },
          "event": "FINISH",
          "id": "T40",
          "resultCode": "hold",
          "to": "A45"
        },
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=130,ly=328,type=Elbow,xs=201&201,ys=304&361",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T46",
          "resultCode": "methodExpression",
          "to": "A51"
        }
      ]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=741,y=263,w=60,h=40"},
      "id": "A46",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Waiting",
        "TIMER_WAIT": "2",
        "Unit": "Minutes",
        "WAIT_EVENT_NAMES": "NonTaskAction-{$MasterRequestID},other,true",
        "WORK_DISPLAY_INFO": "x=416,y=247,w=100,h=60"
      },
      "id": "A49",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Timer and Event\nWait - wait",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=632,ly=283,type=Elbow,xs=520&737,ys=283&283"},
          "event": "FINISH",
          "id": "T37",
          "to": "A46"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=486,ly=220,type=Elbow,xs=466&466,ys=243&210"},
          "event": "FINISH",
          "id": "T43",
          "resultCode": "other",
          "to": "A44"
        }
      ]
    },
    {
      "attributes": {
        "$+Id": "69569",
        "TIMER_WAIT": "1",
        "Unit": "Minutes",
        "WORK_DISPLAY_INFO": "x=415,y=502,w=100,h=60"
      },
      "id": "A47",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "wait for 1 min",
      "transitions": [{
        "attributes": {
          "TRANSITION_DELAY": "0",
          "TRANSITION_DISPLAY_INFO": "lx=502,ly=375,type=ElbowH,xs=519&565&565&521,ys=530&530&433&433",
          "TRANSITION_RETRY_COUNT": "0"
        },
        "event": "FINISH",
        "id": "T42",
        "to": "A45"
      }]
    },
    {
      "attributes": {
        "TIMER_WAIT": "1",
        "Unit": "Minutes",
        "WORK_DISPLAY_INFO": "x=417,y=146,w=100,h=60"
      },
      "id": "A44",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "wait for 1min"
    },
    {
      "attributes": {
        "TIMER_WAIT": "60",
        "Unit": "Seconds",
        "WORK_DISPLAY_INFO": "x=733,y=26,w=100,h=60"
      },
      "id": "A50",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "wait for 60s",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=771,ly=174,type=Elbow,xs=771&771,ys=90&259"},
        "event": "FINISH",
        "id": "T45",
        "to": "A46"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Hold",
        "TIMER_WAIT": "2",
        "Unit": "Minutes",
        "WAIT_EVENT_NAMES": "NonTaskAction-{$MasterRequestID},other,true",
        "WORK_DISPLAY_INFO": "x=417,y=387,w=100,h=60"
      },
      "id": "A45",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Timer and Event\nWait - hold",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=633,ly=353,type=Elbow,xs=521&737,ys=417&283"},
          "event": "FINISH",
          "id": "T39",
          "to": "A46"
        },
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=467,ly=476,type=Elbow,xs=466&466,ys=451&498",
            "TRANSITION_RETRY_COUNT": "0"
          },
          "event": "FINISH",
          "id": "T41",
          "resultCode": "other",
          "to": "A47"
        }
      ]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "2",
        "Unit": "Minutes",
        "WAIT_EVENT_NAMES": "NonTaskAction-{$MasterRequestID},other,true",
        "WORK_DISPLAY_INFO": "x=420,y=24,w=100,h=60"
      },
      "id": "A48",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Timer and Event\nWait - cancel",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=623,ly=163,type=Elbow,xs=524&737,ys=54&283"},
          "event": "FINISH",
          "id": "T35",
          "to": "A46"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=655,ly=28,type=Elbow,xs=524&729,ys=55&55"},
          "event": "FINISH",
          "id": "T44",
          "resultCode": "other",
          "to": "A50"
        }
      ]
    },
    {
      "attributes": {
        "Output Documents": "timerBean",
        "Rule": "import com.centurylink.mdw.tests.workflow.TimerBean\r\n\r\n// this value gets reduced in TimerBean.getTimerDelaySeconds\r\ntimerBean = new TimerBean()\r\ntimerBean.setTimerDelaySeconds(120)",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=144,y=365,w=104,h=78"
      },
      "id": "A51",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Create\r\nTimerBean",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=196,ly=461,type=Elbow,xs=196&196,ys=447&487",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T47",
        "to": "A52"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "#{timerBean.timerDelaySeconds}",
        "Unit": "Seconds",
        "WAIT_EVENT_NAMES": "fireAfterSixty-#{masterRequestId},not,true,",
        "WORK_DISPLAY_INFO": "x=141,y=491,w=117,h=68"
      },
      "id": "A52",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Wait via\r\nMethod Expr",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=198,ly=584,type=Elbow,xs=198&198,ys=563&606",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T49",
          "to": "A53"
        },
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=272,ly=505,type=Elbow,xs=262&302,ys=526&526",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T50",
          "resultCode": "Not",
          "to": "A55"
        }
      ]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=168,y=610,w=60,h=40"
      },
      "id": "A53",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=306,y=506,w=60,h=40"
      },
      "id": "A55",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Done"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2327820",
    "TRANSITION_RETRY_COUNT": "-1",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=31,y=23,w=176,h=27"
  },
  "variables": {
    "testCase": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "timerBean": {
      "category": "LOCAL",
      "type": "java.lang.Object"
    }
  }
}