<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="MDWTestSubProcess" version="1.7" description="">
    <bpm:Activity Id="Activity34" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=55,y=100,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity32" Name="Wait for a while" Implementation="com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TIMER_WAIT" Value="( [exist $testxml] $testxml.MINUTES ; [$argument>3] 1; $argument )"/>
      <bpm:Attribute Name="Unit" Value="Minutes"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=384,y=94,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity33" Name="Finish" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=558,y=102,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity31" Name="Calculate sqaure" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="result = argument * argument;   "/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=195,y=93,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="Activity32" To="Activity33" Event="FINISH" Id="Transition26">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=523,ly=121,type=Elbow,xs=488&amp;554,ys=122&amp;122"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="Activity34" To="Activity31" Event="FINISH" Id="Transition27">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=157,ly=119,type=Elbow,xs=119&amp;191,ys=120&amp;120"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="Activity31" To="Activity32" Event="FINISH" Id="Transition28">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=340,ly=123,type=Elbow,xs=299&amp;380,ys=123&amp;123"/>
    </bpm:Transition>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="SLA" Value="0"/>
    <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=31,y=23,w=192,h=27"/>
    <bpm:Attribute Name="START_TRANSITION_ID" Value="2326941"/>
    <bpm:Variables Name="argument" ReferredAs="" Category="INOUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Integer"/>
    </bpm:Variables>
    <bpm:Variables Name="newvar" ReferredAs="" Category="INOUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Boolean"/>
    </bpm:Variables>
    <bpm:Variables Name="result" ReferredAs="" Category="OUTPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Long"/>
    </bpm:Variables>
    <bpm:Variables Name="testxml" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="org.w3c.dom.Document"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>