<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="MDWTestSubProcess2" version="0.5" description="">
    <bpm:Activity Id="Activity30" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=21,y=179,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity27" Name="Not executed" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=448,y=287,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity28" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=705,y=156,w=60,h=40"/>
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity26" Name="Throw an Exception" Implementation="com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity">
      <bpm:Attribute Name="Java" Value="/**&#10; * Copyright (c) 2016 CenturyLink, Inc. All Rights Reserved.&#10; */&#10;&#10;package com.centurylink.mdw.tests.workflow;&#10;&#10;import java.util.Map;&#10;&#10;import com.centurylink.mdw.java.JavaExecutionException;&#10;import com.centurylink.mdw.java.JavaExecutor;&#10;import com.centurylink.mdw.java.MdwJavaException;&#10;import com.centurylink.mdw.model.value.activity.ActivityRuntimeContext;&#10;&#10;/**&#10; * Dynamic Java to force an error.&#10; */&#10;public class ThrowanException_Activity26 implements JavaExecutor {&#10;&#10;    public void initialize(ActivityRuntimeContext context) throws MdwJavaException {&#10;    }&#10;&#10;    public Object execute(Map&lt;String, Object> variables) throws JavaExecutionException {&#10;        throw new RuntimeException(&quot;Help me, I'm an error&quot;);&#10;    }&#10;&#10;}&#10;"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=166,y=176,w=132,h=69"/>
    </bpm:Activity>
    <bpm:Activity Id="Activity29" Name="Alternate path" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="runtimeContext.logInfo(&quot;In alternate path&quot;);"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=448,y=24,w=100,h=60"/>
      <bpm:Attribute Name="OsgiBundleSymbolicName" Value="com.centurylink.mdw.workflow"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="AltAction" From="Activity26" To="Activity29" Event="RESUME" Id="Transition20">
      <bpm:Attribute Name="TRANSITION_DELAY" Value="0"/>
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=373,ly=126,type=Elbow,xs=302&amp;444,ys=210&amp;54"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="0"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="Activity29" To="Activity28" Event="FINISH" Id="Transition21">
      <bpm:Attribute Name="TRANSITION_DELAY" Value="0"/>
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=605,ly=126,type=Elbow,xs=552&amp;701,ys=54&amp;176"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="0"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="no" From="Activity26" To="Activity27" Event="FINISH" Id="Transition22">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=380,ly=265,type=Elbow,xs=302&amp;444,ys=210&amp;317"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="Activity27" To="Activity28" Event="FINISH" Id="Transition23">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=633,ly=242,type=Elbow,xs=552&amp;701,ys=317&amp;176"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="Activity30" To="Activity26" Event="FINISH" Id="Transition24">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=124,ly=256,type=Elbow,xs=85&amp;162,ys=199&amp;199"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="yes" From="Activity26" To="Activity28" Event="FINISH" Id="Transition25">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=508,ly=186,type=ElbowV,xs=302&amp;701,ys=186&amp;186"/>
    </bpm:Transition>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="SLA" Value="0"/>
    <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
    <bpm:Attribute Name="Transition with no Label" Value="Acts as Default"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=43,y=29,w=202,h=27"/>
    <bpm:Attribute Name="START_TRANSITION_ID" Value="2326876"/>
  </bpm:Process>
</bpm:processDefinition>