activities:
- id: A34
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=53,y=119,w=60,h=40
  transitions:
  - id: T27
    to: A31
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=158,ly=138,type=Elbow,xs=117&199,ys=139&139
- id: A33
  name: Finish
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=625,y=117,w=60,h=40
- id: A31
  name: Calculate cube
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: 'ncube = n * n * n;   '
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=203,y=111,w=100,h=60
  transitions:
  - id: T28
    to: A35
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=360,ly=142,type=Elbow,xs=307&412,ys=142&142
- id: A35
  name: "create output\r\ndocument"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: resultdoc
    Rule: "import groovy.xml.MarkupBuilder;\r\n\r\ndef stringWriter = new StringWriter();\r\ndef docBuilder = new MarkupBuilder(stringWriter);\r\ndocBuilder.Result {\r\n\t\tn(n)\r\n\t\tnplus1(n+1)\r\n\t\tcube(ncube)\r\n\t\r\n}\r\nresultdoc = stringWriter.toString();"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=416,y=113,w=100,h=60
  transitions:
  - id: T29
    to: A33
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=571,ly=137,type=Elbow,xs=520&621,ys=137&137
variables:
  n:
    type: java.lang.Integer
    category: INPUT
  ncube:
    type: java.lang.Long
    category: OUTPUT
  resultdoc:
    type: com.centurylink.mdw.model.StringDocument
    category: OUTPUT
attributes:
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=41,y=30,w=202,h=27
