{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=157,y=90,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=160,ly=149,type=Elbow,xs=187&187,ys=134&209"},
        "event": "FINISH",
        "id": "T3",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=158,y=336,w=60,h=40"},
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=396,y=218,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "localString = inputString + \" added string\";\r\nlocalInt = inputInt + 8;\r\nif (inputString != null)\r\n  \"OutcomeY\";",
        "SCRIPT": "JavaScript",
        "WORK_DISPLAY_INFO": "x=137,y=213,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "JavaScript Activity",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=188,ly=302,type=Elbow,xs=188&188,ys=277&332"},
          "event": "FINISH",
          "id": "T1",
          "to": "A4"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=317,ly=238,type=Elbow,xs=241&392,ys=238&238"},
          "event": "FINISH",
          "id": "T2",
          "resultCode": "OutcomeY",
          "to": "A2"
        }
      ]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2330344",
    "WORK_DISPLAY_INFO": "x=29,y=25,w=179,h=27"
  },
  "variables": {
    "bystander": {
      "category": "LOCAL",
      "type": "org.json.JSONObject"
    },
    "innocent": {
      "category": "LOCAL",
      "type": "org.w3c.dom.Document"
    },
    "inputInt": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "inputString": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "localInt": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "localString": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  },
  "version": "0.3"
}