activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=260,w=60,h=40
  transitions:
  - id: T1
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=150,ly=280,xs=124&177,ys=280&280
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=361,y=258,w=60,h=40
- id: A5
  name: |-
    Event Wait Activity
    with timeout
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    SLA: '60'
    SLA_UNITS: Minutes
    STATUS_AFTER_TIMEOUT: Hold
    WORK_DISPLAY_INFO: x=181,y=248,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=321,ly=278,xs=285&357,ys=278&278
subprocesses:
- id: P1
  name: Delay Handler
  activities:
  - id: A6
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=373,y=86,w=60,h=40
    transitions:
    - id: T3
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: type=Elbow,lx=553,ly=106,xs=437&669,ys=106&106
  - id: A7
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      TerminationAction: Complete Process
      WORK_DISPLAY_INFO: x=673,y=86,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Delay Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=333,y=46,w=440,h=120
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=50,y=50,w=0,h=0
