{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=85,y=70,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=187,ly=90,type=Elbow,xs=149&224,ys=90&90"},
        "event": "FINISH",
        "id": "T7",
        "to": "A7"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=559,y=78,w=60,h=40"},
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DO_LOGGING": "True",
        "EndpointUri": "http://localhost:7001/Services",
        "HttpMethod": "POST",
        "REQUEST_VARIABLE": "requestDoc",
        "RESPONSE_VARIABLE": "responseDoc",
        "WORK_DISPLAY_INFO": "x=228,y=398,w=100,h=60"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter",
      "name": "Sim Mode",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=361,ly=415,type=ElbowH,xs=332&391,ys=415&415"},
        "event": "FINISH",
        "id": "T2",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=567,y=300,w=60,h=40"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=395,y=392,w=60,h=40"},
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "ConnectTimeout": "60000",
        "DO_LOGGING": "True",
        "EndpointUri": "#{props['mdw.services.url']}/Services",
        "HeadersVariable": "headersMap",
        "HttpMethod": "POST",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "REQUEST_VARIABLE": "requestDoc",
        "RESPONSE_VARIABLE": "responseDoc",
        "ReadTimeout": "60000",
        "WORK_DISPLAY_INFO": "x=313,y=294,w=108,h=71"
      },
      "id": "A9",
      "implementor": "com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter",
      "name": "RESTful\r\nAction Request",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DELAY": "30s",
            "TRANSITION_DISPLAY_INFO": "lx=326,ly=292,type=Curve,xs=367&382,ys=329&266",
            "TRANSITION_RETRY_COUNT": "3"
          },
          "event": "ERROR",
          "id": "T9",
          "resultCode": "RETRY",
          "to": "A9"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=517,ly=318,type=Elbow,xs=425&563,ys=320&320"},
          "event": "FINISH",
          "id": "T12",
          "to": "A5"
        }
      ]
    },
    {
      "attributes": {
        "DO_LOGGING": "True",
        "EndpointUri": "#{props['mdw.services.url']}/services/AppSummary",
        "HeadersVariable": "headersMap",
        "HttpMethod": "GET",
        "RESPONSE_VARIABLE": "responseDoc",
        "WORK_DISPLAY_INFO": "x=386,y=78,w=116,h=77"
      },
      "id": "A8",
      "implementor": "com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter",
      "name": "RESTful\r\nResource Request",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=531,ly=102,type=Elbow,xs=506&555,ys=98&98"},
        "event": "FINISH",
        "id": "T3",
        "to": "A6"
      }]
    },
    {
      "attributes": {
        "OsgiBundleSymbolicName": "com.centurylink.donsservicemix",
        "Output Documents": "requestDoc",
        "RETURN_CODE": "httpMethod",
        "Rule": "System.out.println(\"HTTP Method: \" + httpMethod);\r\n\r\nif (httpMethod.equals(\"POST\") || httpMethod.equals(\"SIM\"))\r\n{\r\n  requestDoc = '''<tns:GetEmployee xmlns:tns=\"http://mdw.centurylink.com/serviceTypes\">\r\n  <tns:workstationId>dxoakes<\/tns:workstationId>\r\n<\/tns:GetEmployee>''';\r\n\r\n}\r\n\r\nreturn httpMethod\r\n",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=228,y=70,w=100,h=60"
      },
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Request Type",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=278,ly=258,type=ElbowH,xs=278&278,ys=134&394"},
          "event": "FINISH",
          "id": "T1",
          "resultCode": "SIM",
          "to": "A2"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=357,ly=104,type=Elbow,xs=332&382,ys=104&104"},
          "event": "FINISH",
          "id": "T5",
          "resultCode": "GET",
          "to": "A8"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=317,ly=202,type=ElbowH,xs=320&320,ys=134&290"},
          "event": "FINISH",
          "id": "T6",
          "resultCode": "POST",
          "to": "A9"
        }
      ]
    }
  ],
  "attributes": {
    "NodeStyle": "BoxIcon",
    "SLA": "20",
    "SLA_UNIT": "Minutes",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=11,y=13,w=202,h=27"
  },
  "variables": {
    "headersMap": {
      "category": "LOCAL",
      "type": "java.util.Map"
    },
    "httpMethod": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "requestDoc": {
      "category": "LOCAL",
      "type": "org.apache.xmlbeans.XmlObject"
    },
    "responseDoc": {
      "category": "LOCAL",
      "type": "com.centurylink.mdw.model.StringDocument"
    }
  },
  "version": "0.21"
}