<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="RestfulServiceAdapter" version="0.18" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=85,y=70,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=559,y=78,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Sim Mode" Implementation="com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter">
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="EndpointUri" Value="http://localhost:7001/Services"/>
      <bpm:Attribute Name="HttpMethod" Value="POST"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="requestDoc"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="responseDoc"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=228,y=398,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=567,y=300,w=60,h=40"/>
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=395,y=392,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A9" Name="RESTful&#13;&#10;Action Request" Implementation="com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter">
      <bpm:Attribute Name="ConnectTimeout" Value="60000"/>
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="EndpointUri" Value="#{props['mdw.services.url']}/Services"/>
      <bpm:Attribute Name="HeadersVariable" Value="headersMap"/>
      <bpm:Attribute Name="HttpMethod" Value="POST"/>
      <bpm:Attribute Name="PostScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="PreScriptLang" Value="Groovy"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="requestDoc"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="responseDoc"/>
      <bpm:Attribute Name="ReadTimeout" Value="60000"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=313,y=294,w=108,h=71"/>
    </bpm:Activity>
    <bpm:Activity Id="A8" Name="RESTful&#13;&#10;Resource Request" Implementation="com.centurylink.mdw.workflow.adapter.rest.RestfulServiceAdapter">
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="EndpointUri" Value="#{props['mdw.services.url']}/resources/com.centurylink.mdw.base/copyright.txt"/>
      <bpm:Attribute Name="HeadersVariable" Value="headersMap"/>
      <bpm:Attribute Name="HttpMethod" Value="GET"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="responseDoc"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=386,y=78,w=116,h=77"/>
    </bpm:Activity>
    <bpm:Activity Id="A7" Name="Request Type" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="OsgiBundleSymbolicName" Value="com.centurylink.donsservicemix"/>
      <bpm:Attribute Name="Output Documents" Value="requestDoc"/>
      <bpm:Attribute Name="RETURN_CODE" Value="httpMethod"/>
      <bpm:Attribute Name="Rule" Value="System.out.println(&quot;HTTP Method: &quot; + httpMethod);&#13;&#10;&#13;&#10;if (httpMethod.equals(&quot;POST&quot;) || httpMethod.equals(&quot;SIM&quot;))&#13;&#10;{&#13;&#10;  requestDoc = '''&lt;tns:GetEmployee xmlns:tns=&quot;http://mdw-servicemix.centurylink.com/serviceTypes&quot;>&#13;&#10;  &lt;tns:workstationId>dxoakes&lt;/tns:workstationId>&#13;&#10;&lt;/tns:GetEmployee>''';&#13;&#10; &#13;&#10;}&#13;&#10;  "/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="SLA" Value="0"/>
      <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=228,y=70,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="SIM" From="A7" To="A2" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=278,ly=258,type=ElbowH,xs=278&amp;278,ys=134&amp;394"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A2" To="A3" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=361,ly=415,type=ElbowH,xs=332&amp;391,ys=415&amp;415"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A8" To="A6" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=531,ly=102,type=Elbow,xs=506&amp;555,ys=98&amp;98"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="GET" From="A7" To="A8" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=357,ly=104,type=Elbow,xs=332&amp;382,ys=104&amp;104"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="POST" From="A7" To="A9" Event="FINISH" Id="T6">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=317,ly=202,type=ElbowH,xs=320&amp;320,ys=134&amp;290"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A7" Event="FINISH" Id="T7">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=187,ly=90,type=Elbow,xs=149&amp;224,ys=90&amp;90"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="RETRY" From="A9" To="A9" Event="ERROR" Id="T9">
      <bpm:Attribute Name="TRANSITION_DELAY" Value="30s"/>
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=326,ly=292,type=Curve,xs=367&amp;382,ys=329&amp;266"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="3"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A9" To="A5" Event="FINISH" Id="T12">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=517,ly=318,type=Elbow,xs=425&amp;563,ys=320&amp;320"/>
    </bpm:Transition>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=11,y=13,w=202,h=27"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Variables Name="headersMap" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.util.Map"/>
    </bpm:Variables>
    <bpm:Variables Name="httpMethod" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
    <bpm:Variables Name="requestDoc" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="org.apache.xmlbeans.XmlObject"/>
    </bpm:Variables>
    <bpm:Variables Name="responseDoc" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.StringDocument"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>