activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=243,y=29,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=45,ly=44,type=Elbow,xs=239&114,ys=49&188
  - id: T3
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=273,ly=89,type=Elbow,xs=273&273,ys=73&106
  - id: T5
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=392,ly=117,type=Elbow,xs=307&458,ys=49&184
- id: A3
  name: Timer 1
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: ${delay1}
    Unit: Seconds
    WORK_DISPLAY_INFO: x=64,y=192,w=100,h=60
  transitions:
  - id: T8
    to: A9
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=146,ly=264,type=Elbow,xs=118&118,ys=256&297
- id: A4
  name: Timer 2
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: ${delay2}
    Unit: Seconds
    WORK_DISPLAY_INFO: x=229,y=110,w=100,h=60
  transitions:
  - id: T6
    to: A10
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=274,ly=182,type=Elbow,xs=282&282,ys=174&200
- id: A5
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=260,y=397,w=60,h=40
- id: A6
  name: Timer 3
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: ${delay3}
    Unit: Seconds
    WORK_DISPLAY_INFO: x=408,y=188,w=100,h=60
  transitions:
  - id: T10
    to: A11
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=459,ly=273,type=Elbow,xs=459&459,ys=252&295
- id: A8
  name: Sync
  implementor: com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    Synced Activities: Timer 1#Timer 2
    WORK_DISPLAY_INFO: x=243,y=288,w=100,h=60
  transitions:
  - id: T7
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=290,ly=370,type=Elbow,xs=290&290,ys=352&393
- id: A9
  name: Dummy 1
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=88,y=301,w=60,h=40
  transitions:
  - id: T12
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=196,ly=321,type=Elbow,xs=152&239,ys=321&321
- id: A10
  name: Dummy 2
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=252,y=204,w=60,h=40
  transitions:
  - id: T9
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=282,ly=266,type=Elbow,xs=282&282,ys=248&284
- id: A11
  name: Dummy 3
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=429,y=299,w=60,h=40
  transitions:
  - id: T11
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=387,ly=319,type=Elbow,xs=425&347,ys=319&319
variables:
  delay1:
    type: java.lang.Integer
    category: INPUT
  delay2:
    type: java.lang.Integer
    category: INPUT
  delay3:
    type: java.lang.Integer
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=21,y=12,w=147,h=27
