<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="RpcWebService" version="0.4" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=76,y=92,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=510,y=92,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Invoke Employee&#13;&#10;Service" Implementation="com.centurylink.mdw.workflow.adapter.soap.MdwRpcWebServiceAdapter">
      <bpm:Attribute Name="DO_LOGGING" Value="True"/>
      <bpm:Attribute Name="REQUEST_VARIABLE" Value="requestDoc"/>
      <bpm:Attribute Name="RESPONSE_VARIABLE" Value="responseDoc"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=273,y=80,w=111,h=67"/>
      <bpm:Attribute Name="WSDL" Value="#{props['mdw.services.url']}/SOAP/MDWWebService?WSDL"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=248,ly=53,type=Elbow,xs=140&amp;269,ys=112&amp;112"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=454,ly=112,type=Elbow,xs=388&amp;506,ys=112&amp;112"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=31,y=26,w=144,h=27"/>
    <bpm:Variables Name="requestDoc" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="org.w3c.dom.Document"/>
    </bpm:Variables>
    <bpm:Variables Name="responseDoc" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.StringDocument"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>