{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=52,y=79,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=184,ly=98,type=Elbow,xs=116&193,ys=99&99"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=405,y=82,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "mrid = runtimeContext.getMasterRequestId();",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=197,y=74,w=127,h=74"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Set mrid variable\r\nfrom runtimeContext",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=365,ly=102,type=Elbow,xs=328&401,ys=102&102"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=28,y=21,w=147,h=27"
  },
  "textNotes": [{
    "attributes": {"WORK_DISPLAY_INFO": "x=137,y=191,w=309,h=38"},
    "content": "TODO: Test other runtimeContext access\r\nbesides masterRequestId.",
    "id": "N4"
  }],
  "variables": {"mrid": {
    "category": "LOCAL",
    "type": "java.lang.String"
  }},
  "version": "0.2"
}