{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=55,y=120,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=185,ly=102,type=Elbow,xs=119&208,ys=140&140"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=414,y=121,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString(); ",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=212,y=113,w=100,h=60"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Set Info",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=364,ly=141,type=Elbow,xs=316&410,ys=141&141"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=41,y=37,w=240,h=27"
  },
  "variables": {
    "procName": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "procVer": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  },
  "version": "10.2"
}