activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=45,y=107,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=161,ly=127,xs=109&213,ys=127&127
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=428,y=106,w=60,h=40
- id: A3
  name: Set Ver Info
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java","Child 2 Set Info"],["false","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["false","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    Rule: "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString();"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=217,y=96,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=372,ly=126,xs=321&424,ys=126&126
variables:
  inputVar:
    type: java.lang.String
    category: INPUT
  procName:
    type: java.lang.String
    category: OUTPUT
  procVer:
    type: java.lang.String
    category: OUTPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=22,y=27,w=182,h=27
