<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="SmartProcessChildCompat" version="10.2" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=55,y=120,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=414,y=121,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Set Info" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="procName = runtimeContext.getProcess().getName();&#13;&#10;procVer = runtimeContext.getProcess().getVersionString(); "/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=212,y=113,w=100,h=60"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=185,ly=102,type=Elbow,xs=119&amp;208,ys=140&amp;140"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=364,ly=141,type=Elbow,xs=316&amp;410,ys=141&amp;141"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=41,y=37,w=240,h=27"/>
    <bpm:Variables Name="procName" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
    <bpm:Variables Name="procVer" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>