activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    WORK_DISPLAY_INFO: x=60,y=91,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=176,ly=90,type=Elbow,xs=124&220,ys=111&111
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    WORK_DISPLAY_INFO: x=420,y=94,w=60,h=40
- id: A3
  name: Set Info
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    Rule: "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString(); "
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=224,y=85,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=376,ly=114,type=Elbow,xs=328&416,ys=114&114
variables:
  inputVar:
    type: java.lang.String
    category: INPUT
  procName:
    type: java.lang.String
    category: OUTPUT
  procVer:
    type: java.lang.String
    category: OUTPUT
attributes:
  NodeStyle: BoxIcon
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=32,y=16,w=172,h=27
