activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=93,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=172,ly=112,xs=124&220,ys=112&112
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=423,y=94,w=60,h=40
- id: A3
  name: Set Info
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Monitors: '[["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java","sub ${inputVar}"],["false","Test Cases","com.centurylink.mdw.testing/TestCaseActivityMonitor.java",""],["false","Zipkin Activity","com.centurylink.mdw.zipkin/TraceActivityMonitor.java",""]]'
    Rule: "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString();"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=224,y=85,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=373,ly=114,xs=328&418,ys=114&114
variables:
  inputVar:
    type: java.lang.String
    category: INPUT
  procName:
    type: java.lang.String
    category: OUTPUT
  procVer:
    type: java.lang.String
    category: OUTPUT
attributes:
  NodeStyle: BoxIcon
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=32,y=16,w=172,h=27
