activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    WORK_DISPLAY_INFO: x=45,y=108,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=185,ly=138,type=Elbow,xs=109&213,ys=128&128
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    WORK_DISPLAY_INFO: x=425,y=105,w=60,h=40
- id: A3
  name: Set Ver Info
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Monitors: '[["false","Activity Timing","com.centurylink.mdw.base/ActivityTimingMonitor.java",""],["true","Milestone","com.centurylink.mdw.milestones/ActivityMilestone.java",""]]'
    Rule: "procName = runtimeContext.getProcess().getName();\r\nprocVer = runtimeContext.getProcess().getVersionString();"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=217,y=96,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=376,ly=125,type=Elbow,xs=321&421,ys=125&125
variables:
  inputVar:
    type: java.lang.String
    category: INPUT
  procName:
    type: java.lang.String
    category: OUTPUT
  procVer:
    type: java.lang.String
    category: OUTPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=22,y=27,w=182,h=27
