activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=250,y=11,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=253,ly=9,type=Elbow,xs=246&207,ys=31&161
  - id: T3
    to: A10
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=283,ly=63,type=Elbow,xs=289&289,ys=55&84
  - id: T6
    to: A9
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=322,ly=28,type=Elbow,xs=314&338,ys=32&32
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=261,y=400,w=60,h=40
- id: A3
  name: "Query Using\r\nJDBC URL"
  implementor: com.centurylink.mdw.workflow.adapter.db.JdbcSqlAdapter
  attributes:
    OsgiBundleSymbolicName: com.centurylink.donsservicemix
    Output Documents: userDocument
    PostScript: "import java.sql.ResultSet\r\nimport com.centurylink.mdw.model.user.User\r\n\r\nResultSet rs = (ResultSet) response;\r\nif (rs.next()) {\r\n    User user = new User();\r\n    user.setCuid(rs.getString(\"cuid\"))\r\n    user.setName(rs.getString(\"name\"))\r\n    userDocument = user.getJson();\r\n}\r\nelse {\r\n    throw new RuntimeException(\"User query returns no results: \" + runtimeContext.getAttributes().get(\"sqlQuery\"));\r\n}"
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    WORK_DISPLAY_INFO: x=101,y=124,w=102,h=75
    jdbcDataSource: MDWDataSource
    parameterVariable: userCuid
    queryType: Select
    sqlQuery: select * from USER_INFO where cuid = ?
  transitions:
  - id: T2
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=181,ly=246,type=Elbow,xs=152&278,ys=203&289
- id: A4
  name: "Query Multiple Params,\r\nMultiple Results"
  implementor: com.centurylink.mdw.workflow.adapter.db.JdbcSqlAdapter
  attributes:
    OsgiBundleSymbolicName: com.centurylink.donsservicemix
    Output Documents: mdwSupportUsers
    PostScript: "import java.sql.ResultSet\r\n\r\nResultSet rs = (ResultSet) response;\r\nmdwSupportUsers = new ArrayList<String>();\r\nwhile (rs.next()) {\r\n  mdwSupportUsers.add(rs.getString(\"name\"));\r\n}\r\n"
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    WORK_DISPLAY_INFO: x=304,y=185,w=145,h=78
    jdbcDataSource: MDWDataSource
    parameterVariable: userCuids
    queryType: Select
    sqlQuery: "select * from USER_INFO ui, USER_GROUP_MAPPING ugm, USER_GROUP ug\r\nwhere ui.user_info_id = ugm.user_info_id\r\nand ugm.user_group_id = ug.user_group_id\r\nand ug.group_name = 'Site Admin'\r\nand (ui.cuid = ? or ui.cuid = ?) \r\norder by cuid desc"
  transitions:
  - id: T5
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=316,ly=276,type=Elbow,xs=316&316,ys=267&289
- id: A5
  name: Sync
  implementor: com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    Synced Activities: "Query Using\r\nJDBC URL#Query Multiple Params,\r\nMultiple Results#Reset\r\nUser Name"
    WORK_DISPLAY_INFO: x=228,y=293,w=100,h=60
  transitions:
  - id: T4
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=291,ly=344,type=Elbow,xs=291&291,ys=357&396
- id: A6
  name: "Update\r\nUser Name"
  implementor: com.centurylink.mdw.workflow.adapter.db.JdbcSqlAdapter
  attributes:
    DESCRIPTION: Where clause is hard-coded to avoid any mishaps due to bad input data.
    WORK_DISPLAY_INFO: x=472,y=13,w=100,h=66
    jdbcDataSource: MDWDataSource
    queryType: Update
    sqlQuery: update USER_INFO set name = 'Don Oakes' where cuid = 'dxoakes'
  transitions:
  - id: T7
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=525,ly=111,type=Elbow,xs=525&525,ys=83&149
- id: A7
  name: "Select User\r\nAnd Bind Name"
  implementor: com.centurylink.mdw.workflow.adapter.db.JdbcSqlAdapter
  attributes:
    OsgiBundleSymbolicName: com.centurylink.donsservicemix
    PostScript: "import java.sql.ResultSet\r\n\r\nResultSet rs = (ResultSet) response;\r\nif (rs.next()) {\r\n  return rs.getString(\"name\");\r\n}"
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    WORK_DISPLAY_INFO: x=479,y=153,w=100,h=72
    jdbcDataSource: MDWDataSource
    queryType: Select
    sqlQuery: select name from USER_INFO where cuid = 'dxoakes'
  transitions:
  - id: T8
    to: A8
    event: FINISH
    resultCode: Don Oakes
    attributes:
      TRANSITION_DISPLAY_INFO: lx=535,ly=248,type=Elbow,xs=527&527,ys=229&287
- id: A8
  name: "Reset\r\nUser Name"
  implementor: com.centurylink.mdw.workflow.adapter.db.JdbcSqlAdapter
  attributes:
    DESCRIPTION: Where clause is hard-coded to avoid any mishaps due to bad input data.
    PostScriptLang: Groovy
    PreScriptLang: Groovy
    WORK_DISPLAY_INFO: x=474,y=291,w=101,h=67
    jdbcDataSource: MDWDataSource
    queryType: Update
    sqlQuery: update USER_INFO set name = 'Donald Oakes' where cuid = 'dxoakes'
  transitions:
  - id: T9
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=401,ly=323,type=Elbow,xs=470&332,ys=323&323
- id: A9
  name: Wait 60s
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '60'
    Unit: Seconds
    WORK_DISPLAY_INFO: x=342,y=13,w=100,h=60
  transitions:
  - id: T10
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=457,ly=43,type=Elbow,xs=446&468,ys=43&43
- id: A10
  name: Wait 10s
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '10'
    Unit: Seconds
    WORK_DISPLAY_INFO: x=268,y=88,w=100,h=60
  transitions:
  - id: T11
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=336,ly=166,type=Elbow,xs=336&336,ys=152&181
variables:
  mdwSupportUsers:
    type: java.util.List<String>
    category: LOCAL
  userCuid:
    type: java.lang.String
    category: INPUT
  userCuids:
    type: java.util.List<String>
    category: INPUT
  userDocument:
    type: org.json.JSONObject
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=21,y=21,w=101,h=27
