{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=64,y=102,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {
          "TRANSITION_DELAY": "5s",
          "TRANSITION_DISPLAY_INFO": "lx=257,ly=122,type=Elbow,xs=128&386,ys=122&122"
        },
        "event": "FINISH",
        "id": "T1",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=390,y=103,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=29,y=25,w=135,h=27"
  }
}