activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=64,y=102,w=60,h=40
  transitions:
  - id: T1
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DELAY: 360s
      TRANSITION_DISPLAY_INFO: lx=257,ly=122,type=Elbow,xs=128&386,ys=122&122
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=390,y=103,w=60,h=40
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=29,y=25,w=135,h=27
