activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=56,y=97,w=60,h=40
  transitions:
  - id: T1
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=261,ly=117,type=Elbow,xs=120&402,ys=117&117
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=406,y=97,w=60,h=40
variables:
  ignoredJson:
    type: org.json.JSONObject
    category: INPUT
    label: (see IgnoredVariables.test)
    display: Hidden
  ignoredString:
    type: java.lang.String
    category: INPUT
    label: (see IgnoredVariables.test)
    display: Hidden
  inputVar:
    type: java.lang.String
    category: INPUT
attributes:
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=23,y=18,w=156,h=27
