activities:
- id: A88
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=57,y=87,w=60,h=40
  transitions:
  - id: T68
    to: A90
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=209,ly=67,type=Elbow,xs=121&241,ys=107&107
- id: A89
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=477,y=87,w=60,h=40
- id: A90
  name: Assign Var Vals
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |
      print 'value of fromParent: ' + fromParent
      toParent = 'returnedValue'
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=245,y=78,w=100,h=60
  transitions:
  - id: T69
    to: A89
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=410,ly=107,type=Elbow,xs=349&473,ys=107&107
variables:
  fromParent:
    type: java.lang.String
    category: INPUT
  toParent:
    type: java.lang.String
    category: OUTPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  START_TRANSITION_ID: '2322718'
  WORK_DISPLAY_INFO: x=17,y=18,w=232,h=27
