activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=260,w=60,h=40
  transitions:
  - id: T1
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=486,ly=-240,type=Elbow,xs=124&166,ys=280&280
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=824,y=261,w=60,h=40
- id: A3
  name: "Invoke Service Subprocess \r\nSync with Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=377,y=47,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromService
    processversion: '[0.1,1)'
    synchronous: 'true'
    variables: '{"varDoc1":"$varDoc1"}'
  transitions:
  - id: T4
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=641,ly=106,type=Elbow,xs=567&854&854,ys=74&74&261
- id: A6
  name: Set Vars
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: '["varDoc1"]'
    Rule: "if (processCase == null)\r\nreturn null;\r\n\r\nvar1 = \"my nice non-document string value\";\r\nvarDoc1 = \"my nice string value\";\r\n\r\nreturn processCase;"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=170,y=250,w=100,h=60
  transitions:
  - id: T9
    to: A3
    event: FINISH
    resultCode: ServiceWithDocsSync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=198,ly=97,type=Elbow,xs=270&323&323&377,ys=280&280&77&77
  - id: T10
    to: A10
    event: FINISH
    resultCode: ServiceNoDocsSync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=273,ly=296,type=Elbow,xs=274&382,ys=284&284
  - id: T11
    to: A11
    event: FINISH
    resultCode: ServiceNoDocsAsync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=202,ly=362,type=Elbow,xs=274&381,ys=280&374
  - id: T12
    to: A9
    event: FINISH
    resultCode: RegularWithDocsSync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=194,ly=445,type=Elbow,xs=270&324&324&379,ys=280&280&461&461
  - id: T13
    to: A12
    event: FINISH
    resultCode: RegularWithDocsAsync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=232,ly=522,type=Elbow,xs=220&220&376,ys=310&546&546
  - id: T14
    to: A13
    event: FINISH
    resultCode: RegularNoDocsSync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=232,ly=609,type=Elbow,xs=220&220&375,ys=310&633&633
  - id: T20
    to: A14
    event: FINISH
    resultCode: RegularNoDocsAsync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=226,ly=694,type=Elbow,xs=220&220&375,ys=310&718&718
  - id: T22
    to: A8
    event: FINISH
    resultCode: ServiceWithDocsAsync
    attributes:
      TRANSITION_DISPLAY_INFO: lx=191,ly=172,type=Elbow,xs=274&371,ys=280&178
- id: A8
  name: "Invoke Service Subprocess \r\nAsync with Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=375,y=148,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromService
    processversion: '[0.1,1)'
    synchronous: 'false'
    variables: '{"varDoc1":"$varDoc1"}'
  transitions:
  - id: T8
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=563,ly=163,type=Elbow,xs=565&854&854,ys=167&167&261
- id: A9
  name: "Invoke Regular Subprocess \r\nSync with Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=379,y=431,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromRegular
    processversion: '[0.1,1)'
    synchronous: 'true'
    variables: '{"varDoc1":"$varDoc1"}'
  transitions:
  - id: T17
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=694,ly=371,type=Elbow,xs=569&820,ys=461&281
- id: A10
  name: "Invoke Service Subprocess \r\nSync no Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=386,y=258,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromService
    processversion: '[0.1,1)'
    synchronous: 'true'
    variables: '{"var1":"$var1"}'
  transitions:
  - id: T15
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=698,ly=281,type=Elbow,xs=576&820,ys=281&281
- id: A11
  name: "Invoke Service Subprocess \r\nAsync no Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=385,y=344,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromService
    processversion: '[0.1,1)'
    synchronous: 'false'
    variables: '{"var1":"$var1"}'
  transitions:
  - id: T16
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=697,ly=327,type=Elbow,xs=575&820,ys=374&281
- id: A12
  name: "Invoke Regular Subprocess \r\nAsync with Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=376,y=516,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromRegular
    processversion: '[0.1,1)'
    synchronous: 'false'
    variables: '{"varDoc1":"$varDoc1"}'
  transitions:
  - id: T18
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=693,ly=413,type=Elbow,xs=566&820,ys=546&281
- id: A13
  name: "Invoke Regular Subprocess \r\nSync no Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=375,y=603,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromRegular
    processversion: '[0.1,1)'
    synchronous: 'true'
    variables: '{"var1":"$var1"}'
  transitions:
  - id: T19
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=692,ly=457,type=Elbow,xs=565&820,ys=633&281
- id: A14
  name: "Invoke Regular Subprocess \r\nAsync no Doc Binding"
  implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
  attributes:
    WORK_DISPLAY_INFO: x=375,y=688,w=186,h=60
    processname: com.centurylink.mdw.tests.workflow/SubProcessInvocationsFromRegular
    processversion: '[0.1,1)'
    synchronous: 'false'
    variables: '{"var1":"$var1"}'
  transitions:
  - id: T21
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=709,ly=511,type=Elbow,xs=565&854,ys=718&305
variables:
  processCase:
    type: java.lang.String
    category: INPUT
  var1:
    type: java.lang.String
    category: LOCAL
  varDoc1:
    type: com.centurylink.mdw.model.StringDocument
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '9'
  WORK_DISPLAY_INFO: x=17,y=18,w=379,h=27
