activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=60,y=260,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=177,ly=280,xs=124&230,ys=280&280
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=480,y=260,w=60,h=40
- id: A3
  name: Force Error
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |-
      runtimeContext.logDebug("Executing " + runtimeContext.getActivity().getName())
      throw new RuntimeException("Help!")
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=233,y=250,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=407,ly=280,xs=338&476,ys=280&280
subprocesses:
- id: P1
  name: Exception Handler
  activities:
  - id: A4
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=439,y=98,w=60,h=40
    transitions:
    - id: T3
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: type=Elbow,lx=533,ly=118,xs=503&563,ys=118&118
  - id: A6
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      WORK_DISPLAY_INFO: x=739,y=98,w=60,h=40
  - id: A7
    name: "Subprocess \nfrom Embedded"
    implementor: com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity
    attributes:
      WORK_DISPLAY_INFO: x=568,y=87,w=105,h=66
      processname: com.centurylink.mdw.tests.workflow/SubprocessForEmbedded.proc
      processversion: '[0.4,1)'
      synchronous: 'true'
      variables: '{"fromParent":"$passToSub","toParent":"$receiveFromSub"}'
    transitions:
    - id: T4
      to: A6
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: type=Elbow,lx=705,ly=118,xs=676&735,ys=118&118
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=399,y=58,w=440,h=120
variables:
  passToSub:
    type: java.lang.String
    category: INPUT
  receiveFromSub:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=50,y=50,w=0,h=0
