activities:
- id: A34
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=55,y=100,w=60,h=40
  transitions:
  - id: T27
    to: A31
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=157,ly=119,type=Elbow,xs=119&191,ys=120&120
- id: A32
  name: Wait for a while
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '1'
    WORK_DISPLAY_INFO: x=384,y=94,w=100,h=60
    Unit: Minutes
  transitions:
  - id: T26
    to: A33
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=523,ly=121,type=Elbow,xs=488&554,ys=122&122
- id: A33
  name: Finish
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=558,y=102,w=60,h=40
- id: A31
  name: Calculate sqaure
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    WORK_DISPLAY_INFO: x=195,y=93,w=100,h=60
    SCRIPT: Groovy
    Rule: 'result = argument * argument;   '
  transitions:
  - id: T28
    to: A32
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=340,ly=123,type=Elbow,xs=299&380,ys=123&123
variables:
  argument:
    type: java.lang.Integer
    category: INOUT
  newvar:
    type: java.lang.Boolean
    category: INOUT
  result:
    type: java.lang.Long
    category: OUTPUT
  testxml:
    type: org.w3c.dom.Document
    category: INPUT
attributes:
  NodeStyle: BoxIcon
  SLA_UNIT: Minutes
  START_TRANSITION_ID: '2326941'
  Transition with no Label: Acts as Default
  SLA: '20'
  WORK_DISPLAY_INFO: x=31,y=23,w=192,h=27
  PROCESS_VISIBILITY: PUBLIC
