activities:
- id: A30
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=21,y=179,w=60,h=40
  transitions:
  - id: T24
    to: A26
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=124,ly=256,type=Elbow,xs=85&162,ys=199&199
- id: A27
  name: Not executed
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    WORK_DISPLAY_INFO: x=448,y=287,w=100,h=60
  transitions:
  - id: T23
    to: A28
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=633,ly=242,type=Elbow,xs=552&701,ys=317&176
- id: A28
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=705,y=156,w=60,h=40
- id: A26
  name: Throw an Exception
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    Java: |
      /**
       * Copyright (c) 2016 CenturyLink, Inc. All Rights Reserved.
       */

      package com.centurylink.mdw.tests.workflow;

      import java.util.Map;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      /**
       * Dynamic Java to force an error.
       */
      public class ThrowanException_A26 implements JavaExecutor {

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
          }

          public Object execute(Map<String, Object> variables) throws JavaExecutionException {
              throw new RuntimeException("Help me, I'm an error");
          }

      }
    WORK_DISPLAY_INFO: x=166,y=176,w=132,h=69
  transitions:
  - id: T20
    to: A29
    event: RESUME
    resultCode: AltAction
    attributes:
      TRANSITION_DELAY: '0'
      TRANSITION_DISPLAY_INFO: lx=373,ly=126,type=Elbow,xs=302&444,ys=210&54
      TRANSITION_RETRY_COUNT: '0'
  - id: T22
    to: A27
    event: FINISH
    resultCode: 'no'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=380,ly=265,type=Elbow,xs=302&444,ys=210&317
  - id: T25
    to: A28
    event: FINISH
    resultCode: 'yes'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=508,ly=186,type=ElbowV,xs=302&701,ys=186&186
- id: A29
  name: Alternate path
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    OsgiBundleSymbolicName: com.centurylink.mdw.workflow
    Rule: runtimeContext.logInfo("In alternate path");
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=448,y=24,w=100,h=60
  transitions:
  - id: T21
    to: A28
    event: FINISH
    attributes:
      TRANSITION_DELAY: '0'
      TRANSITION_DISPLAY_INFO: lx=605,ly=126,type=Elbow,xs=552&701,ys=54&176
      TRANSITION_RETRY_COUNT: '0'
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  START_TRANSITION_ID: '2326876'
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=43,y=29,w=202,h=27
