activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=56,y=133,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=174,ly=153,type=Elbow,xs=120&210,ys=153&153
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=476,y=133,w=60,h=40
- id: A3
  name: PopulateVariables
  implementor: com.centurylink.mdw.tests.workflow.PopulateVar
  attributes:
    WORK_DISPLAY_INFO: x=214,y=123,w=155,h=55
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=424,ly=153,type=Elbow,xs=373&472,ys=153&153
variables:
  intListVar:
    type: java.util.List<Integer>
    category: LOCAL
  longListVar:
    type: java.util.List<Long>
    category: LOCAL
  stringListVar:
    type: java.util.List<String>
    category: LOCAL
  stringMapVar:
    type: java.util.Map<String,String>
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  SLA: '20'
  SLA_UNIT: Minutes
  Transition with no Label: Acts as Default
  WORK_DISPLAY_INFO: x=50,y=50,w=169,h=27
