activities:
- id: A2
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=36,y=208,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=188,ly=195,type=Elbow,xs=100&230,ys=228&228
- id: A4
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=490,y=212,w=60,h=40
- id: A1
  name: Check
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    TIMER_WAIT: '2'
    WORK_DISPLAY_INFO: x=159,y=363,w=100,h=60
    Unit: Minutes
  transitions:
  - id: T4
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DELAY: '0'
      TRANSITION_RETRY_COUNT: '0'
      TRANSITION_DISPLAY_INFO: lx=325,ly=316,type=Elbow,xs=263&263&320&320,ys=359&307&307&262
- id: A3
  name: Event Wait
  implementor: com.centurylink.mdw.workflow.activity.event.EventWaitActivity
  attributes:
    STATUS_AFTER_EVENT: Hold
    $+Id: '472083'
    WAIT_EVENT_NAMES: NonTaskAction-{$MasterRequestID},NonTaskAction,false
    STATUS_AFTER_TIMEOUT: Hold
    WORK_DISPLAY_INFO: x=234,y=200,w=100,h=60
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=390,ly=233,type=Elbow,xs=338&486,ys=232&232
  - id: T3
    to: A1
    event: DELAY
    attributes:
      TRANSITION_DELAY: '0'
      TRANSITION_RETRY_COUNT: '0'
      TRANSITION_DISPLAY_INFO: lx=200,ly=293,type=Elbow,xs=246&246,ys=264&359
subprocesses:
- id: P2
  name: Exception Handler
  activities:
  - id: A5
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=398,y=71,w=60,h=40
    transitions:
    - id: T6
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=491,ly=91,type=Elbow,xs=462&519,ys=91&91
  - id: A6
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      WORK_DISPLAY_INFO: x=698,y=71,w=60,h=40
  - id: A7
    name: Event Wait Fallout
    implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
    attributes:
      Wait for Task: 'TRUE'
      STATUS_AFTER_EVENT: Cancelled
      WORK_DISPLAY_INFO: x=523,y=61,w=105,h=61
      TASK_TEMPLATE: com.centurylink.mdw.tests.workflow/Event Wait Fallout.task
      TASK_TEMPLATE_assetVersion: '[0.2,1)'
    transitions:
    - id: T5
      to: A6
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=663,ly=91,type=Elbow,xs=632&694,ys=91&91
  variables:
    EmbeddedSubProcessTaskAction:
      type: java.lang.String
      category: LOCAL
  attributes:
    WORK_DISPLAY_INFO: x=358,y=31,w=440,h=120
    START_TRANSITION_ID: '2327293'
    ENTRY_TRANSITION_ID: '2327303'
    PROCESS_VISIBILITY: EMBEDDED
attributes:
  NodeStyle: BoxIcon
  SLA_UNIT: Minutes
  START_TRANSITION_ID: '2327302'
  Transition with no Label: Acts as Default
  ArrowStyle: ArrowEnd
  SLA: '20'
  WORK_DISPLAY_INFO: x=38,y=63,w=248,h=27
  PROCESS_VISIBILITY: PUBLIC
  ERROR_PROCESS_ID: '-3'
  ERROR_TRANSITION_ID: '68528'
