<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="TimerWaitActivityOrder" version="0.2" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=26,y=76,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=493,y=269,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Wait 20s" Implementation="com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TIMER_WAIT" Value="20"/>
      <bpm:Attribute Name="Unit" Value="Seconds"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=224,y=68,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Should Finish&#13;&#10;Quickly" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="def appendVal = {&#13;&#10;    sleep 100;&#13;&#10;    cumulativeResult += it&#13;&#10;}&#13;&#10;0.upto(9, appendVal)"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=227,y=154,w=98,h=68"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Sync" Implementation="com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="Synced Activities" Value="New Execute Script"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=472,y=162,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Update&#13;&#10;Result" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="cumulativeResult += '_update'"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=369,y=61,w=106,h=68"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A3" To="A6" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=348,ly=101,type=Elbow,xs=328&amp;365,ys=98&amp;98"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A5" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=404,ly=168,type=Elbow,xs=329&amp;468,ys=192&amp;192"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A6" To="A5" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=444,ly=74,type=Elbow,xs=479&amp;522&amp;522,ys=90&amp;90&amp;162"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A5" To="A2" Event="FINISH" Id="T6">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=523,ly=245,type=Elbow,xs=523&amp;523,ys=226&amp;265"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T7">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=155,ly=96,type=Elbow,xs=90&amp;220,ys=96&amp;96"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A4" Event="FINISH" Id="T8">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=157,ly=141,type=Elbow,xs=90&amp;223,ys=96&amp;188"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=29,y=21,w=210,h=27"/>
    <bpm:Variables Name="cumulativeResult" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>