activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=63,y=138,w=60,h=40
  transitions:
  - id: T1
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=156,ly=159,xs=128&184,ys=159&159
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=533,y=248,w=60,h=40
- id: A3
  name: increment n
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |-
      if (n == null)
          n = 0

      n++
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=328,y=133,w=100,h=60
  transitions:
  - id: T4
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=381,ly=217,xs=381&381,ys=197&237
- id: A4
  name: dummy
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=188,y=140,w=60,h=40
  transitions:
  - id: T3
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=288,ly=160,xs=252&324,ys=160&160
- id: A5
  name: stop?
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: n > loops
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=340,y=241,w=85,h=56
  transitions:
  - id: T2
    to: A2
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=459,ly=249,xs=428&529,ys=268&268
  - id: T5
    to: A4
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DELAY: ${delay}s
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=269,ly=249,xs=340&218&218,ys=269&269&180
      TRANSITION_RETRY_COUNT: ${max}
variables:
  delay:
    type: java.lang.Integer
    category: INPUT
  loops:
    type: java.lang.Integer
    category: INPUT
  max:
    type: java.lang.Integer
    category: INPUT
  n:
    type: java.lang.Integer
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  PerformanceLevel: '0'
  WORK_DISPLAY_INFO: x=50,y=50,w=0,h=0
