activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=57,y=140,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=233,ly=184,type=Elbow,xs=121&232,ys=160&160
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=477,y=140,w=60,h=40
- id: A3
  name: Update Vars
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Output Documents: inputJsonable#inputYaml#localJsonable#localYaml
    Rule: "import com.centurylink.mdw.tests.workflow.Person\r\n\r\n// assign local variables\r\nlocalJsonable = new Person()\r\nlocalJsonable.firstName = 'donald'\r\nlocalJsonable.lastName = 'oakes'\r\n\r\nlocalYaml = new Person()\r\nlocalYaml.firstName = 'manoj'\r\nlocalYaml.lastName = 'agrawal'\r\n\r\n// update input variables\r\ninputJsonable.lastName = 'Torvalds'\r\ninputYaml.lastName = 'Richards'"
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=236,y=134,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=411,ly=160,type=Elbow,xs=340&473,ys=160&160
variables:
  inputJsonable:
    type: com.centurylink.mdw.common.service.Jsonable
    category: INPUT
  inputYaml:
    type: org.yaml.snakeyaml.Yaml
    category: INPUT
  localJsonable:
    type: com.centurylink.mdw.common.service.Jsonable
    category: LOCAL
  localYaml:
    type: org.yaml.snakeyaml.Yaml
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=29,y=27,w=130,h=27
