activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=342,y=24,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=470,ly=78,type=Elbow,xs=372&372,ys=68&147
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=174,y=475,w=60,h=40
- id: A3
  name: "Send\r\nVia"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: ${sendVia}
    SCRIPT: javax.el
    WORK_DISPLAY_INFO: x=325,y=151,w=94,h=71
  transitions:
  - id: T2
    to: A5
    event: FINISH
    resultCode: smtp
    attributes:
      TRANSITION_DISPLAY_INFO: lx=292,ly=164,type=Elbow,xs=321&258,ys=186&266
  - id: T3
    to: A4
    event: FINISH
    resultCode: sendgrid
    attributes:
      TRANSITION_DISPLAY_INFO: lx=420,ly=164,type=Elbow,xs=423&490,ys=186&267
- id: A5
  name: SMTP
  implementor: com.centurylink.mdw.workflow.activity.notification.EmailNotificationActivity
  attributes:
    CCGroups: '["MDW Support"]'
    NoticeGroups: '["Developers"]'
    RecipientsExpression: '${recipientList != null ? recipientList : recipient}'
    WORK_DISPLAY_INFO: x=154,y=236,w=100,h=60
    from: mdwdev@centurylink.com
    noticeType: SMTP
    subject: Test Email via SMTP
    template: com.centurylink.mdw.base/emailTemplate.html
    template_assetVersion: '[0.1,1)'
  transitions:
  - id: T4
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=204,ly=322,type=Elbow,xs=204&204,ys=300&345
- id: A4
  name: SendGrid
  implementor: com.centurylink.mdw.sendgrid.SendgridActivity
  attributes:
    CCGroups: '["MDW Support"]'
    NoticeGroups: '["Developers"]'
    RecipientsExpression: '${recipientList ? recipientList : recipient}'
    WORK_DISPLAY_INFO: x=494,y=237,w=100,h=60
    from: mdw.support@centurylink.com
    subject: Test Email via SendGrid
    template: com.centurylink.mdw.base/emailTemplate.html
    template_assetVersion: '[0.1,1)'
  transitions:
  - id: T6
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=544,ly=322,type=Elbow,xs=544&544,ys=301&344
- id: A6
  name: "SMTP\r\nTask"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.notifications/SmtpTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=153,y=349,w=103,h=68
    Wait for Task: 'true'
  transitions:
  - id: T5
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=204,ly=446,type=Elbow,xs=204&204,ys=421&471
- id: A7
  name: "SendGrid\r\nTask"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.notifications/SendgridTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=495,y=348,w=102,h=70
    Wait for Task: 'true'
  transitions:
  - id: T7
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=546,ly=444,type=Elbow,xs=546&546,ys=422&471
- id: A8
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=516,y=475,w=60,h=40
variables:
  recipient:
    type: java.lang.String
    category: INPUT
  recipientList:
    type: java.util.List<String>
    category: INPUT
  sendVia:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=61,y=26,w=63,h=27
textNotes:
- id: N9
  content: For manual testing
  attributes:
    WORK_DISPLAY_INFO: x=52,y=70,w=174,h=26
