activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=54,y=145,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=152,ly=165,xs=118&186,ys=165&165
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=533,y=146,w=60,h=40
- id: A3
  name: Notify
  implementor: com.centurylink.mdw.slack.SlackActivity
  attributes:
    WORK_DISPLAY_INFO: x=189,y=135,w=100,h=60
    message: com.centurylink.mdw.slack/message.json
    message_assetVersion: '[0.1,1)'
    webhookUrl: ${props['mdw.slack.webhook.url']}
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=319,ly=166,xs=294&344,ys=166&166
- id: A4
  name: |-
    Slack
    Task
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    TASK_TEMPLATE: com.centurylink.mdw.tests.notifications/SlackTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=348,y=138,w=100,h=60
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=490,ly=166,xs=452&528,ys=166&166
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=47,y=47,w=52,h=26
textNotes:
- id: N1
  content: For manual testing
  attributes:
    WORK_DISPLAY_INFO: x=144,y=47,w=190,h=28
