/*
 * Copyright (C) 2017 CenturyLink, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.centurylink.mdw.java;

import java.io.IOException;
import java.util.Hashtable;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.tools.FileObject;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import javax.tools.JavaFileObject.Kind;

import com.centurylink.mdw.util.log.LoggerUtil;
import com.centurylink.mdw.util.log.StandardLogger;

public class MdwJavaFileManager <M extends JavaFileManager> extends ForwardingJavaFileManager<M> {

    private static StandardLogger logger = LoggerUtil.getStandardLogger();

    private static Map<String,JavaFileObject> jfoCache = new ConcurrentHashMap<>();

    public static JavaFileObject getJavaFileObject(String className) {
        return jfoCache.get(className);
    }

    public static void clearJfoCache() {
        jfoCache.clear();
    }

    public MdwJavaFileManager(M fileManager) {
        super(fileManager);
    }

    /**
     * Create a new Java file object which will be used by the compiler to
     * store the generated byte code. Also add a reference to the object to the
     * cache so it can be accessed by other parts of the application.
     */
    public JavaFileObject getJavaFileForOutput(Location location, String className, Kind kind, FileObject sibling)
    throws IOException {
        if (logger.isMdwDebugEnabled())
            logger.mdwDebug("Loading Dynamic Java byte code from: " + (sibling == null ? null : sibling.toUri()));
        try {
            JavaFileObject jfo = new ByteArrayJavaFileObject(className, kind);
            jfoCache.putIfAbsent(className, jfo);
            return jfo;
        }
        catch (Exception ex) {
            logger.severeException(ex.getMessage(), ex);
            throw new IOException(ex.getMessage(), ex);
        }
    }
}

