activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=64,y=123,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=190,ly=91,type=Elbow,xs=128&201,ys=143&143
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=570,y=121,w=60,h=40
- id: A3
  name: "Assign\r\nLocal Float"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: localFloat = 3.1416f
    WORK_DISPLAY_INFO: x=205,y=104,w=99,h=74
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=349,ly=142,type=Elbow,xs=308&393,ys=142&142
- id: A4
  name: "Custom\r\nCategory Task"
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.cloud/customCategoryTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=397,y=106,w=99,h=72
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=533,ly=141,type=Elbow,xs=500&566,ys=141&141
variables:
  assignedFloat:
    type: java.lang.Float
    category: LOCAL
  inputFloat:
    type: java.lang.Float
    category: INPUT
  localFloat:
    type: java.lang.Float
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=36,y=27,w=155,h=27
