<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="CustomBaseData" version="0.3" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=64,y=123,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=570,y=121,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Assign&#13;&#10;Local Float" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity">
      <bpm:Attribute Name="Rule" Value="localFloat = 3.1416f"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=205,y=104,w=99,h=74"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Custom&#13;&#10;Category Task" Implementation="com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity">
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
      <bpm:Attribute Name="Category" Value="PLN"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="IndexProvider" Value="com.centurylink.mdw.services.task.CustomTaskIndexProvider"/>
      <bpm:Attribute Name="Notices" Value="Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;"/>
      <bpm:Attribute Name="SLAUnits" Value="Hours"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TaskLogicalId" Value="CustomBaseData:A4"/>
      <bpm:Attribute Name="TaskName" Value="Custom Category Task"/>
      <bpm:Attribute Name="Variables" Value="inputFloat,inputFloat,Not Displayed,0,,java.lang.Float;localFloat,localFloat,Not Displayed,0,,java.lang.Float"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=397,y=106,w=99,h=72"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=190,ly=91,type=Elbow,xs=128&amp;201,ys=143&amp;143"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A4" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=349,ly=142,type=Elbow,xs=308&amp;393,ys=142&amp;142"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=533,ly=141,type=Elbow,xs=500&amp;566,ys=141&amp;141"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=36,y=27,w=155,h=27"/>
    <bpm:Variables Name="assignedFloat" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.Float"/>
    </bpm:Variables>
    <bpm:Variables Name="inputFloat" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Float"/>
    </bpm:Variables>
    <bpm:Variables Name="localFloat" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.Float"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>