{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=45,y=84,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=159,ly=82,type=Elbow,xs=109&159,ys=104&104"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=420,y=77,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=163,y=74,w=104,h=57"},
      "id": "A3",
      "implementor": "com.centurylink.mdw.tests.cloud.DynamicJavaGeneralActivity",
      "name": "Dynamic Java\r\nGeneral Activity",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=363,ly=97,type=Elbow,xs=271&416,ys=97&97"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=31,y=20,w=186,h=27"
  },
  "variables": {"varSetByGenActivity": {
    "category": "LOCAL",
    "type": "java.lang.String"
  }},
  "version": "0.2"
}