<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="DynamicActivityImpl" version="0.2" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=45,y=84,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=420,y=77,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="Dynamic Java&#13;&#10;General Activity" Implementation="com.centurylink.mdw.tests.cloud.DynamicJavaGeneralActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=163,y=74,w=104,h=57"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=159,ly=82,type=Elbow,xs=109&amp;159,ys=104&amp;104"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=363,ly=97,type=Elbow,xs=271&amp;416,ys=97&amp;97"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=31,y=20,w=186,h=27"/>
    <bpm:Variables Name="varSetByGenActivity" ReferredAs="" Category="LOCAL" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>