activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=74,y=159,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=166,ly=178,xs=138&195,ys=178&178
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=692,y=158,w=60,h=40
- id: A3
  name: before
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |-
      runtimeContext.logDebug("Executing " + runtimeContext.getActivity().getName())
      beforeVar = 'initial version'
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=199,y=149,w=100,h=60
  transitions:
  - id: T3
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=342,ly=181,xs=303&381,ys=181&181
- id: A4
  name: after
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: |-
      runtimeContext.logDebug("Executing " + runtimeContext.getActivity().getName())
      afterVar = 'initial version' // to be changed for instance
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=534,y=151,w=100,h=60
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=663,ly=178,xs=639&688,ys=178&178
- id: A5
  name: Pause
  implementor: com.centurylink.mdw.base.PauseActivity
  attributes:
    WORK_DISPLAY_INFO: x=384,y=162,w=60,h=40
  transitions:
  - id: T4
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=489,ly=181,xs=449&530,ys=181&181
variables:
  afterVar:
    type: java.lang.String
    category: LOCAL
  beforeVar:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=43,y=38,w=183,h=26
textNotes:
- id: N1
  content: For manual testing
  attributes:
    WORK_DISPLAY_INFO: x=46,y=75,w=152,h=32
