activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=70,y=100,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=160,ly=120,xs=134&186,ys=120&120
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=480,y=100,w=60,h=40
- id: A3
  name: Pause
  implementor: com.centurylink.mdw.base.PauseActivity
  attributes:
    WORK_DISPLAY_INFO: x=190,y=100,w=60,h=40
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=280,ly=120,xs=254&306,ys=120&120
- id: A4
  name: JavaStuff
  implementor: com.centurylink.mdw.workflow.activity.java.DynamicJavaActivity
  attributes:
    ClassName: InflightDynamicJava_A4
    Java: |
      package com.centurylink.mdw.tests.cloud;

      import java.util.Map;

      import com.centurylink.mdw.java.JavaExecutionException;
      import com.centurylink.mdw.java.JavaExecutor;
      import com.centurylink.mdw.java.MdwJavaException;
      import com.centurylink.mdw.model.workflow.ActivityRuntimeContext;

      public class InflightDynamicJava_A4 implements JavaExecutor {
          private ActivityRuntimeContext context;

          public void initialize(ActivityRuntimeContext context) throws MdwJavaException {
              this.context = context;
          }

          public Object execute(Map<String,Object> variables) throws JavaExecutionException  {
              context.logDebug("Executing " + context.getActivity().getName());
              variables.put("version", "original");
              return null;
          }
      }
    WORK_DISPLAY_INFO: x=310,y=90,w=100,h=60
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: type=Elbow,lx=445,ly=120,xs=414&476,ys=120&120
variables:
  version:
    type: java.lang.String
    category: LOCAL
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=24,y=27,w=196,h=26
