{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=43,y=147,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=170,ly=167,xs=107&233,ys=167&167"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=507,y=253,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=237,y=144,w=100,h=60"},
      "id": "A3",
      "implementor": "com.centurylink.mdw.tests.cloud.MyKotlinActivity",
      "name": "Kotlin Impl",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=426,ly=203,xs=341&502,ys=174&273"},
        "event": "FINISH",
        "id": "T2",
        "resultCode": "myOutcome",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=0,h=0"
  },
  "variables": {"stringVar": {
    "category": "LOCAL",
    "type": "java.lang.String"
  }}
}