{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=35,y=86,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=139,ly=88,type=Elbow,xs=99&161,ys=106&106"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=463,y=90,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "WORK_DISPLAY_INFO": "x=165,y=74,w=101,h=70",
        "processname": "com.centurylink.mdw.tests.cloud/JaxbDocument",
        "processversion": "[0.8,1)",
        "synchronous": "TRUE",
        "variables": "actionRequest=$actionRequest;assetDefinedJaxb=$assetDefinedJaxbIn"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity",
      "name": "Invoke\r\nJaxbDocument",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=299,ly=86,type=Elbow,xs=270&320,ys=109&109"},
        "event": "FINISH",
        "id": "T2",
        "to": "A4"
      }]
    },
    {
      "attributes": {
        "Rule": "import com.centurylink.mdw.common.service.types.Parameter;\r\n\r\noptionalElement = assetDefinedJaxbIn.getOptionalElement()\r\noptionalAttr = assetDefinedJaxbIn.getOptionalAttribute()\r\nactionName = actionRequest.getAction().getName()\r\ninsertedParam = null\r\nfor (Parameter param : actionRequest.getAction().getParameter()) {\r\n    if (param.getName().equals('insertedParam'))\r\n        insertedParam = param.getValue()\r\n}",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=324,y=73,w=106,h=71"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Pull\r\nValues",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=443,ly=110,type=Elbow,xs=434&459,ys=110&110"},
        "event": "FINISH",
        "id": "T3",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=27,y=21,w=207,h=27"
  },
  "description": "Renamed from e:\\workspaces\\mdw\\mdw-workflow\\assets\\com\\centurylink\\mdw\\tests\\ParentProc.proc",
  "variables": {
    "actionName": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "actionRequest": {
      "category": "INPUT",
      "type": "javax.xml.bind.JAXBElement"
    },
    "assetDefinedJaxbIn": {
      "category": "INPUT",
      "type": "javax.xml.bind.JAXBElement"
    },
    "insertedParam": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "optionalAttr": {
      "category": "LOCAL",
      "type": "java.lang.String"
    },
    "optionalElement": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }
  }
}