{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=260,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=294,ly=285,type=Elbow,xs=124&256,ys=280&280"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=481,y=260,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "DO_LOGGING": "true",
        "REQUEST_VARIABLE": "ServiceRequest",
        "RESPONSE_VARIABLE": "ServiceResponse",
        "WORK_DISPLAY_INFO": "x=260,y=244,w=127,h=69",
        "override_inbox": "false",
        "topic": "Q.MDWTEST.ORDEH.EVENT.UPDA.MIDD50.DEVINT143",
        "uri": "rvd://239.75.2.3:7523/omahfd.qwest.net:7523"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.adapter.tibco.PoolableTibcoBusAdapter",
      "name": "PoolableBusAdapter",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=440,ly=280,type=Elbow,xs=391&477,ys=280&280"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=231,h=27"
  },
  "variables": {
    "ServiceRequest": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "ServiceResponse": {
      "category": "LOCAL",
      "type": "org.w3c.dom.Document"
    }
  },
  "version": "0.4"
}