{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=60,y=260,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=300,ly=284,type=Elbow,xs=124&202,ys=280&280"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=480,y=260,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Bus Topic": "Q.MDWTEST.ORDEH.EVENT.UPDA.MIDD50.DEVINT143",
        "DO_LOGGING": "True",
        "Override Inbox": "False",
        "PostScriptLang": "Groovy",
        "PreScriptLang": "Groovy",
        "REQUEST_VARIABLE": "ServiceRequest",
        "RESPONSE_VARIABLE": "ServiceResponse",
        "Response Timeout (sec)": "60",
        "Synchronous Response Required": "true",
        "WORK_DISPLAY_INFO": "x=206,y=245,w=191,h=69"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.adapter.tibco.SynchronousBusAdapter",
      "name": "SynchronousBusAdapter",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=439,ly=280,type=Elbow,xs=401&476,ys=280&280"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=223,h=27"
  },
  "variables": {
    "ServiceRequest": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "ServiceResponse": {
      "category": "OUTPUT",
      "type": "org.w3c.dom.Document"
    }
  },
  "version": "0.3"
}