{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=55,y=220,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=207,ly=194,type=Elbow,xs=119&216,ys=240&240"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=475,y=220,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Rule": "throw new Exception(\"Fallout\")",
        "WORK_DISPLAY_INFO": "x=220,y=210,w=101,h=74"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Throw\r\nException",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=397,ly=240,type=Elbow,xs=325&471,ys=240&240"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=21,y=24,w=142,h=27"
  },
  "subprocesses": [{
    "activities": [
      {
        "attributes": {"WORK_DISPLAY_INFO": "x=302,y=80,w=60,h=40"},
        "id": "A7",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
        "name": "Start",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=392,ly=100,type=Elbow,xs=366&417,ys=100&100"},
          "event": "FINISH",
          "id": "T3",
          "to": "A4"
        }]
      },
      {
        "attributes": {
          "STATUS_AFTER_EVENT": "Cancelled",
          "TASK_PAGELET": "com.centurylink.mdw.base/CustomManualTask.pagelet",
          "TASK_TEMPLATE": "com.centurylink.mdw.tests.tasks/Fallout Test Task.task",
          "TASK_TEMPLATE_assetVersion": "[0.1,1)",
          "WORK_DISPLAY_INFO": "x=421,y=70,w=111,h=62"
        },
        "id": "A4",
        "implementor": "com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity",
        "name": "Fallout Test Task",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=567,ly=100,type=Elbow,xs=536&598,ys=100&100"},
          "event": "FINISH",
          "id": "T4",
          "to": "A8"
        }]
      },
      {
        "attributes": {
          "DoNotNotifyCaller": "false",
          "WORK_DISPLAY_INFO": "x=602,y=80,w=60,h=40"
        },
        "id": "A8",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
        "name": "Stop"
      }
    ],
    "attributes": {
      "EMBEDDED_PROCESS_TYPE": "Exception Handler",
      "PROCESS_VISIBILITY": "EMBEDDED",
      "WORK_DISPLAY_INFO": "x=262,y=40,w=440,h=120"
    },
    "id": "P6",
    "name": "Exception Handler"
  }],
  "textNotes": [{
    "attributes": {"WORK_DISPLAY_INFO": "x=29,y=64,w=197,h=22"},
    "content": "TODO: Test all features.",
    "id": "N5"
  }],
  "version": "0.2"
}