activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=55,y=220,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=207,ly=194,type=Elbow,xs=119&216,ys=240&240
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=475,y=220,w=60,h=40
- id: A3
  name: "Throw\r\nException"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity
  attributes:
    Rule: throw new Exception("Fallout")
    WORK_DISPLAY_INFO: x=220,y=210,w=101,h=74
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=397,ly=240,type=Elbow,xs=325&471,ys=240&240
subprocesses:
- id: P6
  name: Exception Handler
  activities:
  - id: A7
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=302,y=80,w=60,h=40
    transitions:
    - id: T3
      to: A4
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=392,ly=100,type=Elbow,xs=366&417,ys=100&100
  - id: A4
    name: Fallout Test Task
    implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
    attributes:
      STATUS_AFTER_EVENT: Cancelled
      TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
      TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/Fallout Test Task.task
      TASK_TEMPLATE_assetVersion: '[0.1,1)'
      WORK_DISPLAY_INFO: x=421,y=70,w=111,h=62
    transitions:
    - id: T4
      to: A8
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=567,ly=100,type=Elbow,xs=536&598,ys=100&100
  - id: A8
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=602,y=80,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Exception Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=262,y=40,w=440,h=120
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=21,y=24,w=142,h=27
textNotes:
- id: N5
  content: 'TODO: Test all features.'
  attributes:
    WORK_DISPLAY_INFO: x=29,y=64,w=197,h=22
