{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=61,y=206,w=60,h=40"},
      "id": "A39",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=210,ly=193,type=Elbow,xs=125&252,ys=226&226"},
        "event": "FINISH",
        "id": "T33",
        "to": "A40"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=515,y=210,w=60,h=40"},
      "id": "A38",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "30",
        "Unit": "Seconds",
        "WORK_DISPLAY_INFO": "x=184,y=361,w=100,h=60"
      },
      "id": "A41",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Check",
      "transitions": [{
        "attributes": {
          "TRANSITION_DELAY": "0",
          "TRANSITION_DISPLAY_INFO": "lx=349,ly=317,type=Elbow,xs=288&288&345&345,ys=357&305&305&264",
          "TRANSITION_RETRY_COUNT": "0"
        },
        "event": "FINISH",
        "id": "T36",
        "to": "A40"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Hold",
        "STATUS_AFTER_TIMEOUT": "Hold",
        "TASK_PAGELET": "com.centurylink.mdw.base/CustomManualTask.pagelet",
        "TASK_TEMPLATE": "com.centurylink.mdw.tests.tasks/Manual task that also waits for event.task",
        "TASK_TEMPLATE_assetVersion": "[0.1,1)",
        "WAIT_EVENT_NAMES": "NonTaskAction-{$MasterRequestID},NonTaskAction,true",
        "WORK_DISPLAY_INFO": "x=256,y=200,w=100,h=60"
      },
      "id": "A40",
      "implementor": "com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity",
      "name": "Task that also waits for event",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=412,ly=231,type=Elbow,xs=360&511,ys=230&230"},
          "event": "FINISH",
          "id": "T34",
          "to": "A38"
        },
        {
          "attributes": {
            "TRANSITION_DELAY": "0",
            "TRANSITION_DISPLAY_INFO": "lx=163,ly=291,type=Elbow,xs=270&270,ys=264&357",
            "TRANSITION_RETRY_COUNT": "0"
          },
          "event": "FINISH",
          "id": "T35",
          "resultCode": "NonTaskAction",
          "to": "A41"
        }
      ]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "ERROR_PROCESS_ID": "-3",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2327205",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=29,y=39,w=214,h=27"
  },
  "subprocesses": [{
    "activities": [
      {
        "attributes": {"WORK_DISPLAY_INFO": "x=330,y=72,w=60,h=40"},
        "id": "A44",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
        "name": "Start",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=425,ly=92,type=Elbow,xs=394&456,ys=92&92"},
          "event": "FINISH",
          "id": "T32",
          "to": "A43"
        }]
      },
      {
        "attributes": {"WORK_DISPLAY_INFO": "x=630,y=72,w=60,h=40"},
        "id": "A42",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
        "name": "Stop"
      },
      {
        "attributes": {
          "STATUS_AFTER_EVENT": "Cancelled",
          "TASK_PAGELET": "com.centurylink.mdw.base/AutoFormManualTask.pagelet",
          "TASK_TEMPLATE": "com.centurylink.mdw.tests.tasks/Task and Event Fallout.task",
          "TASK_TEMPLATE_assetVersion": "[0.1,1)",
          "WORK_DISPLAY_INFO": "x=460,y=61,w=100,h=60",
          "Wait for Task": "TRUE"
        },
        "id": "A43",
        "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
        "name": "Task And Event\r\nFallout",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=595,ly=92,type=Elbow,xs=564&626,ys=92&92"},
          "event": "FINISH",
          "id": "T31",
          "to": "A42"
        }]
      }
    ],
    "attributes": {
      "ENTRY_TRANSITION_ID": "2327206",
      "PROCESS_VISIBILITY": "EMBEDDED",
      "START_TRANSITION_ID": "2327196",
      "WORK_DISPLAY_INFO": "x=290,y=32,w=440,h=120"
    },
    "id": "SubProcess4",
    "name": "Exception Handler",
    "variables": {"EmbeddedSubProcessTaskAction": {
      "category": "LOCAL",
      "type": "java.lang.String"
    }}
  }]
}