<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="MDWTestGeneralManualTask" version="0.12" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=93,y=76,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Autoform General Task" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="AlertInterval" Value="8"/>
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
      <bpm:Attribute Name="Category" Value="COM"/>
      <bpm:Attribute Name="FormName" Value="Autoform"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="Notices" Value="Open,,,;Assigned,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Forward,,,;"/>
      <bpm:Attribute Name="SLAUnits" Value="Days"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TaskLogicalId" Value="MDWTestGeneralManualTask:A6"/>
      <bpm:Attribute Name="TaskName" Value="Autoform General Task"/>
      <bpm:Attribute Name="TaskSLA" Value="1"/>
      <bpm:Attribute Name="Variables" Value="MasterRequest,Master Request,Required,2,,com.centurylink.mdw.model.FormDataDocument;IntegerVar,Integer Var,Required,3,IntegerKey,java.lang.Integer;DateVar,Date Var,Optional,4,,java.util.Date;ArrayVar,Array Var,Optional,5,,java.lang.String[];NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=77,y=186,w=100,h=60"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
      <bpm:Attribute Name="IndexProvider" Value="com.centurylink.mdw.services.task.AutoFormTaskIndexProvider"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="TerminationAction" Value="Complete Process and Cancel Tasks"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=481,y=126,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="General Task" Implementation="com.centurylink.mdw.workflow.activity.task.FormDataDocumentManualTaskActivity">
      <bpm:Attribute Name="AlertInterval" Value="540"/>
      <bpm:Attribute Name="Category" Value="COM"/>
      <bpm:Attribute Name="FormDataVar" Value="MasterRequest"/>
      <bpm:Attribute Name="FormName" Value="TestTask"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="Indices" Value="State#City"/>
      <bpm:Attribute Name="Notices" Value="Open,,0,;Assigned,,0,;Failed,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Hold,,,;Forward,,,"/>
      <bpm:Attribute Name="RecipientVar" Value="benjxu@yahoo.com"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="Task Description" Value="This is a task for testing MDW 5.1 style task&#10;template, which contains indices and groups"/>
      <bpm:Attribute Name="TaskId" Value="184667"/>
      <bpm:Attribute Name="TaskLogicalId" Value="MDWTestGeneralManualTask:A3"/>
      <bpm:Attribute Name="TaskName" Value="General Task"/>
      <bpm:Attribute Name="TaskSLA" Value="72"/>
      <bpm:Attribute Name="Variables" Value="ArrayVar,ArrayVar,Not Displayed,0,,java.lang.String[];DateVar,DateVar,Not Displayed,0,,java.util.Date;IntegerVar,IntegerVar,Not Displayed,0,,java.lang.Integer;MasterRequest,MasterRequest,Not Displayed,0,,com.centurylink.mdw.model.FormDataDocument;NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=68,y=305,w=100,h=60"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
      <bpm:Attribute Name="SLAUnits" Value="Hours"/>
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Notify MDWTeam" Implementation="com.centurylink.mdw.workflow.activity.notification.EmailNotificationActivity">
      <bpm:Attribute Name="CCEmails" Value="benjxu@yahoo.com"/>
      <bpm:Attribute Name="ContinueDespiteMessagingException" Value="true"/>
      <bpm:Attribute Name="Documentation" Value="&lt;html>&#13;&#10;  &lt;head>&#13;&#10;&#13;&#10;  &lt;/head>&#13;&#10;  &lt;body>&#13;&#10;    &lt;p style=&quot;margin-top: 0&quot;>&#13;&#10;      &#13;&#10;    &lt;/p>&#13;&#10;  &lt;/body>&#13;&#10;&lt;/html>&#13;&#10;"/>
      <bpm:Attribute Name="RecipientVar" Value="mdw.development@centurylink.com"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=467,y=306,w=100,h=60"/>
      <bpm:Attribute Name="from" Value="mdw@centurylink.com"/>
      <bpm:Attribute Name="host" Value="mailgate.uswc.uswest.com"/>
      <bpm:Attribute Name="noticeType" Value="E-Mail"/>
      <bpm:Attribute Name="subject" Value="Test Notification Activity"/>
      <bpm:Attribute Name="template" Value="com.centurylink.mdw.base/mdwNotification.html"/>
      <bpm:Attribute Name="template_assetVersion" Value="[0.4,1)"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="JSF Task" Implementation="com.centurylink.mdw.workflow.activity.task.FormDataDocumentManualTaskActivity">
      <bpm:Attribute Name="AlertInterval" Value="480"/>
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
      <bpm:Attribute Name="Category" Value="COM"/>
      <bpm:Attribute Name="FormDataVar" Value="MasterRequest"/>
      <bpm:Attribute Name="FormName" Value="jsf:JiyangTestForm"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="Indices" Value="State#City"/>
      <bpm:Attribute Name="Notices" Value="Open,,0,;Assigned,taskAssignEmail,com.centurylink.mdw.workflow.task.notifier.TaskEmailNotifier,com.centurylink.mdw.workflow.task.notifier.TaskEmailNotifier;Failed,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Hold,,,;Forward,,,"/>
      <bpm:Attribute Name="RecipientVar" Value="benjxu@yahoo.com"/>
      <bpm:Attribute Name="SLAUnits" Value="Hours"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="Task Description" Value="This is a task for testing MDW 5.1 style task&#10;template, which contains indices and groups"/>
      <bpm:Attribute Name="TaskLogicalId" Value="MDWTestGeneralManualTask:A5"/>
      <bpm:Attribute Name="TaskName" Value="JSF Task"/>
      <bpm:Attribute Name="TaskSLA" Value="72"/>
      <bpm:Attribute Name="Variables" Value="ArrayVar,ArrayVar,Not Displayed,0,,java.lang.String[];DateVar,DateVar,Not Displayed,0,,java.util.Date;IntegerVar,IntegerVar,Not Displayed,0,,java.lang.Integer;MasterRequest,MasterRequest,Not Displayed,0,,com.centurylink.mdw.model.FormDataDocument;NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=260,y=305,w=100,h=60"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=470,ly=262,type=Elbow,xs=511&amp;511,ys=302&amp;170"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A5" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=220,ly=299,type=Elbow,xs=172&amp;256,ys=335&amp;335"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A5" To="A4" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=416,ly=335,type=Elbow,xs=364&amp;463,ys=335&amp;335"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A6" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=123,ly=151,type=Elbow,xs=123&amp;123,ys=120&amp;182"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A6" To="A3" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=122,ly=275,type=Elbow,xs=122&amp;122,ys=250&amp;301"/>
      <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    </bpm:Transition>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="SLA" Value="0"/>
    <bpm:Attribute Name="SLA_UNIT" Value="Seconds"/>
    <bpm:Attribute Name="TRANSITION_RETRY_COUNT" Value="-1"/>
    <bpm:Attribute Name="Transition with no Label" Value="Acts as Default"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=26,y=22,w=259,h=27"/>
    <bpm:Attribute Name="START_TRANSITION_ID" Value="2327946"/>
    <bpm:Variables Name="ArrayVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String[]"/>
    </bpm:Variables>
    <bpm:Variables Name="DateVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.util.Date"/>
    </bpm:Variables>
    <bpm:Variables Name="IntegerVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Integer"/>
    </bpm:Variables>
    <bpm:Variables Name="MasterRequest" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="com.centurylink.mdw.model.FormDataDocument"/>
    </bpm:Variables>
    <bpm:Variables Name="NotDisplayed" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
    <bpm:Variables Name="runJsfTask" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Boolean"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>