{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=93,y=76,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=123,ly=151,type=Elbow,xs=123&123,ys=120&182",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T1",
        "to": "A6"
      }]
    },
    {
      "attributes": {
        "AlertInterval": "8",
        "AlertIntervalUnits": "Hours",
        "Category": "COM",
        "FormName": "Autoform",
        "Groups": "MDW Support",
        "IndexProvider": "com.centurylink.mdw.services.task.AutoFormTaskIndexProvider",
        "Notices": "Open,,,;Assigned,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Forward,,,;",
        "SLAUnits": "Days",
        "STATUS_AFTER_EVENT": "Cancelled",
        "TaskLogicalId": "MDWTestGeneralManualTask:A6",
        "TaskName": "Autoform General Task",
        "TaskSLA": "1",
        "Variables": "MasterRequest,Master Request,Required,2,,com.centurylink.mdw.model.FormDataDocument;IntegerVar,Integer Var,Required,3,IntegerKey,java.lang.Integer;DateVar,Date Var,Optional,4,,java.util.Date;ArrayVar,Array Var,Optional,5,,java.lang.String[];NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean",
        "WORK_DISPLAY_INFO": "x=77,y=186,w=100,h=60",
        "Wait for Task": "TRUE"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
      "name": "Autoform General Task",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=122,ly=275,type=Elbow,xs=122&122,ys=250&301",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T2",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "TerminationAction": "Complete Process and Cancel Tasks",
        "WORK_DISPLAY_INFO": "x=481,y=126,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "AlertInterval": "540",
        "AlertIntervalUnits": "Hours",
        "Category": "COM",
        "FormDataVar": "MasterRequest",
        "FormName": "TestTask",
        "Groups": "MDW Support",
        "Indices": "State#City",
        "Notices": "Open,,0,;Assigned,,0,;Failed,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Hold,,,;Forward,,,",
        "RecipientVar": "benjxu@yahoo.com",
        "SLAUnits": "Hours",
        "STATUS_AFTER_EVENT": "Cancelled",
        "Task Description": "This is a task for testing MDW 5.1 style task\ntemplate, which contains indices and groups",
        "TaskId": "184667",
        "TaskLogicalId": "MDWTestGeneralManualTask:A3",
        "TaskName": "General Task",
        "TaskSLA": "72",
        "Variables": "ArrayVar,ArrayVar,Not Displayed,0,,java.lang.String[];DateVar,DateVar,Not Displayed,0,,java.util.Date;IntegerVar,IntegerVar,Not Displayed,0,,java.lang.Integer;MasterRequest,MasterRequest,Not Displayed,0,,com.centurylink.mdw.model.FormDataDocument;NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean",
        "WORK_DISPLAY_INFO": "x=68,y=305,w=100,h=60",
        "Wait for Task": "TRUE"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.task.FormDataDocumentManualTaskActivity",
      "name": "General Task",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=220,ly=299,type=Elbow,xs=172&256,ys=335&335",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T1",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "CCEmails": "benjxu@yahoo.com",
        "ContinueDespiteMessagingException": "true",
        "Documentation": "<html>\r\n  <head>\r\n\r\n  <\/head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r\n    <\/p>\r\n  <\/body>\r\n<\/html>\r\n",
        "RecipientVar": "mdw.development@centurylink.com",
        "WORK_DISPLAY_INFO": "x=467,y=306,w=100,h=60",
        "from": "mdw@centurylink.com",
        "host": "mailgate.uswc.uswest.com",
        "noticeType": "E-Mail",
        "subject": "Test Notification Activity",
        "template": "com.centurylink.mdw.base/mdwNotification.html",
        "template_assetVersion": "[0.4,1)"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.notification.EmailNotificationActivity",
      "name": "Notify MDWTeam",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=470,ly=262,type=Elbow,xs=511&511,ys=302&170",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "AlertInterval": "480",
        "AlertIntervalUnits": "Hours",
        "Category": "COM",
        "FormDataVar": "MasterRequest",
        "FormName": "jsf:JiyangTestForm",
        "Groups": "MDW Support",
        "Indices": "State#City",
        "Notices": "Open,,0,;Assigned,taskAssignEmail,com.centurylink.mdw.workflow.task.notifier.TaskEmailNotifier,com.centurylink.mdw.workflow.task.notifier.TaskEmailNotifier;Failed,,,;Completed,,,;Cancelled,,,;In Progress,,,;Alert,,,;Jeopardy,,,;Hold,,,;Forward,,,",
        "RecipientVar": "benjxu@yahoo.com",
        "SLAUnits": "Hours",
        "STATUS_AFTER_EVENT": "Cancelled",
        "Task Description": "This is a task for testing MDW 5.1 style task\ntemplate, which contains indices and groups",
        "TaskLogicalId": "MDWTestGeneralManualTask:A5",
        "TaskName": "JSF Task",
        "TaskSLA": "72",
        "Variables": "ArrayVar,ArrayVar,Not Displayed,0,,java.lang.String[];DateVar,DateVar,Not Displayed,0,,java.util.Date;IntegerVar,IntegerVar,Not Displayed,0,,java.lang.Integer;MasterRequest,MasterRequest,Not Displayed,0,,com.centurylink.mdw.model.FormDataDocument;NotDisplayed,NotDisplayed,Not Displayed,0,,java.lang.String;runJsfTask,runJsfTask,Not Displayed,0,,java.lang.Boolean",
        "WORK_DISPLAY_INFO": "x=260,y=305,w=100,h=60",
        "Wait for Task": "TRUE"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.task.FormDataDocumentManualTaskActivity",
      "name": "JSF Task",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=416,ly=335,type=Elbow,xs=364&463,ys=335&335",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T1",
        "to": "A4"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "START_TRANSITION_ID": "2327946",
    "TRANSITION_RETRY_COUNT": "-1",
    "Transition with no Label": "Acts as Default",
    "WORK_DISPLAY_INFO": "x=26,y=22,w=259,h=27"
  },
  "variables": {
    "ArrayVar": {
      "category": "INPUT",
      "type": "java.lang.String[]"
    },
    "DateVar": {
      "category": "INPUT",
      "type": "java.util.Date"
    },
    "IntegerVar": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "MasterRequest": {
      "category": "INPUT",
      "type": "com.centurylink.mdw.model.FormDataDocument"
    },
    "NotDisplayed": {
      "category": "INPUT",
      "type": "java.lang.String"
    },
    "runJsfTask": {
      "category": "INPUT",
      "type": "java.lang.Boolean"
    }
  },
  "version": "0.12"
}