activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=27,y=74,w=60,h=40
  transitions:
  - id: T3
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=180,ly=94,type=Elbow,xs=91&270,ys=94&94
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=579,y=76,w=60,h=40
- id: A4
  name: Master Task
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    Wait for Task: 'TRUE'
    STATUS_AFTER_EVENT: Cancelled
    WORK_DISPLAY_INFO: x=274,y=72,w=100,h=60
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/masterTaskForSubtasks.task
    TASK_TEMPLATE_assetVersion: '[0.3,1)'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=491,ly=96,type=Elbow,xs=378&575,ys=96&96
- id: A5
  name: Subtask A
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    Wait for Task: 'TRUE'
    STATUS_AFTER_EVENT: Cancelled
    WORK_DISPLAY_INFO: x=273,y=150,w=100,h=60
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/subtaskA.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
- id: A6
  name: Subtask B
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    WORK_DISPLAY_INFO: x=274,y=232,w=100,h=60
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/subtaskB.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  WORK_DISPLAY_INFO: x=40,y=26,w=84,h=27
  PROCESS_VISIBILITY: PUBLIC
