<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="Subtasks" version="0.2" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=27,y=74,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=579,y=76,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="Master Task" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/AutoFormManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/masterTaskForSubtasks.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.3,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=274,y=72,w=100,h=60"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Subtask A" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/AutoFormManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/subtaskA.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=273,y=150,w=100,h=60"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Subtask B" Implementation="com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/CustomManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/subtaskB.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=274,y=232,w=100,h=60"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=491,ly=96,type=Elbow,xs=378&amp;575,ys=96&amp;96"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A4" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=180,ly=94,type=Elbow,xs=91&amp;270,ys=94&amp;94"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=40,y=26,w=84,h=27"/>
  </bpm:Process>
</bpm:processDefinition>