activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=29,y=209,w=60,h=40
  transitions:
  - id: T10
    to: A16
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=126,ly=229,type=Elbow,xs=93&132,ys=229&229
      TRANSITION_RETRY_COUNT: '-1'
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=588,y=186,w=60,h=40
- id: A3
  name: "AutoForm Manual Task \r\nw Non Recurring Event"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Hold
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/AutoForm Task with Non-Recurring Event.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WAIT_EVENT_NAMES: C-{$MasterRequestID},CORRECT,true,;A-{$MasterRequestID},ABORT,true,
    WORK_DISPLAY_INFO: x=343,y=140,w=132,h=69
    Wait for Task: 'TRUE'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=549,ly=191,type=Elbow,xs=479&584,ys=197&197
- id: A12
  name: "Custom Manual Task \r\nw Recurring Event"
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Hold
    STATUS_AFTER_TIMEOUT: Hold
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/Custom Manual Task w Recurring Event.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WAIT_EVENT_NAMES: NonTaskAction-{$MasterRequestID},NonTaskAction,true
    WORK_DISPLAY_INFO: x=338,y=220,w=137,h=66
  transitions:
  - id: T7
    to: A14
    event: FINISH
    resultCode: NonTaskAction
    attributes:
      TRANSITION_DISPLAY_INFO: lx=302,ly=305,type=Elbow,xs=405&405,ys=290&339
      TRANSITION_RETRY_COUNT: '-1'
  - id: T9
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=566,ly=223,type=Elbow,xs=479&584,ys=223&223
      TRANSITION_RETRY_COUNT: '-1'
  - id: T13
    to: A2
    event: FINISH
    resultCode: AnotherWay
    attributes:
      TRANSITION_DISPLAY_INFO: lx=512,ly=262,type=Elbow,xs=475&616&616,ys=265&265&230
      TRANSITION_RETRY_COUNT: '-1'
- id: A14
  name: Check
  implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
  attributes:
    Category: COM
    STATUS_AFTER_EVENT: Cancelled
    TIMER_WAIT: '5'
    TaskName: New Task for uuu
    Unit: Seconds
    WORK_DISPLAY_INFO: x=355,y=343,w=100,h=60
  transitions:
  - id: T8
    to: A12
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=405,ly=323,type=Elbow,xs=405&405,ys=339&290
      TRANSITION_RETRY_COUNT: '-1'
- id: A16
  name: Which Task?
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: path
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=136,y=175,w=112,h=85
  transitions:
  - id: T11
    to: A3
    event: FINISH
    resultCode: AutoForm
    attributes:
      TRANSITION_DISPLAY_INFO: lx=268,ly=168,type=Elbow,xs=252&339,ys=192&192
      TRANSITION_RETRY_COUNT: '-1'
  - id: T12
    to: A12
    event: FINISH
    resultCode: Custom
    attributes:
      TRANSITION_DISPLAY_INFO: lx=266,ly=217,type=Elbow,xs=252&334,ys=240&240
      TRANSITION_RETRY_COUNT: '-1'
subprocesses:
- id: P5
  name: TaskEventTest Correction Handler
  activities:
  - id: A6
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=239,y=48,w=60,h=40
    transitions:
    - id: T4
      to: A11
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=336,ly=76,type=Elbow,xs=303&362,ys=68&68
  - id: A7
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=539,y=48,w=60,h=40
  - id: A11
    name: New Timer Wait
    implementor: com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity
    attributes:
      STATUS_AFTER_EVENT: Cancelled
      TIMER_WAIT: '2'
      Unit: Seconds
      WORK_DISPLAY_INFO: x=366,y=35,w=100,h=60
    transitions:
    - id: T6
      to: A7
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=502,ly=68,type=Elbow,xs=470&535,ys=68&68
  attributes:
    EMBEDDED_PROCESS_TYPE: Correction Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=199,y=8,w=440,h=120
- id: P8
  name: Cancellation Handler
  activities:
  - id: A9
    name: Start
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
    attributes:
      WORK_DISPLAY_INFO: x=697,y=52,w=60,h=40
    transitions:
    - id: T5
      to: A10
      event: FINISH
      attributes:
        TRANSITION_DISPLAY_INFO: lx=877,ly=72,type=Elbow,xs=761&993,ys=72&72
  - id: A10
    name: Stop
    implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
    attributes:
      DoNotNotifyCaller: 'false'
      WORK_DISPLAY_INFO: x=997,y=52,w=60,h=40
  attributes:
    EMBEDDED_PROCESS_TYPE: Cancellation Handler
    PROCESS_VISIBILITY: EMBEDDED
    WORK_DISPLAY_INFO: x=657,y=12,w=440,h=120
variables:
  path:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  TRANSITION_RETRY_COUNT: '-1'
  WORK_DISPLAY_INFO: x=50,y=50,w=134,h=27
