<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="TaskIndexTesting" version="0.8" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=41,y=86,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=542,y=84,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="A Custom Task" Implementation="com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity">
      <bpm:Attribute Name="AlertInterval" Value="2"/>
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
      <bpm:Attribute Name="Category" Value="ORD"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="Indices" Value="intIndex,#{intVar},;stringIndex,#{stringVar},;constantIndex,'constIdxVal',;jaxbAttrOneIndex,#{jaxbVar.attributeOne},;jaxbElemTwoIndex,#{jaxbVar.elementTwo},;dateIndex,#{dateVar},;nonExistentIndex,#{nonExistentVar},;stringListItemIndex,#{stringListVar[0]},"/>
      <bpm:Attribute Name="Notices" Value="Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;"/>
      <bpm:Attribute Name="SLAUnits" Value="Hours"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="Task Description" Value="For testing custom task features."/>
      <bpm:Attribute Name="TaskLogicalId" Value="TaskIndexTesting:A3"/>
      <bpm:Attribute Name="TaskName" Value="A Custom Task"/>
      <bpm:Attribute Name="TaskSLA" Value="8"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=389,y=172,w=123,h=64"/>
      <bpm:Attribute Name="taskIndexProvider" Value="com.centurylink.mdw.services.task.CustomTaskIndexProvider"/>
      <bpm:Attribute Name="IndexProvider" Value="com.centurylink.mdw.services.task.CustomTaskIndexProvider"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="An AutoForm Task" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="Category" Value="COM"/>
      <bpm:Attribute Name="FormName" Value="Autoform"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="Notices" Value="Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TaskLogicalId" Value="TaskIndexTesting:A4"/>
      <bpm:Attribute Name="TaskName" Value="An AutoForm Task"/>
      <bpm:Attribute Name="Variables" Value="dateVar,Date Var,Optional,0,dateVarIndex,java.util.Date;intVar,Int Var,Required,0,intVarIndex,java.lang.Integer;isCustom,isCustom,Not Displayed,0,,java.lang.Boolean;jaxbVar,JAXB Var,Read Only,0,,javax.xml.bind.JAXBElement;stringListVar,String List Var,Not Displayed,0,,java.util.List&lt;String>;stringVar,String Var,Required,0,stringVarIndex,java.lang.String"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=310,y=71,w=122,h=66"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
      <bpm:Attribute Name="taskIndexProvider" Value="com.centurylink.mdw.services.task.AutoFormTaskIndexProvider"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="Custom&#13;&#10;?" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptEvaluator">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=172,y=78,w=77,h=57"/>
      <bpm:Attribute Name="SCRIPT" Value="javax.el"/>
      <bpm:Attribute Name="Expression" Value="#{isCustom}"/>
    </bpm:Activity>
    <bpm:Activity Id="A6" Name="Provider&#13;&#10;?" Implementation="com.centurylink.mdw.workflow.activity.script.ScriptEvaluator">
      <bpm:Attribute Name="Expression" Value="isIndexProvider"/>
      <bpm:Attribute Name="SCRIPT" Value="Groovy"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=176,y=198,w=69,h=61"/>
    </bpm:Activity>
    <bpm:Activity Id="A7" Name="Another Custom Task" Implementation="com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity">
      <bpm:Attribute Name="AlertIntervalUnits" Value="Hours"/>
      <bpm:Attribute Name="Category" Value="ORD"/>
      <bpm:Attribute Name="Groups" Value="MDW Support"/>
      <bpm:Attribute Name="IndexProvider" Value="com.centurylink.mdw.tests.tasks.MyTaskIndexProvider"/>
      <bpm:Attribute Name="Notices" Value="Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;"/>
      <bpm:Attribute Name="SLAUnits" Value="Hours"/>
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TaskLogicalId" Value="TaskIndexTesting:A7"/>
      <bpm:Attribute Name="TaskName" Value="Another Custom Task"/>
      <bpm:Attribute Name="Variables" Value="dateVar,dateVar,Not Displayed,0,,java.util.Date;intVar,intVar,Not Displayed,0,,java.lang.Integer;isCustom,isCustom,Not Displayed,0,,java.lang.Boolean;isIndexProvider,isIndexProvider,Not Displayed,0,,java.lang.Boolean;jaxbVar,jaxbVar,Not Displayed,0,,javax.xml.bind.JAXBElement;stringListVar,stringListVar,Not Displayed,0,,java.util.List&lt;String>;stringVar,stringVar,Not Displayed,0,,java.lang.String"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=268,y=306,w=144,h=65"/>
      <bpm:Attribute Name="taskIndexProvider" Value="com.centurylink.mdw.tests.tasks.MyTaskIndexProvider"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A5" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=169,ly=86,type=Elbow,xs=105&amp;168,ys=106&amp;106"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=510,ly=150,type=Elbow,xs=516&amp;538,ys=204&amp;104"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=487,ly=104,type=Elbow,xs=436&amp;538,ys=104&amp;104"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="false" From="A5" To="A4" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=262,ly=83,type=Elbow,xs=253&amp;306,ys=106&amp;106"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="true" From="A5" To="A6" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=224,ly=161,type=Elbow,xs=210&amp;210,ys=139&amp;194"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="false" From="A6" To="A3" Event="FINISH" Id="T6">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=287,ly=196,type=Elbow,xs=249&amp;385,ys=217&amp;217"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="true" From="A6" To="A7" Event="FINISH" Id="T7">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=267,ly=268,type=Elbow,xs=249&amp;340,ys=228&amp;302"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A7" To="A2" Event="FINISH" Id="T8">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=489,ly=234,type=Elbow,xs=416&amp;572,ys=338&amp;128"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=25,y=27,w=159,h=27"/>
    <bpm:Variables Name="dateVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.util.Date"/>
    </bpm:Variables>
    <bpm:Variables Name="intVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Integer"/>
    </bpm:Variables>
    <bpm:Variables Name="isCustom" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Boolean"/>
    </bpm:Variables>
    <bpm:Variables Name="isIndexProvider" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.Boolean"/>
    </bpm:Variables>
    <bpm:Variables Name="jaxbVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="javax.xml.bind.JAXBElement"/>
    </bpm:Variables>
    <bpm:Variables Name="stringListVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.util.List&lt;String>"/>
    </bpm:Variables>
    <bpm:Variables Name="stringVar" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>