activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=41,y=103,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=188,ly=126,type=Elbow,xs=105&211,ys=123&123
  - id: T3
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=161,ly=169,type=Elbow,xs=105&213,ys=123&214
  - id: T5
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=71,ly=201,type=Elbow,xs=71&71,ys=147&255
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=461,y=103,w=60,h=40
- id: A3
  name: "AutoAssigned\r\nTask"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/AutoAssignTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=215,y=88,w=114,h=74
    Wait for Task: 'TRUE'
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=398,ly=123,type=Elbow,xs=333&457,ys=123&123
- id: A4
  name: "AutoAssigned\r\nFrom JAB Elem"
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/AutoAssignedFromJaxbElem.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=217,y=181,w=115,h=66
  transitions:
  - id: T4
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=397,ly=167,type=Elbow,xs=336&457,ys=214&123
- id: A5
  name: "AutoAssigned\r\nFrom JAXB Attr"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/AutoAssignedFromJaxbAttr.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=29,y=259,w=112,h=66
    Wait for Task: 'TRUE'
  transitions:
  - id: T6
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=205,ly=288,type=Elbow,xs=141&491&491,ys=292&292&143
variables:
  jaxbWithAssignee:
    type: javax.xml.bind.JAXBElement
    category: INPUT
  stringAssignee:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=32,y=29,w=146,h=27
