{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=29,y=209,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=126,ly=229,type=Elbow,xs=93&132,ys=229&229",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T10",
        "to": "A16"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=588,y=186,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Category": "COM",
        "FormName": "Autoform",
        "Groups": "MDW Support",
        "IndexProvider": "com.centurylink.mdw.services.task.AutoFormTaskIndexProvider",
        "Notices": "Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;",
        "STATUS_AFTER_EVENT": "Hold",
        "TaskLogicalId": "TaskEventTest:A3",
        "TaskName": "AutoForm Task with Non-Recurring Event",
        "Variables": "FormDataVar,,Not Displayed,0,,com.centurylink.mdw.model.FormDataDocument;path,path,Not Displayed,0,,java.lang.String",
        "WAIT_EVENT_NAMES": "C-{$MasterRequestID},CORRECT,true,;A-{$MasterRequestID},ABORT,true,",
        "WORK_DISPLAY_INFO": "x=343,y=140,w=132,h=69",
        "Wait for Task": "TRUE"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
      "name": "AutoForm Manual Task \r\nw Non Recurring Event",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=549,ly=191,type=Elbow,xs=479&584,ys=197&197"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "AlertIntervalUnits": "Hours",
        "Category": "ORD",
        "Groups": "MDW Support",
        "IndexProvider": "com.centurylink.mdw.services.task.CustomTaskIndexProvider",
        "Notices": "Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;",
        "SLAUnits": "Hours",
        "STATUS_AFTER_EVENT": "Hold",
        "STATUS_AFTER_TIMEOUT": "Hold",
        "TaskLogicalId": "TaskEventTest:A12",
        "TaskName": "Custom Manual Task w Recurring Event",
        "TaskSLA": "48",
        "WAIT_EVENT_NAMES": "NonTaskAction-{$MasterRequestID},NonTaskAction,true",
        "WORK_DISPLAY_INFO": "x=338,y=220,w=137,h=66"
      },
      "id": "A12",
      "implementor": "com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity",
      "name": "Custom Manual Task \r\nw Recurring Event",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=302,ly=305,type=Elbow,xs=405&405,ys=290&339",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T7",
          "resultCode": "NonTaskAction",
          "to": "A14"
        },
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=566,ly=223,type=Elbow,xs=479&584,ys=223&223",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T9",
          "to": "A2"
        },
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=512,ly=262,type=Elbow,xs=475&616&616,ys=265&265&230",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T13",
          "resultCode": "AnotherWay",
          "to": "A2"
        }
      ]
    },
    {
      "attributes": {
        "Category": "COM",
        "STATUS_AFTER_EVENT": "Cancelled",
        "TIMER_WAIT": "5",
        "TaskName": "New Task for uuu",
        "Unit": "Seconds",
        "WORK_DISPLAY_INFO": "x=355,y=343,w=100,h=60"
      },
      "id": "A14",
      "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
      "name": "Check",
      "transitions": [{
        "attributes": {
          "TRANSITION_DISPLAY_INFO": "lx=405,ly=323,type=Elbow,xs=405&405,ys=339&290",
          "TRANSITION_RETRY_COUNT": "-1"
        },
        "event": "FINISH",
        "id": "T8",
        "to": "A12"
      }]
    },
    {
      "attributes": {
        "Expression": "path",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=136,y=175,w=112,h=85"
      },
      "id": "A16",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Which Task?",
      "transitions": [
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=268,ly=168,type=Elbow,xs=252&339,ys=192&192",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T11",
          "resultCode": "AutoForm",
          "to": "A3"
        },
        {
          "attributes": {
            "TRANSITION_DISPLAY_INFO": "lx=266,ly=217,type=Elbow,xs=252&334,ys=240&240",
            "TRANSITION_RETRY_COUNT": "-1"
          },
          "event": "FINISH",
          "id": "T12",
          "resultCode": "Custom",
          "to": "A12"
        }
      ]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "TRANSITION_RETRY_COUNT": "-1",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=134,h=27"
  },
  "subprocesses": [
    {
      "activities": [
        {
          "attributes": {"WORK_DISPLAY_INFO": "x=239,y=48,w=60,h=40"},
          "id": "A6",
          "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
          "name": "Start",
          "transitions": [{
            "attributes": {"TRANSITION_DISPLAY_INFO": "lx=336,ly=76,type=Elbow,xs=303&362,ys=68&68"},
            "event": "FINISH",
            "id": "T4",
            "to": "A11"
          }]
        },
        {
          "attributes": {
            "DoNotNotifyCaller": "false",
            "WORK_DISPLAY_INFO": "x=539,y=48,w=60,h=40"
          },
          "id": "A7",
          "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
          "name": "Stop"
        },
        {
          "attributes": {
            "STATUS_AFTER_EVENT": "Cancelled",
            "TIMER_WAIT": "2",
            "Unit": "Seconds",
            "WORK_DISPLAY_INFO": "x=366,y=35,w=100,h=60"
          },
          "id": "A11",
          "implementor": "com.centurylink.mdw.workflow.activity.timer.TimerWaitActivity",
          "name": "New Timer Wait",
          "transitions": [{
            "attributes": {"TRANSITION_DISPLAY_INFO": "lx=502,ly=68,type=Elbow,xs=470&535,ys=68&68"},
            "event": "FINISH",
            "id": "T6",
            "to": "A7"
          }]
        }
      ],
      "attributes": {
        "EMBEDDED_PROCESS_TYPE": "Correction Handler",
        "PROCESS_VISIBILITY": "EMBEDDED",
        "WORK_DISPLAY_INFO": "x=199,y=8,w=440,h=120"
      },
      "id": "P5",
      "name": "TaskEventTest Correction Handler"
    },
    {
      "activities": [
        {
          "attributes": {"WORK_DISPLAY_INFO": "x=697,y=52,w=60,h=40"},
          "id": "A9",
          "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
          "name": "Start",
          "transitions": [{
            "attributes": {"TRANSITION_DISPLAY_INFO": "lx=877,ly=72,type=Elbow,xs=761&993,ys=72&72"},
            "event": "FINISH",
            "id": "T5",
            "to": "A10"
          }]
        },
        {
          "attributes": {
            "DoNotNotifyCaller": "false",
            "WORK_DISPLAY_INFO": "x=997,y=52,w=60,h=40"
          },
          "id": "A10",
          "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
          "name": "Stop"
        }
      ],
      "attributes": {
        "EMBEDDED_PROCESS_TYPE": "Cancellation Handler",
        "PROCESS_VISIBILITY": "EMBEDDED",
        "WORK_DISPLAY_INFO": "x=657,y=12,w=440,h=120"
      },
      "id": "P8",
      "name": "Cancellation Handler"
    }
  ],
  "variables": {"path": {
    "category": "INPUT",
    "type": "java.lang.String"
  }},
  "version": "0.4"
}