activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=41,y=86,w=60,h=40
  transitions:
  - id: T1
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=169,ly=86,type=Elbow,xs=105&168,ys=106&106
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    DoNotNotifyCaller: 'false'
    WORK_DISPLAY_INFO: x=542,y=84,w=60,h=40
- id: A3
  name: A Custom Task
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/A Custom Task.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=389,y=172,w=123,h=64
    taskIndexProvider: com.centurylink.mdw.services.task.CustomTaskIndexProvider
  transitions:
  - id: T2
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=510,ly=150,type=Elbow,xs=516&538,ys=204&104
- id: A4
  name: An AutoForm Task
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/An AutoForm Task.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=310,y=71,w=122,h=66
    Wait for Task: 'TRUE'
    taskIndexProvider: com.centurylink.mdw.services.task.AutoFormTaskIndexProvider
  transitions:
  - id: T3
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=487,ly=104,type=Elbow,xs=436&538,ys=104&104
- id: A5
  name: "Custom\r\n?"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: '#{isCustom}'
    SCRIPT: javax.el
    WORK_DISPLAY_INFO: x=172,y=78,w=77,h=57
  transitions:
  - id: T4
    to: A4
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=262,ly=83,type=Elbow,xs=253&306,ys=106&106
  - id: T5
    to: A6
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=224,ly=161,type=Elbow,xs=210&210,ys=139&194
- id: A6
  name: "Provider\r\n?"
  implementor: com.centurylink.mdw.workflow.activity.script.ScriptEvaluator
  attributes:
    Expression: isIndexProvider
    SCRIPT: Groovy
    WORK_DISPLAY_INFO: x=176,y=198,w=69,h=61
  transitions:
  - id: T6
    to: A3
    event: FINISH
    resultCode: 'false'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=287,ly=196,type=Elbow,xs=249&385,ys=217&217
  - id: T7
    to: A7
    event: FINISH
    resultCode: 'true'
    attributes:
      TRANSITION_DISPLAY_INFO: lx=267,ly=268,type=Elbow,xs=249&340,ys=228&302
- id: A7
  name: Another Custom Task
  implementor: com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/CustomManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/Another Custom Task.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=268,y=306,w=144,h=65
    taskIndexProvider: com.centurylink.mdw.tests.tasks.MyTaskIndexProvider
  transitions:
  - id: T8
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=489,ly=234,type=Elbow,xs=416&572,ys=338&128
variables:
  dateVar:
    type: java.util.Date
    category: INPUT
  intVar:
    type: java.lang.Integer
    category: INPUT
  isCustom:
    type: java.lang.Boolean
    category: INPUT
  isIndexProvider:
    type: java.lang.Boolean
    category: INPUT
  jaxbVar:
    type: javax.xml.bind.JAXBElement
    category: INPUT
  stringListVar:
    type: java.util.List<String>
    category: INPUT
  stringVar:
    type: java.lang.String
    category: INPUT
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=25,y=27,w=159,h=27
