<bpm:processDefinition schemaVersion="5.5" xmlns:bpm="http://mdw.centurylink.com/bpm">
  <bpm:Process Id="MainProcess" name="TaskAutoAssign" version="0.3" description="">
    <bpm:Activity Id="A1" Name="Start" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessStartActivity">
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=41,y=103,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A2" Name="Stop" Implementation="com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity">
      <bpm:Attribute Name="DoNotNotifyCaller" Value="false"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=461,y=103,w=60,h=40"/>
    </bpm:Activity>
    <bpm:Activity Id="A3" Name="AutoAssigned&#13;&#10;Task" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/AutoFormManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/AutoAssignTask.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=215,y=88,w=114,h=74"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
    </bpm:Activity>
    <bpm:Activity Id="A4" Name="AutoAssigned&#13;&#10;From JAB Elem" Implementation="com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/CustomManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/AutoAssignedFromJaxbElem.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=217,y=181,w=115,h=66"/>
    </bpm:Activity>
    <bpm:Activity Id="A5" Name="AutoAssigned&#13;&#10;From JAXB Attr" Implementation="com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity">
      <bpm:Attribute Name="STATUS_AFTER_EVENT" Value="Cancelled"/>
      <bpm:Attribute Name="TASK_PAGELET" Value="com.centurylink.mdw.base/AutoFormManualTask.pagelet"/>
      <bpm:Attribute Name="TASK_TEMPLATE" Value="com.centurylink.mdw.tests.tasks/AutoAssignedFromJaxbAttr.task"/>
      <bpm:Attribute Name="TASK_TEMPLATE_assetVersion" Value="[0.1,1)"/>
      <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=29,y=259,w=112,h=66"/>
      <bpm:Attribute Name="Wait for Task" Value="TRUE"/>
    </bpm:Activity>
    <bpm:Transition CompletionCode="" From="A1" To="A3" Event="FINISH" Id="T1">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=188,ly=126,type=Elbow,xs=105&amp;211,ys=123&amp;123"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A3" To="A2" Event="FINISH" Id="T2">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=398,ly=123,type=Elbow,xs=333&amp;457,ys=123&amp;123"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A4" Event="FINISH" Id="T3">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=161,ly=169,type=Elbow,xs=105&amp;213,ys=123&amp;214"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A4" To="A2" Event="FINISH" Id="T4">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=397,ly=167,type=Elbow,xs=336&amp;457,ys=214&amp;123"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A1" To="A5" Event="FINISH" Id="T5">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=71,ly=201,type=Elbow,xs=71&amp;71,ys=147&amp;255"/>
    </bpm:Transition>
    <bpm:Transition CompletionCode="" From="A5" To="A2" Event="FINISH" Id="T6">
      <bpm:Attribute Name="TRANSITION_DISPLAY_INFO" Value="lx=205,ly=288,type=Elbow,xs=141&amp;491&amp;491,ys=292&amp;292&amp;143"/>
    </bpm:Transition>
    <bpm:Attribute Name="PROCESS_VISIBILITY" Value="PUBLIC"/>
    <bpm:Attribute Name="NodeStyle" Value="BoxIcon"/>
    <bpm:Attribute Name="ArrowStyle" Value="ArrowEnd"/>
    <bpm:Attribute Name="WORK_DISPLAY_INFO" Value="x=32,y=29,w=146,h=27"/>
    <bpm:Variables Name="jaxbWithAssignee" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="javax.xml.bind.JAXBElement"/>
    </bpm:Variables>
    <bpm:Variables Name="stringAssignee" ReferredAs="" Category="INPUT" DisplaySequence="0">
      <bpm:type Name="java.lang.String"/>
    </bpm:Variables>
  </bpm:Process>
</bpm:processDefinition>