{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=155,y=19,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=302,ly=84,type=Elbow,xs=219&289,ys=39&110"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=488,y=685,w=60,h=40"},
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=250,y=114,w=78,h=48"},
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Step\r\nOne",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=289,ly=209,type=Elbow,xs=289&289,ys=166&273"},
        "event": "FINISH",
        "id": "T2",
        "to": "A4"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=246,y=277,w=83,h=47"},
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Step\r\nTwo",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=291,ly=378,type=Elbow,xs=291&291,ys=328&433"},
          "event": "FINISH",
          "id": "T3",
          "to": "A6"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=388,ly=254,type=Elbow,xs=333&444,ys=300&158"},
          "event": "FINISH",
          "id": "T4",
          "to": "A5"
        }
      ]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=448,y=133,w=78,h=50"},
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Step\r\nThree",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=496,ly=342,type=Elbow,xs=496&496,ys=187&542"},
        "event": "FINISH",
        "id": "T6",
        "to": "A7"
      }]
    },
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=253,y=437,w=80,h=50"},
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.DefaultActivityImpl",
      "name": "Step\r\nFour",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=190,ly=552,type=Elbow,xs=249&134,ys=462&629"},
        "event": "FINISH",
        "id": "T5",
        "to": "A8"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "WORK_DISPLAY_INFO": "x=467,y=546,w=100,h=60"
      },
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity",
      "name": "New Synchronization Activity",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=518,ly=645,type=Elbow,xs=518&518,ys=610&681"},
        "event": "FINISH",
        "id": "T7",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "STATUS_AFTER_EVENT": "Cancelled",
        "TASK_PAGELET": "com.centurylink.mdw.base/AutoFormManualTask.pagelet",
        "TASK_TEMPLATE": "com.centurylink.mdw.tests.tasks/RenderedTask.task",
        "TASK_TEMPLATE_assetVersion": "[0.1,1)",
        "WORK_DISPLAY_INFO": "x=84,y=633,w=101,h=68",
        "Wait for Task": "true"
      },
      "id": "A8",
      "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
      "name": "Rendered\r\nTask",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=326,ly=620,type=Elbow,xs=189&463,ys=667&576"},
        "event": "FINISH",
        "id": "T8",
        "to": "A7"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=36,y=92,w=136,h=27"
  }
}