{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=41,y=86,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=169,ly=86,type=Elbow,xs=105&168,ys=106&106"},
        "event": "FINISH",
        "id": "T1",
        "to": "A5"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=542,y=84,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "AlertInterval": "2",
        "AlertIntervalUnits": "Hours",
        "Category": "ORD",
        "Groups": "MDW Support",
        "IndexProvider": "com.centurylink.mdw.services.task.CustomTaskIndexProvider",
        "Indices": "intIndex,#{intVar},;stringIndex,#{stringVar},;constantIndex,'constIdxVal',;jaxbAttrOneIndex,#{jaxbVar.attributeOne},;jaxbElemTwoIndex,#{jaxbVar.elementTwo},;dateIndex,#{dateVar},;nonExistentIndex,#{nonExistentVar},;stringListItemIndex,#{stringListVar[0]},",
        "Notices": "Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;",
        "SLAUnits": "Hours",
        "STATUS_AFTER_EVENT": "Cancelled",
        "Task Description": "For testing custom task features.",
        "TaskLogicalId": "TaskIndexTesting:A3",
        "TaskName": "A Custom Task",
        "TaskSLA": "8",
        "WORK_DISPLAY_INFO": "x=389,y=172,w=123,h=64",
        "taskIndexProvider": "com.centurylink.mdw.services.task.CustomTaskIndexProvider"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity",
      "name": "A Custom Task",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=510,ly=150,type=Elbow,xs=516&538,ys=204&104"},
        "event": "FINISH",
        "id": "T2",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Category": "COM",
        "FormName": "Autoform",
        "Groups": "MDW Support",
        "Notices": "Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;",
        "STATUS_AFTER_EVENT": "Cancelled",
        "TaskLogicalId": "TaskIndexTesting:A4",
        "TaskName": "An AutoForm Task",
        "Variables": "dateVar,Date Var,Optional,0,dateVarIndex,java.util.Date;intVar,Int Var,Required,0,intVarIndex,java.lang.Integer;isCustom,isCustom,Not Displayed,0,,java.lang.Boolean;jaxbVar,JAXB Var,Read Only,0,,javax.xml.bind.JAXBElement;stringListVar,String List Var,Not Displayed,0,,java.util.List<String>;stringVar,String Var,Required,0,stringVarIndex,java.lang.String",
        "WORK_DISPLAY_INFO": "x=310,y=71,w=122,h=66",
        "Wait for Task": "TRUE",
        "taskIndexProvider": "com.centurylink.mdw.services.task.AutoFormTaskIndexProvider"
      },
      "id": "A4",
      "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
      "name": "An AutoForm Task",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=487,ly=104,type=Elbow,xs=436&538,ys=104&104"},
        "event": "FINISH",
        "id": "T3",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "Expression": "#{isCustom}",
        "SCRIPT": "javax.el",
        "WORK_DISPLAY_INFO": "x=172,y=78,w=77,h=57"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Custom\r\n?",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=262,ly=83,type=Elbow,xs=253&306,ys=106&106"},
          "event": "FINISH",
          "id": "T4",
          "resultCode": "false",
          "to": "A4"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=224,ly=161,type=Elbow,xs=210&210,ys=139&194"},
          "event": "FINISH",
          "id": "T5",
          "resultCode": "true",
          "to": "A6"
        }
      ]
    },
    {
      "attributes": {
        "Expression": "isIndexProvider",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=176,y=198,w=69,h=61"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Provider\r\n?",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=287,ly=196,type=Elbow,xs=249&385,ys=217&217"},
          "event": "FINISH",
          "id": "T6",
          "resultCode": "false",
          "to": "A3"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "lx=267,ly=268,type=Elbow,xs=249&340,ys=228&302"},
          "event": "FINISH",
          "id": "T7",
          "resultCode": "true",
          "to": "A7"
        }
      ]
    },
    {
      "attributes": {
        "AlertIntervalUnits": "Hours",
        "Category": "ORD",
        "Groups": "MDW Support",
        "IndexProvider": "com.centurylink.mdw.tests.tasks.MyTaskIndexProvider",
        "Notices": "Open,,,,;Assigned,,,,;Completed,,,,;Cancelled,,,,;In Progress,,,,;Alert,,,,;Jeopardy,,,,;Forward,,,,;",
        "SLAUnits": "Hours",
        "STATUS_AFTER_EVENT": "Cancelled",
        "TaskLogicalId": "TaskIndexTesting:A7",
        "TaskName": "Another Custom Task",
        "Variables": "dateVar,dateVar,Not Displayed,0,,java.util.Date;intVar,intVar,Not Displayed,0,,java.lang.Integer;isCustom,isCustom,Not Displayed,0,,java.lang.Boolean;isIndexProvider,isIndexProvider,Not Displayed,0,,java.lang.Boolean;jaxbVar,jaxbVar,Not Displayed,0,,javax.xml.bind.JAXBElement;stringListVar,stringListVar,Not Displayed,0,,java.util.List<String>;stringVar,stringVar,Not Displayed,0,,java.lang.String",
        "WORK_DISPLAY_INFO": "x=268,y=306,w=144,h=65",
        "taskIndexProvider": "com.centurylink.mdw.tests.tasks.MyTaskIndexProvider"
      },
      "id": "A7",
      "implementor": "com.centurylink.mdw.workflow.activity.task.CustomManualTaskActivity",
      "name": "Another Custom Task",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "lx=489,ly=234,type=Elbow,xs=416&572,ys=338&128"},
        "event": "FINISH",
        "id": "T8",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=25,y=27,w=159,h=27"
  },
  "variables": {
    "dateVar": {
      "category": "INPUT",
      "type": "java.util.Date"
    },
    "intVar": {
      "category": "INPUT",
      "type": "java.lang.Integer"
    },
    "isCustom": {
      "category": "INPUT",
      "type": "java.lang.Boolean"
    },
    "isIndexProvider": {
      "category": "INPUT",
      "type": "java.lang.Boolean"
    },
    "jaxbVar": {
      "category": "INPUT",
      "type": "javax.xml.bind.JAXBElement"
    },
    "stringListVar": {
      "category": "INPUT",
      "type": "java.util.List<String>"
    },
    "stringVar": {
      "category": "INPUT",
      "type": "java.lang.String"
    }
  },
  "version": "0.8"
}