activities:
- id: A1
  name: Start
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessStartActivity
  attributes:
    WORK_DISPLAY_INFO: x=155,y=19,w=60,h=40
  transitions:
  - id: T1
    to: A3
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=302,ly=84,type=Elbow,xs=219&289,ys=39&110
- id: A2
  name: Stop
  implementor: com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity
  attributes:
    WORK_DISPLAY_INFO: x=488,y=685,w=60,h=40
- id: A3
  name: "Step\r\nOne"
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=250,y=114,w=78,h=48
  transitions:
  - id: T2
    to: A4
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=289,ly=209,type=Elbow,xs=289&289,ys=166&273
- id: A4
  name: "Step\r\nTwo"
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=246,y=277,w=83,h=47
  transitions:
  - id: T3
    to: A6
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=291,ly=378,type=Elbow,xs=291&291,ys=328&433
  - id: T4
    to: A5
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=388,ly=254,type=Elbow,xs=333&444,ys=300&158
- id: A5
  name: "Step\r\nThree"
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=448,y=133,w=78,h=50
  transitions:
  - id: T6
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=496,ly=342,type=Elbow,xs=496&496,ys=187&542
- id: A6
  name: "Step\r\nFour"
  implementor: com.centurylink.mdw.workflow.activity.DefaultActivityImpl
  attributes:
    WORK_DISPLAY_INFO: x=253,y=437,w=80,h=50
  transitions:
  - id: T5
    to: A8
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=190,ly=552,type=Elbow,xs=249&134,ys=462&629
- id: A7
  name: New Synchronization Activity
  implementor: com.centurylink.mdw.workflow.activity.sync.SynchronizationActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    WORK_DISPLAY_INFO: x=467,y=546,w=100,h=60
  transitions:
  - id: T7
    to: A2
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=518,ly=645,type=Elbow,xs=518&518,ys=610&681
- id: A8
  name: "Rendered\r\nTask"
  implementor: com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity
  attributes:
    STATUS_AFTER_EVENT: Cancelled
    TASK_PAGELET: com.centurylink.mdw.base/AutoFormManualTask.pagelet
    TASK_TEMPLATE: com.centurylink.mdw.tests.tasks/RenderedTask.task
    TASK_TEMPLATE_assetVersion: '[0.1,1)'
    WORK_DISPLAY_INFO: x=84,y=633,w=101,h=68
    Wait for Task: 'true'
  transitions:
  - id: T8
    to: A7
    event: FINISH
    attributes:
      TRANSITION_DISPLAY_INFO: lx=326,ly=620,type=Elbow,xs=189&463,ys=667&576
attributes:
  ArrowStyle: ArrowEnd
  NodeStyle: BoxIcon
  PROCESS_VISIBILITY: PUBLIC
  WORK_DISPLAY_INFO: x=36,y=92,w=136,h=27
