spool create_bam_indexes.log;

ALTER TABLE BAM_MASTER_REQUEST ADD (
  PRIMARY KEY
  (MASTER_REQUEST_ROWID)
  USING INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          448K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE BAM_MASTER_REQUEST ADD 
 UNIQUE (SOURCE_SYSTEM, MASTER_REQUEST_ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE BAM_EVENT ADD (
  PRIMARY KEY
  (EVENT_ROWID)
  USING INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          3M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE BAM_EVENT ADD (
  FOREIGN KEY (MASTER_REQUEST_ROWID) 
  REFERENCES BAM_MASTER_REQUEST (MASTER_REQUEST_ROWID));


ALTER TABLE BAM_COMPONENT ADD (
  PRIMARY KEY
  (COMPONENT_ROWID));

ALTER TABLE BAM_COMPONENT ADD (
  FOREIGN KEY (MASTER_REQUEST_ROWID) 
  REFERENCES BAM_MASTER_REQUEST (MASTER_REQUEST_ROWID));

  ALTER TABLE BAM_ATTRIBUTE ADD (
  CONSTRAINT EVENT_ROWID 
  FOREIGN KEY (EVENT_ROWID) 
  REFERENCES BAM_EVENT (EVENT_ROWID));

ALTER TABLE BAM_ATTRIBUTE ADD 
 FOREIGN KEY (MASTER_REQUEST_ROWID)
 REFERENCES BAM_MASTER_REQUEST (MASTER_REQUEST_ROWID);
spool off;
