spool create_bam_tables.log;

CREATE TABLE BAM_MASTER_REQUEST
(
  MASTER_REQUEST_ROWID  NUMBER,
  MASTER_REQUEST_ID     VARCHAR2(64 BYTE)		NOT NULL,
  SOURCE_SYSTEM         VARCHAR2(32 BYTE)		NOT NULL,
  REQUEST_TIME          DATE                    NOT NULL,
  RECORD_TIME           DATE                    NOT NULL
);

CREATE TABLE BAM_EVENT
(
  EVENT_ROWID           NUMBER,
  MASTER_REQUEST_ROWID  NUMBER                  NOT NULL,
  EVENT_NAME            VARCHAR2(40 BYTE)       NOT NULL,
  EVENT_CATEGORY        VARCHAR2(40 BYTE),
  EVENT_SUBCATEGORY     VARCHAR2(40 BYTE),
  SOURCE_SYSTEM         VARCHAR2(40 BYTE),
  EVENT_ID              VARCHAR2(64 BYTE),
  EVENT_DATA            VARCHAR2(4000 BYTE),
  RECORD_TIME           DATE                    NOT NULL,
  EVENT_TIME            DATE                    NOT NULL,
  NOTE                  VARCHAR2(4000 BYTE)
);

CREATE TABLE BAM_ATTRIBUTE
(
  MASTER_REQUEST_ROWID  NUMBER                  NOT NULL,  
  EVENT_ROWID           NUMBER					NOT NULL,
  COMPONENT_ROWID       NUMBER,
  ATTRIBUTE_NAME        VARCHAR2(64 BYTE)       NOT NULL,
  ATTRIBUTE_VALUE       VARCHAR2(4000 BYTE)
);

CREATE TABLE BAM_COMPONENT
(
  COMPONENT_ROWID       NUMBER,
  MASTER_REQUEST_ROWID  NUMBER                  NOT NULL,
  COMPONENT_ID          VARCHAR2(256 BYTE)      NOT NULL,
  COMPONENT_TYPE        VARCHAR2(256 BYTE)
);

CREATE TABLE BAM_COMPONENT_RELATION
(
  COMPONENT_A_ROWID  NUMBER                     NOT NULL,
  COMPONENT_B_ROWID  NUMBER                     NOT NULL,
  RELATION_TYPE      VARCHAR2(32 BYTE)          NOT NULL
);

spool off;
