name: Build Test Publish

# currently disabled because test execution hangs
on:
  push:
    branches:
      - none # master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MDW_HOME: $RUNNER_WORKSPACE/mdw/mdw/cli
      MDW_APP_TOKEN: ${{secrets.MDW_APP_TOKEN}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
      SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
      OSSRH_JIRA_USERNAME: ${{secrets.OSSRH_JIRA_USERNAME}}
      OSSRH_JIRA_PASSWORD: ${{secrets.OSSRH_JIRA_PASSWORD}}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: caching
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle')}}
          restore-keys: ${{runner.os}}-gradle-
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        working-directory: mdw-hub
        run: npm install
      - name: zip assets
        working-directory: mdw
        run: ./gradlew --no-daemon zipAssetPackages
      - name: bats path
        run: echo "::add-path::$RUNNER_WORKSPACE/mdw/mdw/cli/bats/bin"
        shell: bash
      - name: cli path
        run: echo "::add-path::${{env['MDW_HOME']}}/bin"
        shell: bash
      - name: signing key
        run: echo signing.keyId=$SIGNING_KEY_ID > ~/.gradle/gradle.properties
      - name: signing password
        run: echo signing.password=$SIGNING_PASSWORD >> ~/.gradle/gradle.properties
      - name: publish
        working-directory: mdw
        run: ./gradlew --no-daemon --stacktrace testAll # publishAll but need valid OSSRH_* env vars
