name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MDW_HOME: $RUNNER_WORKSPACE/mdw/mdw/cli
      MDW_APP_TOKEN: ${{ secrets.MDW_APP_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        working-directory: mdw-hub
        run: npm install
      - name: gradle version
        working-directory: mdw
        run: ./gradlew -version
#      - name: zip assets
#        working-directory: mdw
#        run: ./gradlew zipAssetPackages
      - name: mdw home temp
        working-directory: mdw
        run: echo MDW_HOME - $MDW_HOME
      - name: bats path
        run: echo "::add-path::$RUNNER_WORKSPACE/mdw/mdw/cli/bats/bin"
        shell: bash
      - name: cli path
        run: echo "::add-path::${{ env['MDW_HOME'] }}/bin"
        shell: bash
      - name: path temp
        working-directory: mdw
        run: echo PATH - $PATH
      - name: publish
        working-directory: mdw
        run: ./gradlew publishGitHub --stacktrace
